/*
 * (c) Copyright, Real-Time Innovations, 2020.  All rights reserved.
 * RTI grants Licensee a license to use, modify, compile, and create derivative
 * works of the software solely for use with RTI Connext DDS. Licensee may
 * redistribute copies of the software provided that all such copies are subject
 * to this license. The software is provided "as is", with no warranty of any
 * type, including any warranty for fitness for any purpose. RTI is under no
 * obligation to maintain or support the software. RTI shall not be liable for
 * any incidental or consequential damages arising out of the use or inability
 * to use the software.
 */


// Resources
const string SA_XML_FILE = "UMAA_SA.xml";

// Participants
const string SA_PROVIDER = "UMAAParticipantLibrary::SAProvider";
const string SA_USER = "UMAAParticipantLibrary::SAUser";


// Writers
const string ACCELLERATIONREPORTWRITER = "AccellerationReportPublisher::AccellerationReportWriter";
const string COMPAUTMENTCONFIGREPORTWRITER = "CompartmentConfigReportPublisher::CompartmentConfigReportWriter";
const string COMPARTMENTCONFIGWRITER = "CompartmentConfigPublisher::CompartmentConfigWriter";
const string CONTACTCOLREGSCLASSIFICATIONSTATUSREPORTWRITER = "ContactCOLREGSClassificationStatusReportPublisher::ContactCOLREGSClassificationStatusReportWriter";
const string CONTACTREMOVEDREPORTWRITER = "ContactRemovedReportPublisher::ContactRemovedReportWriter";
const string CONTACTREPORTWRITER = "ContactReportPublisher::ContactReportWriter";
const string CONTACTREPORT_CONTACTSSETWRITER = "ContactReport_ContactsSetPublisher::ContactReport_ContactsSetWriter";
const string CONTACTVISUALCLASSIFICATIONSTATUSREPORTWRITER = "ContactVisualClassificationStatusReportPublisher::ContactVisualClassificationStatusReportWriter";
const string CTDREPORTWRITER = "CTDReportPublisher::CTDReportWriter";
const string DATETIMEREPORTWRITER = "DateTimeReportPublisher::DateTimeReportWriter";
const string ECEFPOSEREPORTWRITER = "ECEFPoseReportPublisher::ECEFPoseReportWriter";
const string FEATUREIMAGEREMOVEDREPORTWRITER = "FeatureImageRemovedReportPublisher::FeatureImageRemovedReportWriter";
const string FEATUREIMAGEREPORTWRITER = "FeatureImageReportPublisher::FeatureImageReportWriter";
const string GLOBALDEADRECKONINGCOMMANDREPORTWRITER = "GlobalDeadReckoningCommandReportPublisher::GlobalDeadReckoningCommandReportWriter";
const string GLOBALDEADRECKONINGCOMMANDSTATUSWRITER = "GlobalDeadReckoningCommandStatusPublisher::GlobalDeadReckoningCommandStatusWriter";
const string GLOBALPOSECONFIGREPORTWRITER = "GlobalPoseConfigReportPublisher::GlobalPoseConfigReportWriter";
const string GLOBALPOSEREPORTWRITER = "GlobalPoseReportPublisher::GlobalPoseReportWriter";
const string IMAGEREMOVEDREPORTWRITER = "ImageRemovedReportPublisher::ImageRemovedReportWriter";
const string IMAGEREPORTWRITER = "ImageReportPublisher::ImageReportWriter";
const string LOCALDEADRECKONINGCOMMANDREPORTWRITER = "LocalDeadReckoningCommandReportPublisher::LocalDeadReckoningCommandReportWriter";
const string LOCALDEADRECKONINGCOMMANDSTATUSWRITER = "LocalDeadReckoningCommandStatusPublisher::LocalDeadReckoningCommandStatusWriter";
const string LOCALPOSEREPORTWRITER = "LocalPoseReportPublisher::LocalPoseReportWriter";
const string NEDVELOCITYREPORTWRITER = "NEDVelocityReportPublisher::NEDVelocityReportWriter";
const string PATHREPORTERSPECSREPORTWRITER = "PathReporterSpecsReportPublisher::PathReporterSpecsReportWriter";
const string PATHREPORTERREPORTWRITER = "PathReporterReportPublisher::PathReporterReportWriter";
const string RANGECONFIGREPORTWRITER = "RangeConfigReportPublisher::RangeConfigReportWriter";
const string RANGESPECSREPORTWRITER = "RangeSpecsReportPublisher::RangeSpecsReportWriter";
const string RANGEREPORTWRITER = "RangeReportPublisher::RangeReportWriter";
const string SEASTATUSREPORTWRITER = "SeaStatusReportPublisher::SeaStatusReportWriter";
const string SPEEDREPORTWRITER = "SpeedReportPublisher::SpeedReportWriter";
const string STILLIMAGECONFIGREPORTWRITER = "StillImageConfigReportPublisher::StillImageConfigReportWriter";
const string STILLIMAGESPECSREPORTWRITER = "StillImageSpecsReportPublisher::StillImageSpecsReportWriter";
const string STILLIMAGEREPORTWRITER = "StillImageReportPublisher::StillImageReportWriter";
const string TRANSLATIONALSHIPMOTIONREPORTWRITER = "TranslationalShipMotionReportPublisher::TranslationalShipMotionReportWriter";
const string VEHICLENAVIGATIONMODEREPORTWRITER = "VehicleNavigationModeReportPublisher::VehicleNavigationModeReportWriter";
const string VELOCITYREPORTWRITER = "VelocityReportPublisher::VelocityReportWriter";
const string WATERCURRENTSTATUSREPORTWRITER = "WaterCurrentStatusReportPublisher::WaterCurrentStatusReportWriter";
const string WATERSPACEREPORTWRITER = "WaterspaceReportPublisher::WaterspaceReportWriter";
const string WEATHERSTATUSREPORTWRITER = "WeatherStatusReportPublisher::WeatherStatusReportWriter";
const string WINDSTATUSREPORTWRITER = "WindStatusReportPublisher::WindStatusReportWriter";
const string LOCALDEADRECKONINGCOMMANDWRITER = "LocalDeadReckoningCommandPublisher::LocalDeadReckoningCommandWriter";
const string GLOBALDEADRECKONINGCOMMANDWRITER = "GlobalDeadReckoningCommandPublisher::GlobalDeadReckoningCommandWriter";


//Readers
const string ACCELLERATIONREPORTREADER = "AccellerationReportSubscriber::AccellerationReportReader";
const string COMPARTMENTCONFIGREPORTREADER = "CompartmentConfigReportSubscriber::CompartmentConfigReportReader";
const string COMPARTMENTCONFIGREADER = "CompartmentConfigSubscriber::CompartmentConfigReader";
const string CONTACTCOLREGSCLASSIFICATIONSTATUSREPORTREADER = "ContactCOLREGSClassificationStatusReportSubscriber::ContactCOLREGSClassificationStatusReportReader";
const string CONTACTREMOVEDREPORTREADER = "ContactRemovedReportSubscriber::ContactRemovedReportReader";
const string CONTACTREPORTREADER = "ContactReportSubscriber::ContactReportReader";
const string CONTACTREPORT_CONTACTSSETREADER = "ContactReport_ContactsSetSubscriber::ContactReport_ContactsSetReader";
const string CONTACTVISUALCLASSIFICATIONSTATUSREPORTREADER = "ContactVisualClassificationStatusReportSubscriber::ContactVisualClassificationStatusReportReader";
const string CTDREPORTREADER = "CTDReportSubscriber::CTDReportReader";
const string DATETIMEREPORTREADER = "DateTimeReportSubscriber::DateTimeReportReader";
const string ECEFPOSEREPORTREADER = "ECEFPoseReportSubscriber::ECEFPoseReportReader";
const string FEATUREIMAGEREMOVEDREPORTREADER = "FeatureImageRemovedReportSubscriber::FeatureImageRemovedReportReader";
const string FEATUREIMAGEREPORTREADER = "FeatureImageReportSubscriber::FeatureImageReportReader";
const string GLOBALDEADRECKONINGCOMMANDREPORTREADER = "GlobalDeadReckoningCommandReportSubscriber::GlobalDeadReckoningCommandReportReader";
const string GLOBALDEADRECKONINGCOMMANDSTATUSREADER = "GlobalDeadReckoningCommandStatusSubscriber::GlobalDeadReckoningCommandStatusReader";
const string GLOBALPOSECONFIGREPORTREADER = "GlobalPoseConfigReportSubscriber::GlobalPoseConfigReportReader";
const string GLOBALPOSEREPORTREADER = "GlobalPoseReportSubscriber::GlobalPoseReportReader";
const string IMAGEREMOVEDREPORTREADER = "ImageRemovedReportSubscriber::ImageRemovedReportReader";
const string IMAGEREPORTREADER = "ImageReportSubscriber::ImageReportReader";
const string LOCALDEADRECKONINGCOMMANDREPORTREADER = "LocalDeadReckoningCommandReportSubscriber::LocalDeadReckoningCommandReportReader";
const string LOCALDEADRECKONINGCOMMANDSTATUSREADER = "LocalDeadReckoningCommandStatusSubscriber::LocalDeadReckoningCommandStatusReader";
const string LOCALPOSEREPORTREADER = "LocalPoseReportSubscriber::LocalPoseReportReader";
const string NEDVELOCITYREPORTREADER = "NEDVelocityReportSubscriber::NEDVelocityReportReader";
const string PATHREPORTERSPECSREPORTREADER = "PathReporterSpecsReportSubscriber::PathReporterSpecsReportReader";
const string PATHREPORTERREPORTREADER = "PathReporterReportSubscriber::PathReporterReportReader";
const string RANGECONFIGREPORTREADER = "RangeConfigReportSubscriber::RangeConfigReportReader";
const string RANGESPECSREPORTREADER = "RangeSpecsReportSubscriber::RangeSpecsReportReader";
const string RANGEREPORTREADER = "RangeReportSubscriber::RangeReportReader";
const string SEASTATUSREPORTREADER = "SeaStatusReportSubscriber::SeaStatusReportReader";
const string SPEEDREPORTREADER = "SpeedReportSubscriber::SpeedReportReader";
const string STILLIMAGECONFIGREPORTREADER = "StillImageConfigReportSubscriber::StillImageConfigReportReader";
const string STILLIMAGESPECSREPORTREADER = "StillImageSpecsReportSubscriber::StillImageSpecsReportReader";
const string STILLIMAGEREPORTREADER = "Subscriber::StillImageReportReader";
const string TRANSLATIONALSHIPMOTIONREPORTREADER = "TranslationalShipMotionReportSubscriber::TranslationalShipMotionReportReader";
const string VEHICLENAVIGATIONMODEREPORTREADER = "VehicleNavigationModeReportSubscriber::VehicleNavigationModeReportReader";
const string VELOCITYREPORTREADER = "VelocityReportSubscriber::VelocityReportReader";
const string WATERCURRENTSTATUSREPORTREADER = "WaterCurrentStatusReportSubscriber::WaterCurrentStatusReportReader";
const string WATERSPACEREPORTREADER = "WaterspaceReportSubscriber::WaterspaceReportReader";
const string WEATHERSTATUSREPORTREADER = "WeatherStatusReportSubscriber::WeatherStatusReportReader";
const string WINDSTATUSREPORTREADER = "WindStatusReportSubscriber::WindStatusReportReader";
const string LOCALDEADRECKONINGCOMMANDREADER = "Subscriber::LocalDeadReckoningCommandReader";
const string GLOBALDEADRECKONINGCOMMANDREADER = "Subscriber::GlobalDeadReckoningCommandReader";

// Types
const string ACCELERATIONREPORTTYPE = "UMAA::SA::AccelerationStatus::AccelerationReportType";
const string COMPARTMENTCONFIGREPORTTYPE = "UMAA::SA::CompartmentConfig::CompartmentConfigReportType";
const string COMPARTMENTREPORTTYPE = "UMAA::SA::CompartmentStatus::CompartmentReportType";
const string CONTACTCOLREGSCLASSIFICATIONSTATUSREPORTTYPE = "UMAA::SA::ContactCOLREGSClassificationStatus::ContactCOLREGSClassificationStatusReportType";
const string CONTACTREMOVEDREPORTTYPE = "UMAA::SA::ContactStatus::ContactRemovedReportType";
const string CONTACTREPORTTYPE = "UMAA::SA::ContactStatus::ContactReportType";
const string CONTACTREPORTTYPE_CONTACTSSET = "UMAA::SA::ContactStatus::ContactReportType_ContactsSet";
const string CONTACTVISUALCLASSIFICATIONSTATUSREPORTTYPE = "UMAA::SA::ContactVisualClassificationStatus::ContactVisualClassificationStatusReportType";
const string CTDREPORTTYPE = "UMAA::SA::CTDStatus::CTDReportType";
const string DATETIMEREPORTTYPE = "UMAA::SA::DateTimeStatus::DateTimeReportType";
const string ECEFPOSEREPORTTYPE = "UMAA::SA::ECEFPoseStatus::ECEFPoseReportType";
const string FEATUREIMAGEREMOVEDREPORTTYPE = "UMAA::SA::FeatureImageStatus::FeatureImageRemovedReportType";
const string FEATUREIMAGEREPORTTYPE = "UMAA::SA::FeatureImageStatus::FeatureImageReportType";
const string GLOBALDEADRECKONINGCOMMANDREPORTTYPE = "UMAA::SA::GlobalDeadReckoning::GlobalDeadReckoningCommandReportType";
const string GLOBALDEADRECKONINGCOMMANDSTATUSTYPE = "UMAA::SA::GlobalDeadReckoning::GlobalDeadReckoningCommandStatusType";
const string GLOBALDEADRECKONINGCOMMANDTYPE = "UMAA::SA::GlobalDeadReckoning::GlobalDeadReckoningCommandType";
const string GLOBALPOSECONFIGREPORTTYPE = "UMAA::SA::GlobalPoseConfig::GlobalPoseConfigReportType";
const string GLOBALPOSEREPORTTYPE = "UMAA::SA::GlobalPoseStatus::GlobalPoseReportType";
const string IMAGEREMOVEDREPORTTYPE = "UMAA::SA::FeatureImageStatus::FeatureImageRemovedReportType";
const string IMAGEREPORTTYPE = "UMAA::SA::ImageStatus::ImageReportType";
const string LOCALDEADRECKONINGCOMMANDREPORTTYPE = "UMAA::SA::LocalDeadReckoning::LocalDeadReckoningCommandReportType";
const string LOCALDEADRECKONINGCOMMANDSTATUSTYPE = "UMAA::SA::LocalDeadReckoning::LocalDeadReckoningCommandStatusType";
const string LOCALDEADRECKONINGCOMMANDTYPE = "UMAA::SA::LocalDeadReckoning::LocalDeadReckoningCommandType";
const string LOCALPOSEREPORTTYPE = "UMAA::SA::LocalPoseStatus::LocalPoseReportType";
const string NEDVELOCITYREPORTTYPE = "UMAA::SA::NEDVelocityStatus::NEDVelocityReportType";
const string PATHREPORTERSPECSREPORTTYPE = "UMAA::SA::PathReporterSpecs::PathReporterSpecsReportType";
const string PATHREPORTERREPORTTYPE = "UMAA::SA::PathReporterStatus::PathReporterReportType";
const string RANGECONFIGREPORTTYPE = "UMAA::SA::RangeConfig::RangeConfigReportType";
const string RANGESPECSREPORTTYPE = "UMAA::SA::RangeSpecs::RangeSpecsReportType";
const string RANGEREPORTTYPE = "UMAA::SA::RangeStatus::RangeReportType";
const string SEASTATUSREPORTTYPE = "UMAA::SA::SeaStatus::SeaStatusReportType";
const string SPEEDREPORTTYPE = "UMAA::SA::SpeedStatus::SpeedReportType";
const string STILLIMAGECONFIGREPORTTYPE = "UMAA::SA::StillImageConfig::StillImageConfigReportType";
const string STILLIMAGESPECSREPORTTYPE = "UMAA::SA::StillImageSpecs::StillImageSpecsReportType";
const string STILLIMAGEREPORTTYPE = "UMAA::SA::StillImageStatus::StillImageReportType";
const string TRANSLATIONALSHIPMOTIONREPORTTYPE = "UMAA::SA::TranslationalShipMotionStatus::TranslationalShipMotionReportType";
const string VEHICLENAVIGATIONMODEREPORTTYPE = "UMAA::SA::VehicleNavigationModeStatus::VehicleNavigationModeReportType";
const string VELOCITYREPORTTYPE = "UMAA::SA::VelocityStatus::VelocityReportType";
const string WATERCURRENTSTATUSREPORTTYPE = "UMAA::SA::WaterCurrentStatus::WaterCurrentStatusReportType";
const string WATERSPACEREPORTTYPE = "UMAA::SA::WaterspaceStatus::WaterspaceReportType";
const string WEATHERSTATUSREPORTTYPE = "UMAA::SA::WeatherStatus::WeatherStatusReportType";
const string WINDSTATUSREPORTTYPE = "UMAA::SA::WindStatus::WindStatusReportType";