// Auto-generated by cpp/sdk/tools/generate_services.py — DO NOT EDIT
#ifndef UMAA_SDK_SERVICES_HPP
#define UMAA_SDK_SERVICES_HPP

#include "umaa/sdk/services/co.hpp"
#include "umaa/sdk/services/eo.hpp"
#include "umaa/sdk/services/mm.hpp"
#include "umaa/sdk/services/mo.hpp"
#include "umaa/sdk/services/sa.hpp"
#include "umaa/sdk/services/sem.hpp"
#include "umaa/sdk/services/so.hpp"

#endif // UMAA_SDK_SERVICES_HPP
