// Auto-generated by cpp/sdk/tools/generate_services.py — DO NOT EDIT
#ifndef UMAA_SDK_SERVICES_CO_HPP
#define UMAA_SDK_SERVICES_CO_HPP

#include "umaa/sdk/command_provider.hpp"
#include "umaa/sdk/command_consumer.hpp"
#include "umaa/sdk/report_provider.hpp"
#include "umaa/sdk/report_consumer.hpp"

#include "UMAA/CO/CommsChannelConfig/CommsChannelAddMessageConfigCommandType.hpp"
#include "UMAA/CO/CommsChannelConfig/CommsChannelAddMessageConfigAckReportType.hpp"
#include "UMAA/CO/CommsChannelConfig/CommsChannelAddMessageConfigCommandStatusType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelClearAllCommandType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelClearAllCommandAckReportType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelClearAllCommandStatusType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelClearMessageCommandType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelClearMessageCommandAckReportType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelClearMessageCommandStatusType.hpp"
#include "UMAA/CO/CommsChannelConfig/CommsChannelDeleteMessageConfigCommandType.hpp"
#include "UMAA/CO/CommsChannelConfig/CommsChannelDeleteMessageConfigAckReportType.hpp"
#include "UMAA/CO/CommsChannelConfig/CommsChannelDeleteMessageConfigCommandStatusType.hpp"
#include "UMAA/CO/CommsChannelPowerConfig/CommsChannelPowerConfigCommandType.hpp"
#include "UMAA/CO/CommsChannelPowerConfig/CommsChannelPowerConfigAckReportType.hpp"
#include "UMAA/CO/CommsChannelPowerConfig/CommsChannelPowerConfigCommandStatusType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelResetCommandType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelResetCommandAckReportType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelResetCommandStatusType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelShutdownCommandType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelShutdownCommandAckReportType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelShutdownCommandStatusType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelStartupCommandType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelStartupCommandAckReportType.hpp"
#include "UMAA/CO/CommsChannelControl/CommsChannelStartupCommandStatusType.hpp"
#include "UMAA/CO/MessageFilterConfig/MessageFilterConfigCommandType.hpp"
#include "UMAA/CO/MessageFilterConfig/MessageFilterConfigAckReportType.hpp"
#include "UMAA/CO/MessageFilterConfig/MessageFilterConfigCommandStatusType.hpp"
#include "UMAA/CO/CommsChannelStatus/CommsChannelReportType.hpp"
#include "UMAA/CO/CommsChannelConfig/CommsChannelConfigReportType.hpp"
#include "UMAA/CO/CommsChannelDataEncodingReport/CommsChannelDataEncodingReportType.hpp"
#include "UMAA/CO/CommsChannelEnvironmentReport/CommsChannelEnvironmentReportType.hpp"
#include "UMAA/CO/CommsChannelPowerReport/CommsChannelPowerReportType.hpp"
#include "UMAA/CO/CommsChannelPowerConfig/CommsChannelPowerConfigReportType.hpp"
#include "UMAA/CO/CommsChannelStatus/CommsChannelReceiverReportType.hpp"
#include "UMAA/CO/CommsChannelStatus/CommsChannelReceiverStatisticsReportType.hpp"
#include "UMAA/CO/CommsChannelStatus/CommsChannelSenderReportType.hpp"
#include "UMAA/CO/CommsChannelStatus/CommsChannelSenderStatisticsReportType.hpp"
#include "UMAA/CO/CommsChannelSpecs/CommsChannelSpecsReportType.hpp"
#include "UMAA/CO/CommsChannelSystemTimeReport/CommsChannelSystemTimeReportType.hpp"

namespace umaa::sdk::services::co {

using CommsChannelAddMessageConfigProvider = umaa::sdk::CommandProvider<
    UMAA::CO::CommsChannelConfig::CommsChannelAddMessageConfigCommandType,
    UMAA::CO::CommsChannelConfig::CommsChannelAddMessageConfigAckReportType,
    UMAA::CO::CommsChannelConfig::CommsChannelAddMessageConfigCommandStatusType>;

using CommsChannelAddMessageConfigConsumer = umaa::sdk::CommandConsumer<
    UMAA::CO::CommsChannelConfig::CommsChannelAddMessageConfigCommandType,
    UMAA::CO::CommsChannelConfig::CommsChannelAddMessageConfigAckReportType,
    UMAA::CO::CommsChannelConfig::CommsChannelAddMessageConfigCommandStatusType>;

using CommsChannelClearAllControlProvider = umaa::sdk::CommandProvider<
    UMAA::CO::CommsChannelControl::CommsChannelClearAllCommandType,
    UMAA::CO::CommsChannelControl::CommsChannelClearAllCommandAckReportType,
    UMAA::CO::CommsChannelControl::CommsChannelClearAllCommandStatusType>;

using CommsChannelClearAllControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::CO::CommsChannelControl::CommsChannelClearAllCommandType,
    UMAA::CO::CommsChannelControl::CommsChannelClearAllCommandAckReportType,
    UMAA::CO::CommsChannelControl::CommsChannelClearAllCommandStatusType>;

using CommsChannelClearMessageControlProvider = umaa::sdk::CommandProvider<
    UMAA::CO::CommsChannelControl::CommsChannelClearMessageCommandType,
    UMAA::CO::CommsChannelControl::CommsChannelClearMessageCommandAckReportType,
    UMAA::CO::CommsChannelControl::CommsChannelClearMessageCommandStatusType>;

using CommsChannelClearMessageControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::CO::CommsChannelControl::CommsChannelClearMessageCommandType,
    UMAA::CO::CommsChannelControl::CommsChannelClearMessageCommandAckReportType,
    UMAA::CO::CommsChannelControl::CommsChannelClearMessageCommandStatusType>;

using CommsChannelDeleteMessageConfigProvider = umaa::sdk::CommandProvider<
    UMAA::CO::CommsChannelConfig::CommsChannelDeleteMessageConfigCommandType,
    UMAA::CO::CommsChannelConfig::CommsChannelDeleteMessageConfigAckReportType,
    UMAA::CO::CommsChannelConfig::CommsChannelDeleteMessageConfigCommandStatusType>;

using CommsChannelDeleteMessageConfigConsumer = umaa::sdk::CommandConsumer<
    UMAA::CO::CommsChannelConfig::CommsChannelDeleteMessageConfigCommandType,
    UMAA::CO::CommsChannelConfig::CommsChannelDeleteMessageConfigAckReportType,
    UMAA::CO::CommsChannelConfig::CommsChannelDeleteMessageConfigCommandStatusType>;

using CommsChannelPowerConfigProvider = umaa::sdk::CommandProvider<
    UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigCommandType,
    UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigAckReportType,
    UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigCommandStatusType>;

using CommsChannelPowerConfigConsumer = umaa::sdk::CommandConsumer<
    UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigCommandType,
    UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigAckReportType,
    UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigCommandStatusType>;

using CommsChannelResetControlProvider = umaa::sdk::CommandProvider<
    UMAA::CO::CommsChannelControl::CommsChannelResetCommandType,
    UMAA::CO::CommsChannelControl::CommsChannelResetCommandAckReportType,
    UMAA::CO::CommsChannelControl::CommsChannelResetCommandStatusType>;

using CommsChannelResetControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::CO::CommsChannelControl::CommsChannelResetCommandType,
    UMAA::CO::CommsChannelControl::CommsChannelResetCommandAckReportType,
    UMAA::CO::CommsChannelControl::CommsChannelResetCommandStatusType>;

using CommsChannelShutdownControlProvider = umaa::sdk::CommandProvider<
    UMAA::CO::CommsChannelControl::CommsChannelShutdownCommandType,
    UMAA::CO::CommsChannelControl::CommsChannelShutdownCommandAckReportType,
    UMAA::CO::CommsChannelControl::CommsChannelShutdownCommandStatusType>;

using CommsChannelShutdownControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::CO::CommsChannelControl::CommsChannelShutdownCommandType,
    UMAA::CO::CommsChannelControl::CommsChannelShutdownCommandAckReportType,
    UMAA::CO::CommsChannelControl::CommsChannelShutdownCommandStatusType>;

using CommsChannelStartupControlProvider = umaa::sdk::CommandProvider<
    UMAA::CO::CommsChannelControl::CommsChannelStartupCommandType,
    UMAA::CO::CommsChannelControl::CommsChannelStartupCommandAckReportType,
    UMAA::CO::CommsChannelControl::CommsChannelStartupCommandStatusType>;

using CommsChannelStartupControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::CO::CommsChannelControl::CommsChannelStartupCommandType,
    UMAA::CO::CommsChannelControl::CommsChannelStartupCommandAckReportType,
    UMAA::CO::CommsChannelControl::CommsChannelStartupCommandStatusType>;

using MessageFilterConfigProvider = umaa::sdk::CommandProvider<
    UMAA::CO::MessageFilterConfig::MessageFilterConfigCommandType,
    UMAA::CO::MessageFilterConfig::MessageFilterConfigAckReportType,
    UMAA::CO::MessageFilterConfig::MessageFilterConfigCommandStatusType>;

using MessageFilterConfigConsumer = umaa::sdk::CommandConsumer<
    UMAA::CO::MessageFilterConfig::MessageFilterConfigCommandType,
    UMAA::CO::MessageFilterConfig::MessageFilterConfigAckReportType,
    UMAA::CO::MessageFilterConfig::MessageFilterConfigCommandStatusType>;

using CommsChannelReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelStatus::CommsChannelReportType>;
using CommsChannelReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelStatus::CommsChannelReportType>;

using CommsChannelConfigReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelConfig::CommsChannelConfigReportType>;
using CommsChannelConfigReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelConfig::CommsChannelConfigReportType>;

using CommsChannelDataEncodingReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelDataEncodingReport::CommsChannelDataEncodingReportType>;
using CommsChannelDataEncodingReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelDataEncodingReport::CommsChannelDataEncodingReportType>;

using CommsChannelEnvironmentReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelEnvironmentReport::CommsChannelEnvironmentReportType>;
using CommsChannelEnvironmentReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelEnvironmentReport::CommsChannelEnvironmentReportType>;

using CommsChannelPowerReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelPowerReport::CommsChannelPowerReportType>;
using CommsChannelPowerReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelPowerReport::CommsChannelPowerReportType>;

using CommsChannelPowerConfigReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigReportType>;
using CommsChannelPowerConfigReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigReportType>;

using CommsChannelReceiverReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelStatus::CommsChannelReceiverReportType>;
using CommsChannelReceiverReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelStatus::CommsChannelReceiverReportType>;

using CommsChannelReceiverStatisticsReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelStatus::CommsChannelReceiverStatisticsReportType>;
using CommsChannelReceiverStatisticsReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelStatus::CommsChannelReceiverStatisticsReportType>;

using CommsChannelSenderReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelStatus::CommsChannelSenderReportType>;
using CommsChannelSenderReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelStatus::CommsChannelSenderReportType>;

using CommsChannelSenderStatisticsReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelStatus::CommsChannelSenderStatisticsReportType>;
using CommsChannelSenderStatisticsReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelStatus::CommsChannelSenderStatisticsReportType>;

using CommsChannelSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelSpecs::CommsChannelSpecsReportType>;
using CommsChannelSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelSpecs::CommsChannelSpecsReportType>;

using CommsChannelSystemTimeReportProvider = umaa::sdk::ReportProvider<UMAA::CO::CommsChannelSystemTimeReport::CommsChannelSystemTimeReportType>;
using CommsChannelSystemTimeReportConsumer = umaa::sdk::ReportConsumer<UMAA::CO::CommsChannelSystemTimeReport::CommsChannelSystemTimeReportType>;

} // namespace umaa::sdk::services::co

namespace umaa::sdk::topics::co {

inline constexpr const char* CommsChannelAddMessageConfigCommandTopic = "UMAA::CO::CommsChannelConfig::CommsChannelAddMessageConfigCommandType";
inline constexpr const char* CommsChannelAddMessageConfigAckTopic = "UMAA::CO::CommsChannelConfig::CommsChannelAddMessageConfigAckReportType";
inline constexpr const char* CommsChannelAddMessageConfigCommandStatusTopic = "UMAA::CO::CommsChannelConfig::CommsChannelAddMessageConfigCommandStatusType";

inline constexpr const char* CommsChannelClearAllCommandTopic = "UMAA::CO::CommsChannelControl::CommsChannelClearAllCommandType";
inline constexpr const char* CommsChannelClearAllCommandAckTopic = "UMAA::CO::CommsChannelControl::CommsChannelClearAllCommandAckReportType";
inline constexpr const char* CommsChannelClearAllCommandStatusTopic = "UMAA::CO::CommsChannelControl::CommsChannelClearAllCommandStatusType";

inline constexpr const char* CommsChannelClearMessageCommandTopic = "UMAA::CO::CommsChannelControl::CommsChannelClearMessageCommandType";
inline constexpr const char* CommsChannelClearMessageCommandAckTopic = "UMAA::CO::CommsChannelControl::CommsChannelClearMessageCommandAckReportType";
inline constexpr const char* CommsChannelClearMessageCommandStatusTopic = "UMAA::CO::CommsChannelControl::CommsChannelClearMessageCommandStatusType";

inline constexpr const char* CommsChannelDeleteMessageConfigCommandTopic = "UMAA::CO::CommsChannelConfig::CommsChannelDeleteMessageConfigCommandType";
inline constexpr const char* CommsChannelDeleteMessageConfigAckTopic = "UMAA::CO::CommsChannelConfig::CommsChannelDeleteMessageConfigAckReportType";
inline constexpr const char* CommsChannelDeleteMessageConfigCommandStatusTopic = "UMAA::CO::CommsChannelConfig::CommsChannelDeleteMessageConfigCommandStatusType";

inline constexpr const char* CommsChannelPowerConfigCommandTopic = "UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigCommandType";
inline constexpr const char* CommsChannelPowerConfigAckTopic = "UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigAckReportType";
inline constexpr const char* CommsChannelPowerConfigCommandStatusTopic = "UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigCommandStatusType";

inline constexpr const char* CommsChannelResetCommandTopic = "UMAA::CO::CommsChannelControl::CommsChannelResetCommandType";
inline constexpr const char* CommsChannelResetCommandAckTopic = "UMAA::CO::CommsChannelControl::CommsChannelResetCommandAckReportType";
inline constexpr const char* CommsChannelResetCommandStatusTopic = "UMAA::CO::CommsChannelControl::CommsChannelResetCommandStatusType";

inline constexpr const char* CommsChannelShutdownCommandTopic = "UMAA::CO::CommsChannelControl::CommsChannelShutdownCommandType";
inline constexpr const char* CommsChannelShutdownCommandAckTopic = "UMAA::CO::CommsChannelControl::CommsChannelShutdownCommandAckReportType";
inline constexpr const char* CommsChannelShutdownCommandStatusTopic = "UMAA::CO::CommsChannelControl::CommsChannelShutdownCommandStatusType";

inline constexpr const char* CommsChannelStartupCommandTopic = "UMAA::CO::CommsChannelControl::CommsChannelStartupCommandType";
inline constexpr const char* CommsChannelStartupCommandAckTopic = "UMAA::CO::CommsChannelControl::CommsChannelStartupCommandAckReportType";
inline constexpr const char* CommsChannelStartupCommandStatusTopic = "UMAA::CO::CommsChannelControl::CommsChannelStartupCommandStatusType";

inline constexpr const char* MessageFilterConfigCommandTopic = "UMAA::CO::MessageFilterConfig::MessageFilterConfigCommandType";
inline constexpr const char* MessageFilterConfigAckTopic = "UMAA::CO::MessageFilterConfig::MessageFilterConfigAckReportType";
inline constexpr const char* MessageFilterConfigCommandStatusTopic = "UMAA::CO::MessageFilterConfig::MessageFilterConfigCommandStatusType";

inline constexpr const char* CommsChannelReportTopic = "UMAA::CO::CommsChannelStatus::CommsChannelReportType";
inline constexpr const char* CommsChannelConfigReportTopic = "UMAA::CO::CommsChannelConfig::CommsChannelConfigReportType";
inline constexpr const char* CommsChannelDataEncodingReportTopic = "UMAA::CO::CommsChannelDataEncodingReport::CommsChannelDataEncodingReportType";
inline constexpr const char* CommsChannelEnvironmentReportTopic = "UMAA::CO::CommsChannelEnvironmentReport::CommsChannelEnvironmentReportType";
inline constexpr const char* CommsChannelPowerReportTopic = "UMAA::CO::CommsChannelPowerReport::CommsChannelPowerReportType";
inline constexpr const char* CommsChannelPowerConfigReportTopic = "UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigReportType";
inline constexpr const char* CommsChannelReceiverReportTopic = "UMAA::CO::CommsChannelStatus::CommsChannelReceiverReportType";
inline constexpr const char* CommsChannelReceiverStatisticsReportTopic = "UMAA::CO::CommsChannelStatus::CommsChannelReceiverStatisticsReportType";
inline constexpr const char* CommsChannelSenderReportTopic = "UMAA::CO::CommsChannelStatus::CommsChannelSenderReportType";
inline constexpr const char* CommsChannelSenderStatisticsReportTopic = "UMAA::CO::CommsChannelStatus::CommsChannelSenderStatisticsReportType";
inline constexpr const char* CommsChannelSpecsReportTopic = "UMAA::CO::CommsChannelSpecs::CommsChannelSpecsReportType";
inline constexpr const char* CommsChannelSystemTimeReportTopic = "UMAA::CO::CommsChannelSystemTimeReport::CommsChannelSystemTimeReportType";

} // namespace umaa::sdk::topics::co

#endif // UMAA_SDK_SERVICES_CO_HPP
