// Auto-generated by cpp/sdk/tools/generate_services.py — DO NOT EDIT
#ifndef UMAA_SDK_SERVICES_EO_HPP
#define UMAA_SDK_SERVICES_EO_HPP

#include "umaa/sdk/command_provider.hpp"
#include "umaa/sdk/command_consumer.hpp"
#include "umaa/sdk/report_provider.hpp"
#include "umaa/sdk/report_consumer.hpp"

#include "UMAA/EO/AnchorControl/AnchorCommandType.hpp"
#include "UMAA/EO/AnchorControl/AnchorCommandAckReportType.hpp"
#include "UMAA/EO/AnchorControl/AnchorCommandStatusType.hpp"
#include "UMAA/EO/BallastTank/BallastPumpCommandType.hpp"
#include "UMAA/EO/BallastTank/BallastPumpCommandAckReportType.hpp"
#include "UMAA/EO/BallastTank/BallastPumpCommandStatusType.hpp"
#include "UMAA/EO/BallastTank/BallastTankCommandType.hpp"
#include "UMAA/EO/BallastTank/BallastTankCommandAckReportType.hpp"
#include "UMAA/EO/BallastTank/BallastTankCommandStatusType.hpp"
#include "UMAA/EO/EngineControl/EngineCommandType.hpp"
#include "UMAA/EO/EngineControl/EngineCommandAckReportType.hpp"
#include "UMAA/EO/EngineControl/EngineCommandStatusType.hpp"
#include "UMAA/EO/FinsControl/FinsCommandType.hpp"
#include "UMAA/EO/FinsControl/FinsCommandAckReportType.hpp"
#include "UMAA/EO/FinsControl/FinsCommandStatusType.hpp"
#include "UMAA/EO/MastControl/MastCommandType.hpp"
#include "UMAA/EO/MastControl/MastCommandAckReportType.hpp"
#include "UMAA/EO/MastControl/MastCommandStatusType.hpp"
#include "UMAA/EO/PowerControl/PowerCommandType.hpp"
#include "UMAA/EO/PowerControl/PowerCommandAckReportType.hpp"
#include "UMAA/EO/PowerControl/PowerCommandStatusType.hpp"
#include "UMAA/EO/PropulsorsControl/PropulsorsCommandType.hpp"
#include "UMAA/EO/PropulsorsControl/PropulsorsCommandAckReportType.hpp"
#include "UMAA/EO/PropulsorsControl/PropulsorsCommandStatusType.hpp"
#include "UMAA/EO/AnchorStatus/AnchorReportType.hpp"
#include "UMAA/EO/AnchorSpecs/AnchorSpecsReportType.hpp"
#include "UMAA/EO/BallastTank/BallastPumpReportType.hpp"
#include "UMAA/EO/BallastTank/BallastPumpSpecsReportType.hpp"
#include "UMAA/EO/BallastTank/BallastTankReportType.hpp"
#include "UMAA/EO/BallastTank/BallastTankSpecsReportType.hpp"
#include "UMAA/EO/BatteryStatus/BatteryReportType.hpp"
#include "UMAA/EO/BatterySpecs/BatterySpecsReportType.hpp"
#include "UMAA/EO/BilgePumpStatus/BilgePumpReportType.hpp"
#include "UMAA/EO/EngineStatus/EngineReportType.hpp"
#include "UMAA/EO/EngineSpecs/EngineSpecsReportType.hpp"
#include "UMAA/EO/FinsSpecs/FinsSpecsReportType.hpp"
#include "UMAA/EO/FuelTankStatus/FuelTankReportType.hpp"
#include "UMAA/EO/FuelTankSpecs/FuelTankSpecsReportType.hpp"
#include "UMAA/EO/GeneratorStatus/GeneratorReportType.hpp"
#include "UMAA/EO/GeneratorSpecs/GeneratorSpecsReportType.hpp"
#include "UMAA/EO/MastStatus/MastReportType.hpp"
#include "UMAA/EO/PowerStatus/PowerReportType.hpp"
#include "UMAA/EO/PropulsorsSpecs/PropulsorsSpecsReportType.hpp"
#include "UMAA/EO/UVPlatformSpecs/UVPlatformCapabilitiesReportType.hpp"
#include "UMAA/EO/UVPlatformSpecs/UVPlatformSpecsReportType.hpp"

namespace umaa::sdk::services::eo {

using AnchorControlProvider = umaa::sdk::CommandProvider<
    UMAA::EO::AnchorControl::AnchorCommandType,
    UMAA::EO::AnchorControl::AnchorCommandAckReportType,
    UMAA::EO::AnchorControl::AnchorCommandStatusType>;

using AnchorControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::EO::AnchorControl::AnchorCommandType,
    UMAA::EO::AnchorControl::AnchorCommandAckReportType,
    UMAA::EO::AnchorControl::AnchorCommandStatusType>;

using BallastPumpControlProvider = umaa::sdk::CommandProvider<
    UMAA::EO::BallastTank::BallastPumpCommandType,
    UMAA::EO::BallastTank::BallastPumpCommandAckReportType,
    UMAA::EO::BallastTank::BallastPumpCommandStatusType>;

using BallastPumpControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::EO::BallastTank::BallastPumpCommandType,
    UMAA::EO::BallastTank::BallastPumpCommandAckReportType,
    UMAA::EO::BallastTank::BallastPumpCommandStatusType>;

using BallastTankControlProvider = umaa::sdk::CommandProvider<
    UMAA::EO::BallastTank::BallastTankCommandType,
    UMAA::EO::BallastTank::BallastTankCommandAckReportType,
    UMAA::EO::BallastTank::BallastTankCommandStatusType>;

using BallastTankControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::EO::BallastTank::BallastTankCommandType,
    UMAA::EO::BallastTank::BallastTankCommandAckReportType,
    UMAA::EO::BallastTank::BallastTankCommandStatusType>;

using EngineControlProvider = umaa::sdk::CommandProvider<
    UMAA::EO::EngineControl::EngineCommandType,
    UMAA::EO::EngineControl::EngineCommandAckReportType,
    UMAA::EO::EngineControl::EngineCommandStatusType>;

using EngineControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::EO::EngineControl::EngineCommandType,
    UMAA::EO::EngineControl::EngineCommandAckReportType,
    UMAA::EO::EngineControl::EngineCommandStatusType>;

using FinsControlProvider = umaa::sdk::CommandProvider<
    UMAA::EO::FinsControl::FinsCommandType,
    UMAA::EO::FinsControl::FinsCommandAckReportType,
    UMAA::EO::FinsControl::FinsCommandStatusType>;

using FinsControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::EO::FinsControl::FinsCommandType,
    UMAA::EO::FinsControl::FinsCommandAckReportType,
    UMAA::EO::FinsControl::FinsCommandStatusType>;

using MastControlProvider = umaa::sdk::CommandProvider<
    UMAA::EO::MastControl::MastCommandType,
    UMAA::EO::MastControl::MastCommandAckReportType,
    UMAA::EO::MastControl::MastCommandStatusType>;

using MastControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::EO::MastControl::MastCommandType,
    UMAA::EO::MastControl::MastCommandAckReportType,
    UMAA::EO::MastControl::MastCommandStatusType>;

using PowerControlProvider = umaa::sdk::CommandProvider<
    UMAA::EO::PowerControl::PowerCommandType,
    UMAA::EO::PowerControl::PowerCommandAckReportType,
    UMAA::EO::PowerControl::PowerCommandStatusType>;

using PowerControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::EO::PowerControl::PowerCommandType,
    UMAA::EO::PowerControl::PowerCommandAckReportType,
    UMAA::EO::PowerControl::PowerCommandStatusType>;

using PropulsorsControlProvider = umaa::sdk::CommandProvider<
    UMAA::EO::PropulsorsControl::PropulsorsCommandType,
    UMAA::EO::PropulsorsControl::PropulsorsCommandAckReportType,
    UMAA::EO::PropulsorsControl::PropulsorsCommandStatusType>;

using PropulsorsControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::EO::PropulsorsControl::PropulsorsCommandType,
    UMAA::EO::PropulsorsControl::PropulsorsCommandAckReportType,
    UMAA::EO::PropulsorsControl::PropulsorsCommandStatusType>;

using AnchorReportProvider = umaa::sdk::ReportProvider<UMAA::EO::AnchorStatus::AnchorReportType>;
using AnchorReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::AnchorStatus::AnchorReportType>;

using AnchorSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::EO::AnchorSpecs::AnchorSpecsReportType>;
using AnchorSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::AnchorSpecs::AnchorSpecsReportType>;

using BallastPumpReportProvider = umaa::sdk::ReportProvider<UMAA::EO::BallastTank::BallastPumpReportType>;
using BallastPumpReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::BallastTank::BallastPumpReportType>;

using BallastPumpSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::EO::BallastTank::BallastPumpSpecsReportType>;
using BallastPumpSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::BallastTank::BallastPumpSpecsReportType>;

using BallastTankReportProvider = umaa::sdk::ReportProvider<UMAA::EO::BallastTank::BallastTankReportType>;
using BallastTankReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::BallastTank::BallastTankReportType>;

using BallastTankSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::EO::BallastTank::BallastTankSpecsReportType>;
using BallastTankSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::BallastTank::BallastTankSpecsReportType>;

using BatteryReportProvider = umaa::sdk::ReportProvider<UMAA::EO::BatteryStatus::BatteryReportType>;
using BatteryReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::BatteryStatus::BatteryReportType>;

using BatterySpecsReportProvider = umaa::sdk::ReportProvider<UMAA::EO::BatterySpecs::BatterySpecsReportType>;
using BatterySpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::BatterySpecs::BatterySpecsReportType>;

using BilgePumpReportProvider = umaa::sdk::ReportProvider<UMAA::EO::BilgePumpStatus::BilgePumpReportType>;
using BilgePumpReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::BilgePumpStatus::BilgePumpReportType>;

using EngineReportProvider = umaa::sdk::ReportProvider<UMAA::EO::EngineStatus::EngineReportType>;
using EngineReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::EngineStatus::EngineReportType>;

using EngineSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::EO::EngineSpecs::EngineSpecsReportType>;
using EngineSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::EngineSpecs::EngineSpecsReportType>;

using FinsSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::EO::FinsSpecs::FinsSpecsReportType>;
using FinsSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::FinsSpecs::FinsSpecsReportType>;

using FuelTankReportProvider = umaa::sdk::ReportProvider<UMAA::EO::FuelTankStatus::FuelTankReportType>;
using FuelTankReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::FuelTankStatus::FuelTankReportType>;

using FuelTankSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::EO::FuelTankSpecs::FuelTankSpecsReportType>;
using FuelTankSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::FuelTankSpecs::FuelTankSpecsReportType>;

using GeneratorReportProvider = umaa::sdk::ReportProvider<UMAA::EO::GeneratorStatus::GeneratorReportType>;
using GeneratorReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::GeneratorStatus::GeneratorReportType>;

using GeneratorSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::EO::GeneratorSpecs::GeneratorSpecsReportType>;
using GeneratorSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::GeneratorSpecs::GeneratorSpecsReportType>;

using MastReportProvider = umaa::sdk::ReportProvider<UMAA::EO::MastStatus::MastReportType>;
using MastReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::MastStatus::MastReportType>;

using PowerReportProvider = umaa::sdk::ReportProvider<UMAA::EO::PowerStatus::PowerReportType>;
using PowerReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::PowerStatus::PowerReportType>;

using PropulsorsSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::EO::PropulsorsSpecs::PropulsorsSpecsReportType>;
using PropulsorsSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::PropulsorsSpecs::PropulsorsSpecsReportType>;

using UVPlatformCapabilitiesReportProvider = umaa::sdk::ReportProvider<UMAA::EO::UVPlatformSpecs::UVPlatformCapabilitiesReportType>;
using UVPlatformCapabilitiesReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::UVPlatformSpecs::UVPlatformCapabilitiesReportType>;

using UVPlatformSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::EO::UVPlatformSpecs::UVPlatformSpecsReportType>;
using UVPlatformSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::EO::UVPlatformSpecs::UVPlatformSpecsReportType>;

} // namespace umaa::sdk::services::eo

namespace umaa::sdk::topics::eo {

inline constexpr const char* AnchorCommandTopic = "UMAA::EO::AnchorControl::AnchorCommandType";
inline constexpr const char* AnchorCommandAckTopic = "UMAA::EO::AnchorControl::AnchorCommandAckReportType";
inline constexpr const char* AnchorCommandStatusTopic = "UMAA::EO::AnchorControl::AnchorCommandStatusType";

inline constexpr const char* BallastPumpCommandTopic = "UMAA::EO::BallastTank::BallastPumpCommandType";
inline constexpr const char* BallastPumpCommandAckTopic = "UMAA::EO::BallastTank::BallastPumpCommandAckReportType";
inline constexpr const char* BallastPumpCommandStatusTopic = "UMAA::EO::BallastTank::BallastPumpCommandStatusType";

inline constexpr const char* BallastTankCommandTopic = "UMAA::EO::BallastTank::BallastTankCommandType";
inline constexpr const char* BallastTankCommandAckTopic = "UMAA::EO::BallastTank::BallastTankCommandAckReportType";
inline constexpr const char* BallastTankCommandStatusTopic = "UMAA::EO::BallastTank::BallastTankCommandStatusType";

inline constexpr const char* EngineCommandTopic = "UMAA::EO::EngineControl::EngineCommandType";
inline constexpr const char* EngineCommandAckTopic = "UMAA::EO::EngineControl::EngineCommandAckReportType";
inline constexpr const char* EngineCommandStatusTopic = "UMAA::EO::EngineControl::EngineCommandStatusType";

inline constexpr const char* FinsCommandTopic = "UMAA::EO::FinsControl::FinsCommandType";
inline constexpr const char* FinsCommandAckTopic = "UMAA::EO::FinsControl::FinsCommandAckReportType";
inline constexpr const char* FinsCommandStatusTopic = "UMAA::EO::FinsControl::FinsCommandStatusType";

inline constexpr const char* MastCommandTopic = "UMAA::EO::MastControl::MastCommandType";
inline constexpr const char* MastCommandAckTopic = "UMAA::EO::MastControl::MastCommandAckReportType";
inline constexpr const char* MastCommandStatusTopic = "UMAA::EO::MastControl::MastCommandStatusType";

inline constexpr const char* PowerCommandTopic = "UMAA::EO::PowerControl::PowerCommandType";
inline constexpr const char* PowerCommandAckTopic = "UMAA::EO::PowerControl::PowerCommandAckReportType";
inline constexpr const char* PowerCommandStatusTopic = "UMAA::EO::PowerControl::PowerCommandStatusType";

inline constexpr const char* PropulsorsCommandTopic = "UMAA::EO::PropulsorsControl::PropulsorsCommandType";
inline constexpr const char* PropulsorsCommandAckTopic = "UMAA::EO::PropulsorsControl::PropulsorsCommandAckReportType";
inline constexpr const char* PropulsorsCommandStatusTopic = "UMAA::EO::PropulsorsControl::PropulsorsCommandStatusType";

inline constexpr const char* AnchorReportTopic = "UMAA::EO::AnchorStatus::AnchorReportType";
inline constexpr const char* AnchorSpecsReportTopic = "UMAA::EO::AnchorSpecs::AnchorSpecsReportType";
inline constexpr const char* BallastPumpReportTopic = "UMAA::EO::BallastTank::BallastPumpReportType";
inline constexpr const char* BallastPumpSpecsReportTopic = "UMAA::EO::BallastTank::BallastPumpSpecsReportType";
inline constexpr const char* BallastTankReportTopic = "UMAA::EO::BallastTank::BallastTankReportType";
inline constexpr const char* BallastTankSpecsReportTopic = "UMAA::EO::BallastTank::BallastTankSpecsReportType";
inline constexpr const char* BatteryReportTopic = "UMAA::EO::BatteryStatus::BatteryReportType";
inline constexpr const char* BatterySpecsReportTopic = "UMAA::EO::BatterySpecs::BatterySpecsReportType";
inline constexpr const char* BilgePumpReportTopic = "UMAA::EO::BilgePumpStatus::BilgePumpReportType";
inline constexpr const char* EngineReportTopic = "UMAA::EO::EngineStatus::EngineReportType";
inline constexpr const char* EngineSpecsReportTopic = "UMAA::EO::EngineSpecs::EngineSpecsReportType";
inline constexpr const char* FinsSpecsReportTopic = "UMAA::EO::FinsSpecs::FinsSpecsReportType";
inline constexpr const char* FuelTankReportTopic = "UMAA::EO::FuelTankStatus::FuelTankReportType";
inline constexpr const char* FuelTankSpecsReportTopic = "UMAA::EO::FuelTankSpecs::FuelTankSpecsReportType";
inline constexpr const char* GeneratorReportTopic = "UMAA::EO::GeneratorStatus::GeneratorReportType";
inline constexpr const char* GeneratorSpecsReportTopic = "UMAA::EO::GeneratorSpecs::GeneratorSpecsReportType";
inline constexpr const char* MastReportTopic = "UMAA::EO::MastStatus::MastReportType";
inline constexpr const char* PowerReportTopic = "UMAA::EO::PowerStatus::PowerReportType";
inline constexpr const char* PropulsorsSpecsReportTopic = "UMAA::EO::PropulsorsSpecs::PropulsorsSpecsReportType";
inline constexpr const char* UVPlatformCapabilitiesReportTopic = "UMAA::EO::UVPlatformSpecs::UVPlatformCapabilitiesReportType";
inline constexpr const char* UVPlatformSpecsReportTopic = "UMAA::EO::UVPlatformSpecs::UVPlatformSpecsReportType";

} // namespace umaa::sdk::topics::eo

#endif // UMAA_SDK_SERVICES_EO_HPP
