// Auto-generated by cpp/sdk/tools/generate_services.py — DO NOT EDIT
#ifndef UMAA_SDK_SERVICES_MM_HPP
#define UMAA_SDK_SERVICES_MM_HPP

#include "umaa/sdk/command_provider.hpp"
#include "umaa/sdk/command_consumer.hpp"
#include "umaa/sdk/report_provider.hpp"
#include "umaa/sdk/report_consumer.hpp"

#include "UMAA/MM/ActiveConstraintsControl/ActiveConstraintsCommandType.hpp"
#include "UMAA/MM/ActiveConstraintsControl/ActiveConstraintsCommandAckReportType.hpp"
#include "UMAA/MM/ActiveConstraintsControl/ActiveConstraintsCommandStatusType.hpp"
#include "UMAA/MM/ConditionalControl/ConditionalAddCommandType.hpp"
#include "UMAA/MM/ConditionalControl/ConditionalAddCommandAckReportType.hpp"
#include "UMAA/MM/ConditionalControl/ConditionalAddCommandStatusType.hpp"
#include "UMAA/MM/ConditionalControl/ConditionalDeleteCommandType.hpp"
#include "UMAA/MM/ConditionalControl/ConditionalDeleteCommandAckReportType.hpp"
#include "UMAA/MM/ConditionalControl/ConditionalDeleteCommandStatusType.hpp"
#include "UMAA/MM/MissionPlanAssignmentControl/MissionPlanAssignmentCommandType.hpp"
#include "UMAA/MM/MissionPlanAssignmentControl/MissionPlanAssignmentCommandAckReportType.hpp"
#include "UMAA/MM/MissionPlanAssignmentControl/MissionPlanAssignmentCommandStatusType.hpp"
#include "UMAA/MM/MissionPlanConstraintControl/MissionPlanConstraintAddCommandType.hpp"
#include "UMAA/MM/MissionPlanConstraintControl/MissionPlanConstraintAddCommandAckReportType.hpp"
#include "UMAA/MM/MissionPlanConstraintControl/MissionPlanConstraintAddCommandStatusType.hpp"
#include "UMAA/MM/MissionPlanConstraintControl/MissionPlanConstraintDeleteCommandType.hpp"
#include "UMAA/MM/MissionPlanConstraintControl/MissionPlanConstraintDeleteCommandAckReportType.hpp"
#include "UMAA/MM/MissionPlanConstraintControl/MissionPlanConstraintDeleteCommandStatusType.hpp"
#include "UMAA/MM/MissionPlanExecutionControl/MissionPlanExecutionCommandType.hpp"
#include "UMAA/MM/MissionPlanExecutionControl/MissionPlanExecutionCommandAckReportType.hpp"
#include "UMAA/MM/MissionPlanExecutionControl/MissionPlanExecutionCommandStatusType.hpp"
#include "UMAA/MM/MissionPlanMissionControl/MissionPlanMissionAddCommandType.hpp"
#include "UMAA/MM/MissionPlanMissionControl/MissionPlanMissionAddCommandAckReportType.hpp"
#include "UMAA/MM/MissionPlanMissionControl/MissionPlanMissionAddCommandStatusType.hpp"
#include "UMAA/MM/MissionPlanMissionControl/MissionPlanMissionClearCommandType.hpp"
#include "UMAA/MM/MissionPlanMissionControl/MissionPlanMissionClearCommandAckReportType.hpp"
#include "UMAA/MM/MissionPlanMissionControl/MissionPlanMissionClearCommandStatusType.hpp"
#include "UMAA/MM/MissionPlanMissionControl/MissionPlanMissionDeleteCommandType.hpp"
#include "UMAA/MM/MissionPlanMissionControl/MissionPlanMissionDeleteCommandAckReportType.hpp"
#include "UMAA/MM/MissionPlanMissionControl/MissionPlanMissionDeleteCommandStatusType.hpp"
#include "UMAA/MM/MissionPlanObjectiveControl/MissionPlanObjectiveAddCommandType.hpp"
#include "UMAA/MM/MissionPlanObjectiveControl/MissionPlanObjectiveAddCommandAckReportType.hpp"
#include "UMAA/MM/MissionPlanObjectiveControl/MissionPlanObjectiveAddCommandStatusType.hpp"
#include "UMAA/MM/MissionPlanObjectiveControl/MissionPlanObjectiveDeleteCommandType.hpp"
#include "UMAA/MM/MissionPlanObjectiveControl/MissionPlanObjectiveDeleteCommandAckReportType.hpp"
#include "UMAA/MM/MissionPlanObjectiveControl/MissionPlanObjectiveDeleteCommandStatusType.hpp"
#include "UMAA/MM/MissionPlanTaskControl/MissionPlanTaskAddCommandType.hpp"
#include "UMAA/MM/MissionPlanTaskControl/MissionPlanTaskAddCommandAckReportType.hpp"
#include "UMAA/MM/MissionPlanTaskControl/MissionPlanTaskAddCommandStatusType.hpp"
#include "UMAA/MM/MissionPlanTaskControl/MissionPlanTaskDeleteCommandType.hpp"
#include "UMAA/MM/MissionPlanTaskControl/MissionPlanTaskDeleteCommandAckReportType.hpp"
#include "UMAA/MM/MissionPlanTaskControl/MissionPlanTaskDeleteCommandStatusType.hpp"
#include "UMAA/MM/ObjectiveAssignmentControl/ObjectiveAssignmentCommandType.hpp"
#include "UMAA/MM/ObjectiveAssignmentControl/ObjectiveAssignmentCommandAckReportType.hpp"
#include "UMAA/MM/ObjectiveAssignmentControl/ObjectiveAssignmentCommandStatusType.hpp"
#include "UMAA/MM/ObjectiveExecutionControl/ObjectiveExecutionCommandType.hpp"
#include "UMAA/MM/ObjectiveExecutionControl/ObjectiveExecutionCommandAckReportType.hpp"
#include "UMAA/MM/ObjectiveExecutionControl/ObjectiveExecutionCommandStatusType.hpp"
#include "UMAA/MM/ObjectiveExecutorControl/ObjectiveExecutorCommandType.hpp"
#include "UMAA/MM/ObjectiveExecutorControl/ObjectiveExecutorCommandAckReportType.hpp"
#include "UMAA/MM/ObjectiveExecutorControl/ObjectiveExecutorCommandStatusType.hpp"
#include "UMAA/MM/ObjectiveExecutorControl/ObjectiveExecutorExecutionStatusReportType.hpp"
#include "UMAA/MM/ObjectiveExecutorControl/ObjectiveExecutorStateCommandType.hpp"
#include "UMAA/MM/ObjectiveExecutorControl/ObjectiveExecutorStateCommandAckReportType.hpp"
#include "UMAA/MM/ObjectiveExecutorControl/ObjectiveExecutorStateCommandStatusType.hpp"
#include "UMAA/MM/OperationalModeControl/OperationalModeCommandType.hpp"
#include "UMAA/MM/OperationalModeControl/OperationalModeCommandAckReportType.hpp"
#include "UMAA/MM/OperationalModeControl/OperationalModeCommandStatusType.hpp"
#include "UMAA/MM/TaskPlanAssignmentControl/TaskPlanAssignmentCommandType.hpp"
#include "UMAA/MM/TaskPlanAssignmentControl/TaskPlanAssignmentCommandAckReportType.hpp"
#include "UMAA/MM/TaskPlanAssignmentControl/TaskPlanAssignmentCommandStatusType.hpp"
#include "UMAA/MM/TaskPlanExecutionControl/TaskPlanExecutionCommandType.hpp"
#include "UMAA/MM/TaskPlanExecutionControl/TaskPlanExecutionCommandAckReportType.hpp"
#include "UMAA/MM/TaskPlanExecutionControl/TaskPlanExecutionCommandStatusType.hpp"
#include "UMAA/MM/ControlTransfer/ClientControlReportType.hpp"
#include "UMAA/MM/ControlTransfer/ClientControlTransferReportType.hpp"
#include "UMAA/MM/ConditionalReport/ConditionalReportType.hpp"
#include "UMAA/MM/ConditionalStateReport/ConditionalStateReportType.hpp"
#include "UMAA/MM/ControlTransfer/ControlSystemControlReportType.hpp"
#include "UMAA/MM/ControlTransfer/ControlSystemTransferReportType.hpp"
#include "UMAA/MM/MissionPlanReport/MissionPlanReportType.hpp"
#include "UMAA/MM/MissionPlanAssignmentReport/MissionPlanAssignmentReportType.hpp"
#include "UMAA/MM/MissionPlanExecutionStatus/MissionPlanExecutionReportType.hpp"
#include "UMAA/MM/ObjectiveAssignmentReport/ObjectiveAssignmentReportType.hpp"
#include "UMAA/MM/ObjectiveExecutionStatus/ObjectiveExecutionReportType.hpp"
#include "UMAA/MM/OperationalModeStatus/OperationalModeReportType.hpp"
#include "UMAA/MM/TaskPlanAssignmentReport/TaskPlanAssignmentReportType.hpp"
#include "UMAA/MM/TaskPlanExecutionStatus/TaskPlanExecutionReportType.hpp"

namespace umaa::sdk::services::mm {

using ActiveConstraintsControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::ActiveConstraintsControl::ActiveConstraintsCommandType,
    UMAA::MM::ActiveConstraintsControl::ActiveConstraintsCommandAckReportType,
    UMAA::MM::ActiveConstraintsControl::ActiveConstraintsCommandStatusType>;

using ActiveConstraintsControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::ActiveConstraintsControl::ActiveConstraintsCommandType,
    UMAA::MM::ActiveConstraintsControl::ActiveConstraintsCommandAckReportType,
    UMAA::MM::ActiveConstraintsControl::ActiveConstraintsCommandStatusType>;

using ConditionalAddControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::ConditionalControl::ConditionalAddCommandType,
    UMAA::MM::ConditionalControl::ConditionalAddCommandAckReportType,
    UMAA::MM::ConditionalControl::ConditionalAddCommandStatusType>;

using ConditionalAddControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::ConditionalControl::ConditionalAddCommandType,
    UMAA::MM::ConditionalControl::ConditionalAddCommandAckReportType,
    UMAA::MM::ConditionalControl::ConditionalAddCommandStatusType>;

using ConditionalDeleteControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::ConditionalControl::ConditionalDeleteCommandType,
    UMAA::MM::ConditionalControl::ConditionalDeleteCommandAckReportType,
    UMAA::MM::ConditionalControl::ConditionalDeleteCommandStatusType>;

using ConditionalDeleteControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::ConditionalControl::ConditionalDeleteCommandType,
    UMAA::MM::ConditionalControl::ConditionalDeleteCommandAckReportType,
    UMAA::MM::ConditionalControl::ConditionalDeleteCommandStatusType>;

using MissionPlanAssignmentControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::MissionPlanAssignmentControl::MissionPlanAssignmentCommandType,
    UMAA::MM::MissionPlanAssignmentControl::MissionPlanAssignmentCommandAckReportType,
    UMAA::MM::MissionPlanAssignmentControl::MissionPlanAssignmentCommandStatusType>;

using MissionPlanAssignmentControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::MissionPlanAssignmentControl::MissionPlanAssignmentCommandType,
    UMAA::MM::MissionPlanAssignmentControl::MissionPlanAssignmentCommandAckReportType,
    UMAA::MM::MissionPlanAssignmentControl::MissionPlanAssignmentCommandStatusType>;

using MissionPlanConstraintAddControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintAddCommandType,
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintAddCommandAckReportType,
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintAddCommandStatusType>;

using MissionPlanConstraintAddControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintAddCommandType,
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintAddCommandAckReportType,
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintAddCommandStatusType>;

using MissionPlanConstraintDeleteControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintDeleteCommandType,
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintDeleteCommandAckReportType,
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintDeleteCommandStatusType>;

using MissionPlanConstraintDeleteControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintDeleteCommandType,
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintDeleteCommandAckReportType,
    UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintDeleteCommandStatusType>;

using MissionPlanExecutionControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::MissionPlanExecutionControl::MissionPlanExecutionCommandType,
    UMAA::MM::MissionPlanExecutionControl::MissionPlanExecutionCommandAckReportType,
    UMAA::MM::MissionPlanExecutionControl::MissionPlanExecutionCommandStatusType>;

using MissionPlanExecutionControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::MissionPlanExecutionControl::MissionPlanExecutionCommandType,
    UMAA::MM::MissionPlanExecutionControl::MissionPlanExecutionCommandAckReportType,
    UMAA::MM::MissionPlanExecutionControl::MissionPlanExecutionCommandStatusType>;

using MissionPlanMissionAddControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionAddCommandType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionAddCommandAckReportType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionAddCommandStatusType>;

using MissionPlanMissionAddControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionAddCommandType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionAddCommandAckReportType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionAddCommandStatusType>;

using MissionPlanMissionClearControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionClearCommandType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionClearCommandAckReportType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionClearCommandStatusType>;

using MissionPlanMissionClearControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionClearCommandType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionClearCommandAckReportType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionClearCommandStatusType>;

using MissionPlanMissionDeleteControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionDeleteCommandType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionDeleteCommandAckReportType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionDeleteCommandStatusType>;

using MissionPlanMissionDeleteControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionDeleteCommandType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionDeleteCommandAckReportType,
    UMAA::MM::MissionPlanMissionControl::MissionPlanMissionDeleteCommandStatusType>;

using MissionPlanObjectiveAddControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveAddCommandType,
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveAddCommandAckReportType,
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveAddCommandStatusType>;

using MissionPlanObjectiveAddControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveAddCommandType,
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveAddCommandAckReportType,
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveAddCommandStatusType>;

using MissionPlanObjectiveDeleteControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveDeleteCommandType,
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveDeleteCommandAckReportType,
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveDeleteCommandStatusType>;

using MissionPlanObjectiveDeleteControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveDeleteCommandType,
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveDeleteCommandAckReportType,
    UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveDeleteCommandStatusType>;

using MissionPlanTaskAddControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskAddCommandType,
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskAddCommandAckReportType,
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskAddCommandStatusType>;

using MissionPlanTaskAddControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskAddCommandType,
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskAddCommandAckReportType,
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskAddCommandStatusType>;

using MissionPlanTaskDeleteControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskDeleteCommandType,
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskDeleteCommandAckReportType,
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskDeleteCommandStatusType>;

using MissionPlanTaskDeleteControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskDeleteCommandType,
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskDeleteCommandAckReportType,
    UMAA::MM::MissionPlanTaskControl::MissionPlanTaskDeleteCommandStatusType>;

using ObjectiveAssignmentControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::ObjectiveAssignmentControl::ObjectiveAssignmentCommandType,
    UMAA::MM::ObjectiveAssignmentControl::ObjectiveAssignmentCommandAckReportType,
    UMAA::MM::ObjectiveAssignmentControl::ObjectiveAssignmentCommandStatusType>;

using ObjectiveAssignmentControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::ObjectiveAssignmentControl::ObjectiveAssignmentCommandType,
    UMAA::MM::ObjectiveAssignmentControl::ObjectiveAssignmentCommandAckReportType,
    UMAA::MM::ObjectiveAssignmentControl::ObjectiveAssignmentCommandStatusType>;

using ObjectiveExecutionControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::ObjectiveExecutionControl::ObjectiveExecutionCommandType,
    UMAA::MM::ObjectiveExecutionControl::ObjectiveExecutionCommandAckReportType,
    UMAA::MM::ObjectiveExecutionControl::ObjectiveExecutionCommandStatusType>;

using ObjectiveExecutionControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::ObjectiveExecutionControl::ObjectiveExecutionCommandType,
    UMAA::MM::ObjectiveExecutionControl::ObjectiveExecutionCommandAckReportType,
    UMAA::MM::ObjectiveExecutionControl::ObjectiveExecutionCommandStatusType>;

using ObjectiveExecutorControlProvider = umaa::sdk::CommandProviderWithExec<
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorCommandType,
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorCommandAckReportType,
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorCommandStatusType,
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorExecutionStatusReportType>;

using ObjectiveExecutorControlConsumer = umaa::sdk::CommandConsumerWithExec<
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorCommandType,
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorCommandAckReportType,
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorCommandStatusType,
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorExecutionStatusReportType>;

using ObjectiveExecutorStateControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorStateCommandType,
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorStateCommandAckReportType,
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorStateCommandStatusType>;

using ObjectiveExecutorStateControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorStateCommandType,
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorStateCommandAckReportType,
    UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorStateCommandStatusType>;

using OperationalModeControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::OperationalModeControl::OperationalModeCommandType,
    UMAA::MM::OperationalModeControl::OperationalModeCommandAckReportType,
    UMAA::MM::OperationalModeControl::OperationalModeCommandStatusType>;

using OperationalModeControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::OperationalModeControl::OperationalModeCommandType,
    UMAA::MM::OperationalModeControl::OperationalModeCommandAckReportType,
    UMAA::MM::OperationalModeControl::OperationalModeCommandStatusType>;

using TaskPlanAssignmentControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::TaskPlanAssignmentControl::TaskPlanAssignmentCommandType,
    UMAA::MM::TaskPlanAssignmentControl::TaskPlanAssignmentCommandAckReportType,
    UMAA::MM::TaskPlanAssignmentControl::TaskPlanAssignmentCommandStatusType>;

using TaskPlanAssignmentControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::TaskPlanAssignmentControl::TaskPlanAssignmentCommandType,
    UMAA::MM::TaskPlanAssignmentControl::TaskPlanAssignmentCommandAckReportType,
    UMAA::MM::TaskPlanAssignmentControl::TaskPlanAssignmentCommandStatusType>;

using TaskPlanExecutionControlProvider = umaa::sdk::CommandProvider<
    UMAA::MM::TaskPlanExecutionControl::TaskPlanExecutionCommandType,
    UMAA::MM::TaskPlanExecutionControl::TaskPlanExecutionCommandAckReportType,
    UMAA::MM::TaskPlanExecutionControl::TaskPlanExecutionCommandStatusType>;

using TaskPlanExecutionControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::MM::TaskPlanExecutionControl::TaskPlanExecutionCommandType,
    UMAA::MM::TaskPlanExecutionControl::TaskPlanExecutionCommandAckReportType,
    UMAA::MM::TaskPlanExecutionControl::TaskPlanExecutionCommandStatusType>;

using ClientControlReportProvider = umaa::sdk::ReportProvider<UMAA::MM::ControlTransfer::ClientControlReportType>;
using ClientControlReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::ControlTransfer::ClientControlReportType>;

using ClientControlTransferReportProvider = umaa::sdk::ReportProvider<UMAA::MM::ControlTransfer::ClientControlTransferReportType>;
using ClientControlTransferReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::ControlTransfer::ClientControlTransferReportType>;

using ConditionalReportProvider = umaa::sdk::ReportProvider<UMAA::MM::ConditionalReport::ConditionalReportType>;
using ConditionalReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::ConditionalReport::ConditionalReportType>;

using ConditionalStateReportProvider = umaa::sdk::ReportProvider<UMAA::MM::ConditionalStateReport::ConditionalStateReportType>;
using ConditionalStateReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::ConditionalStateReport::ConditionalStateReportType>;

using ControlSystemControlReportProvider = umaa::sdk::ReportProvider<UMAA::MM::ControlTransfer::ControlSystemControlReportType>;
using ControlSystemControlReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::ControlTransfer::ControlSystemControlReportType>;

using ControlSystemTransferReportProvider = umaa::sdk::ReportProvider<UMAA::MM::ControlTransfer::ControlSystemTransferReportType>;
using ControlSystemTransferReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::ControlTransfer::ControlSystemTransferReportType>;

using MissionPlanReportProvider = umaa::sdk::ReportProvider<UMAA::MM::MissionPlanReport::MissionPlanReportType>;
using MissionPlanReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::MissionPlanReport::MissionPlanReportType>;

using MissionPlanAssignmentReportProvider = umaa::sdk::ReportProvider<UMAA::MM::MissionPlanAssignmentReport::MissionPlanAssignmentReportType>;
using MissionPlanAssignmentReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::MissionPlanAssignmentReport::MissionPlanAssignmentReportType>;

using MissionPlanExecutionReportProvider = umaa::sdk::ReportProvider<UMAA::MM::MissionPlanExecutionStatus::MissionPlanExecutionReportType>;
using MissionPlanExecutionReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::MissionPlanExecutionStatus::MissionPlanExecutionReportType>;

using ObjectiveAssignmentReportProvider = umaa::sdk::ReportProvider<UMAA::MM::ObjectiveAssignmentReport::ObjectiveAssignmentReportType>;
using ObjectiveAssignmentReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::ObjectiveAssignmentReport::ObjectiveAssignmentReportType>;

using ObjectiveExecutionReportProvider = umaa::sdk::ReportProvider<UMAA::MM::ObjectiveExecutionStatus::ObjectiveExecutionReportType>;
using ObjectiveExecutionReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::ObjectiveExecutionStatus::ObjectiveExecutionReportType>;

using OperationalModeReportProvider = umaa::sdk::ReportProvider<UMAA::MM::OperationalModeStatus::OperationalModeReportType>;
using OperationalModeReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::OperationalModeStatus::OperationalModeReportType>;

using TaskPlanAssignmentReportProvider = umaa::sdk::ReportProvider<UMAA::MM::TaskPlanAssignmentReport::TaskPlanAssignmentReportType>;
using TaskPlanAssignmentReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::TaskPlanAssignmentReport::TaskPlanAssignmentReportType>;

using TaskPlanExecutionReportProvider = umaa::sdk::ReportProvider<UMAA::MM::TaskPlanExecutionStatus::TaskPlanExecutionReportType>;
using TaskPlanExecutionReportConsumer = umaa::sdk::ReportConsumer<UMAA::MM::TaskPlanExecutionStatus::TaskPlanExecutionReportType>;

} // namespace umaa::sdk::services::mm

namespace umaa::sdk::topics::mm {

inline constexpr const char* ActiveConstraintsCommandTopic = "UMAA::MM::ActiveConstraintsControl::ActiveConstraintsCommandType";
inline constexpr const char* ActiveConstraintsCommandAckTopic = "UMAA::MM::ActiveConstraintsControl::ActiveConstraintsCommandAckReportType";
inline constexpr const char* ActiveConstraintsCommandStatusTopic = "UMAA::MM::ActiveConstraintsControl::ActiveConstraintsCommandStatusType";

inline constexpr const char* ConditionalAddCommandTopic = "UMAA::MM::ConditionalControl::ConditionalAddCommandType";
inline constexpr const char* ConditionalAddCommandAckTopic = "UMAA::MM::ConditionalControl::ConditionalAddCommandAckReportType";
inline constexpr const char* ConditionalAddCommandStatusTopic = "UMAA::MM::ConditionalControl::ConditionalAddCommandStatusType";

inline constexpr const char* ConditionalDeleteCommandTopic = "UMAA::MM::ConditionalControl::ConditionalDeleteCommandType";
inline constexpr const char* ConditionalDeleteCommandAckTopic = "UMAA::MM::ConditionalControl::ConditionalDeleteCommandAckReportType";
inline constexpr const char* ConditionalDeleteCommandStatusTopic = "UMAA::MM::ConditionalControl::ConditionalDeleteCommandStatusType";

inline constexpr const char* MissionPlanAssignmentCommandTopic = "UMAA::MM::MissionPlanAssignmentControl::MissionPlanAssignmentCommandType";
inline constexpr const char* MissionPlanAssignmentCommandAckTopic = "UMAA::MM::MissionPlanAssignmentControl::MissionPlanAssignmentCommandAckReportType";
inline constexpr const char* MissionPlanAssignmentCommandStatusTopic = "UMAA::MM::MissionPlanAssignmentControl::MissionPlanAssignmentCommandStatusType";

inline constexpr const char* MissionPlanConstraintAddCommandTopic = "UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintAddCommandType";
inline constexpr const char* MissionPlanConstraintAddCommandAckTopic = "UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintAddCommandAckReportType";
inline constexpr const char* MissionPlanConstraintAddCommandStatusTopic = "UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintAddCommandStatusType";

inline constexpr const char* MissionPlanConstraintDeleteCommandTopic = "UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintDeleteCommandType";
inline constexpr const char* MissionPlanConstraintDeleteCommandAckTopic = "UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintDeleteCommandAckReportType";
inline constexpr const char* MissionPlanConstraintDeleteCommandStatusTopic = "UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintDeleteCommandStatusType";

inline constexpr const char* MissionPlanExecutionCommandTopic = "UMAA::MM::MissionPlanExecutionControl::MissionPlanExecutionCommandType";
inline constexpr const char* MissionPlanExecutionCommandAckTopic = "UMAA::MM::MissionPlanExecutionControl::MissionPlanExecutionCommandAckReportType";
inline constexpr const char* MissionPlanExecutionCommandStatusTopic = "UMAA::MM::MissionPlanExecutionControl::MissionPlanExecutionCommandStatusType";

inline constexpr const char* MissionPlanMissionAddCommandTopic = "UMAA::MM::MissionPlanMissionControl::MissionPlanMissionAddCommandType";
inline constexpr const char* MissionPlanMissionAddCommandAckTopic = "UMAA::MM::MissionPlanMissionControl::MissionPlanMissionAddCommandAckReportType";
inline constexpr const char* MissionPlanMissionAddCommandStatusTopic = "UMAA::MM::MissionPlanMissionControl::MissionPlanMissionAddCommandStatusType";

inline constexpr const char* MissionPlanMissionClearCommandTopic = "UMAA::MM::MissionPlanMissionControl::MissionPlanMissionClearCommandType";
inline constexpr const char* MissionPlanMissionClearCommandAckTopic = "UMAA::MM::MissionPlanMissionControl::MissionPlanMissionClearCommandAckReportType";
inline constexpr const char* MissionPlanMissionClearCommandStatusTopic = "UMAA::MM::MissionPlanMissionControl::MissionPlanMissionClearCommandStatusType";

inline constexpr const char* MissionPlanMissionDeleteCommandTopic = "UMAA::MM::MissionPlanMissionControl::MissionPlanMissionDeleteCommandType";
inline constexpr const char* MissionPlanMissionDeleteCommandAckTopic = "UMAA::MM::MissionPlanMissionControl::MissionPlanMissionDeleteCommandAckReportType";
inline constexpr const char* MissionPlanMissionDeleteCommandStatusTopic = "UMAA::MM::MissionPlanMissionControl::MissionPlanMissionDeleteCommandStatusType";

inline constexpr const char* MissionPlanObjectiveAddCommandTopic = "UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveAddCommandType";
inline constexpr const char* MissionPlanObjectiveAddCommandAckTopic = "UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveAddCommandAckReportType";
inline constexpr const char* MissionPlanObjectiveAddCommandStatusTopic = "UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveAddCommandStatusType";

inline constexpr const char* MissionPlanObjectiveDeleteCommandTopic = "UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveDeleteCommandType";
inline constexpr const char* MissionPlanObjectiveDeleteCommandAckTopic = "UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveDeleteCommandAckReportType";
inline constexpr const char* MissionPlanObjectiveDeleteCommandStatusTopic = "UMAA::MM::MissionPlanObjectiveControl::MissionPlanObjectiveDeleteCommandStatusType";

inline constexpr const char* MissionPlanTaskAddCommandTopic = "UMAA::MM::MissionPlanTaskControl::MissionPlanTaskAddCommandType";
inline constexpr const char* MissionPlanTaskAddCommandAckTopic = "UMAA::MM::MissionPlanTaskControl::MissionPlanTaskAddCommandAckReportType";
inline constexpr const char* MissionPlanTaskAddCommandStatusTopic = "UMAA::MM::MissionPlanTaskControl::MissionPlanTaskAddCommandStatusType";

inline constexpr const char* MissionPlanTaskDeleteCommandTopic = "UMAA::MM::MissionPlanTaskControl::MissionPlanTaskDeleteCommandType";
inline constexpr const char* MissionPlanTaskDeleteCommandAckTopic = "UMAA::MM::MissionPlanTaskControl::MissionPlanTaskDeleteCommandAckReportType";
inline constexpr const char* MissionPlanTaskDeleteCommandStatusTopic = "UMAA::MM::MissionPlanTaskControl::MissionPlanTaskDeleteCommandStatusType";

inline constexpr const char* ObjectiveAssignmentCommandTopic = "UMAA::MM::ObjectiveAssignmentControl::ObjectiveAssignmentCommandType";
inline constexpr const char* ObjectiveAssignmentCommandAckTopic = "UMAA::MM::ObjectiveAssignmentControl::ObjectiveAssignmentCommandAckReportType";
inline constexpr const char* ObjectiveAssignmentCommandStatusTopic = "UMAA::MM::ObjectiveAssignmentControl::ObjectiveAssignmentCommandStatusType";

inline constexpr const char* ObjectiveExecutionCommandTopic = "UMAA::MM::ObjectiveExecutionControl::ObjectiveExecutionCommandType";
inline constexpr const char* ObjectiveExecutionCommandAckTopic = "UMAA::MM::ObjectiveExecutionControl::ObjectiveExecutionCommandAckReportType";
inline constexpr const char* ObjectiveExecutionCommandStatusTopic = "UMAA::MM::ObjectiveExecutionControl::ObjectiveExecutionCommandStatusType";

inline constexpr const char* ObjectiveExecutorCommandTopic = "UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorCommandType";
inline constexpr const char* ObjectiveExecutorCommandAckTopic = "UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorCommandAckReportType";
inline constexpr const char* ObjectiveExecutorCommandStatusTopic = "UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorCommandStatusType";
inline constexpr const char* ObjectiveExecutorExecStatusTopic = "UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorExecutionStatusReportType";

inline constexpr const char* ObjectiveExecutorStateCommandTopic = "UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorStateCommandType";
inline constexpr const char* ObjectiveExecutorStateCommandAckTopic = "UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorStateCommandAckReportType";
inline constexpr const char* ObjectiveExecutorStateCommandStatusTopic = "UMAA::MM::ObjectiveExecutorControl::ObjectiveExecutorStateCommandStatusType";

inline constexpr const char* OperationalModeCommandTopic = "UMAA::MM::OperationalModeControl::OperationalModeCommandType";
inline constexpr const char* OperationalModeCommandAckTopic = "UMAA::MM::OperationalModeControl::OperationalModeCommandAckReportType";
inline constexpr const char* OperationalModeCommandStatusTopic = "UMAA::MM::OperationalModeControl::OperationalModeCommandStatusType";

inline constexpr const char* TaskPlanAssignmentCommandTopic = "UMAA::MM::TaskPlanAssignmentControl::TaskPlanAssignmentCommandType";
inline constexpr const char* TaskPlanAssignmentCommandAckTopic = "UMAA::MM::TaskPlanAssignmentControl::TaskPlanAssignmentCommandAckReportType";
inline constexpr const char* TaskPlanAssignmentCommandStatusTopic = "UMAA::MM::TaskPlanAssignmentControl::TaskPlanAssignmentCommandStatusType";

inline constexpr const char* TaskPlanExecutionCommandTopic = "UMAA::MM::TaskPlanExecutionControl::TaskPlanExecutionCommandType";
inline constexpr const char* TaskPlanExecutionCommandAckTopic = "UMAA::MM::TaskPlanExecutionControl::TaskPlanExecutionCommandAckReportType";
inline constexpr const char* TaskPlanExecutionCommandStatusTopic = "UMAA::MM::TaskPlanExecutionControl::TaskPlanExecutionCommandStatusType";

inline constexpr const char* ClientControlReportTopic = "UMAA::MM::ControlTransfer::ClientControlReportType";
inline constexpr const char* ClientControlTransferReportTopic = "UMAA::MM::ControlTransfer::ClientControlTransferReportType";
inline constexpr const char* ConditionalReportTopic = "UMAA::MM::ConditionalReport::ConditionalReportType";
inline constexpr const char* ConditionalStateReportTopic = "UMAA::MM::ConditionalStateReport::ConditionalStateReportType";
inline constexpr const char* ControlSystemControlReportTopic = "UMAA::MM::ControlTransfer::ControlSystemControlReportType";
inline constexpr const char* ControlSystemTransferReportTopic = "UMAA::MM::ControlTransfer::ControlSystemTransferReportType";
inline constexpr const char* MissionPlanReportTopic = "UMAA::MM::MissionPlanReport::MissionPlanReportType";
inline constexpr const char* MissionPlanAssignmentReportTopic = "UMAA::MM::MissionPlanAssignmentReport::MissionPlanAssignmentReportType";
inline constexpr const char* MissionPlanExecutionReportTopic = "UMAA::MM::MissionPlanExecutionStatus::MissionPlanExecutionReportType";
inline constexpr const char* ObjectiveAssignmentReportTopic = "UMAA::MM::ObjectiveAssignmentReport::ObjectiveAssignmentReportType";
inline constexpr const char* ObjectiveExecutionReportTopic = "UMAA::MM::ObjectiveExecutionStatus::ObjectiveExecutionReportType";
inline constexpr const char* OperationalModeReportTopic = "UMAA::MM::OperationalModeStatus::OperationalModeReportType";
inline constexpr const char* TaskPlanAssignmentReportTopic = "UMAA::MM::TaskPlanAssignmentReport::TaskPlanAssignmentReportType";
inline constexpr const char* TaskPlanExecutionReportTopic = "UMAA::MM::TaskPlanExecutionStatus::TaskPlanExecutionReportType";

} // namespace umaa::sdk::topics::mm

#endif // UMAA_SDK_SERVICES_MM_HPP
