// Auto-generated by cpp/sdk/tools/generate_services.py — DO NOT EDIT
#ifndef UMAA_SDK_SERVICES_MO_HPP
#define UMAA_SDK_SERVICES_MO_HPP

#include "umaa/sdk/command_provider.hpp"
#include "umaa/sdk/command_consumer.hpp"
#include "umaa/sdk/report_provider.hpp"
#include "umaa/sdk/report_consumer.hpp"

#include "UMAA/MO/FreeFloatControl/FreeFloatCommandType.hpp"
#include "UMAA/MO/FreeFloatControl/FreeFloatCommandAckReportType.hpp"
#include "UMAA/MO/FreeFloatControl/FreeFloatCommandStatusType.hpp"
#include "UMAA/MO/FreeFloatControl/FreeFloatExecutionStatusReportType.hpp"
#include "UMAA/MO/GlobalDriftControl/GlobalDriftCommandType.hpp"
#include "UMAA/MO/GlobalDriftControl/GlobalDriftCommandAckReportType.hpp"
#include "UMAA/MO/GlobalDriftControl/GlobalDriftCommandStatusType.hpp"
#include "UMAA/MO/GlobalDriftControl/GlobalDriftExecutionStatusReportType.hpp"
#include "UMAA/MO/GlobalHoverControl/GlobalHoverCommandType.hpp"
#include "UMAA/MO/GlobalHoverControl/GlobalHoverCommandAckReportType.hpp"
#include "UMAA/MO/GlobalHoverControl/GlobalHoverCommandStatusType.hpp"
#include "UMAA/MO/GlobalHoverControl/GlobalHoverExecutionStatusReportType.hpp"
#include "UMAA/MO/GlobalVectorControl/GlobalVectorCommandType.hpp"
#include "UMAA/MO/GlobalVectorControl/GlobalVectorCommandAckReportType.hpp"
#include "UMAA/MO/GlobalVectorControl/GlobalVectorCommandStatusType.hpp"
#include "UMAA/MO/GlobalVectorControl/GlobalVectorExecutionStatusReportType.hpp"
#include "UMAA/MO/GlobalWaypointControl/GlobalWaypointCommandType.hpp"
#include "UMAA/MO/GlobalWaypointControl/GlobalWaypointCommandAckReportType.hpp"
#include "UMAA/MO/GlobalWaypointControl/GlobalWaypointCommandStatusType.hpp"
#include "UMAA/MO/GlobalWaypointControl/GlobalWaypointExecutionStatusReportType.hpp"
#include "UMAA/MO/PrimitiveDriverControl/PrimitiveDriverCommandType.hpp"
#include "UMAA/MO/PrimitiveDriverControl/PrimitiveDriverCommandAckReportType.hpp"
#include "UMAA/MO/PrimitiveDriverControl/PrimitiveDriverCommandStatusType.hpp"
#include "UMAA/MO/PrimitiveDriverControl/PrimitiveDriverExecutionStatusReportType.hpp"
#include "UMAA/MO/ContactManeuverInfluenceStatus/ContactManeuverInfluenceReportType.hpp"
#include "UMAA/MO/CoordinationSituationalSignalStatus/CoordinationSituationalSignalReportType.hpp"
#include "UMAA/MO/HazardAvoidanceConfig/HazardAvoidanceConfigReportType.hpp"

namespace umaa::sdk::services::mo {

using FreeFloatControlProvider = umaa::sdk::CommandProviderWithExec<
    UMAA::MO::FreeFloatControl::FreeFloatCommandType,
    UMAA::MO::FreeFloatControl::FreeFloatCommandAckReportType,
    UMAA::MO::FreeFloatControl::FreeFloatCommandStatusType,
    UMAA::MO::FreeFloatControl::FreeFloatExecutionStatusReportType>;

using FreeFloatControlConsumer = umaa::sdk::CommandConsumerWithExec<
    UMAA::MO::FreeFloatControl::FreeFloatCommandType,
    UMAA::MO::FreeFloatControl::FreeFloatCommandAckReportType,
    UMAA::MO::FreeFloatControl::FreeFloatCommandStatusType,
    UMAA::MO::FreeFloatControl::FreeFloatExecutionStatusReportType>;

using GlobalDriftControlProvider = umaa::sdk::CommandProviderWithExec<
    UMAA::MO::GlobalDriftControl::GlobalDriftCommandType,
    UMAA::MO::GlobalDriftControl::GlobalDriftCommandAckReportType,
    UMAA::MO::GlobalDriftControl::GlobalDriftCommandStatusType,
    UMAA::MO::GlobalDriftControl::GlobalDriftExecutionStatusReportType>;

using GlobalDriftControlConsumer = umaa::sdk::CommandConsumerWithExec<
    UMAA::MO::GlobalDriftControl::GlobalDriftCommandType,
    UMAA::MO::GlobalDriftControl::GlobalDriftCommandAckReportType,
    UMAA::MO::GlobalDriftControl::GlobalDriftCommandStatusType,
    UMAA::MO::GlobalDriftControl::GlobalDriftExecutionStatusReportType>;

using GlobalHoverControlProvider = umaa::sdk::CommandProviderWithExec<
    UMAA::MO::GlobalHoverControl::GlobalHoverCommandType,
    UMAA::MO::GlobalHoverControl::GlobalHoverCommandAckReportType,
    UMAA::MO::GlobalHoverControl::GlobalHoverCommandStatusType,
    UMAA::MO::GlobalHoverControl::GlobalHoverExecutionStatusReportType>;

using GlobalHoverControlConsumer = umaa::sdk::CommandConsumerWithExec<
    UMAA::MO::GlobalHoverControl::GlobalHoverCommandType,
    UMAA::MO::GlobalHoverControl::GlobalHoverCommandAckReportType,
    UMAA::MO::GlobalHoverControl::GlobalHoverCommandStatusType,
    UMAA::MO::GlobalHoverControl::GlobalHoverExecutionStatusReportType>;

using GlobalVectorControlProvider = umaa::sdk::CommandProviderWithExec<
    UMAA::MO::GlobalVectorControl::GlobalVectorCommandType,
    UMAA::MO::GlobalVectorControl::GlobalVectorCommandAckReportType,
    UMAA::MO::GlobalVectorControl::GlobalVectorCommandStatusType,
    UMAA::MO::GlobalVectorControl::GlobalVectorExecutionStatusReportType>;

using GlobalVectorControlConsumer = umaa::sdk::CommandConsumerWithExec<
    UMAA::MO::GlobalVectorControl::GlobalVectorCommandType,
    UMAA::MO::GlobalVectorControl::GlobalVectorCommandAckReportType,
    UMAA::MO::GlobalVectorControl::GlobalVectorCommandStatusType,
    UMAA::MO::GlobalVectorControl::GlobalVectorExecutionStatusReportType>;

using GlobalWaypointControlProvider = umaa::sdk::CommandProviderWithExec<
    UMAA::MO::GlobalWaypointControl::GlobalWaypointCommandType,
    UMAA::MO::GlobalWaypointControl::GlobalWaypointCommandAckReportType,
    UMAA::MO::GlobalWaypointControl::GlobalWaypointCommandStatusType,
    UMAA::MO::GlobalWaypointControl::GlobalWaypointExecutionStatusReportType>;

using GlobalWaypointControlConsumer = umaa::sdk::CommandConsumerWithExec<
    UMAA::MO::GlobalWaypointControl::GlobalWaypointCommandType,
    UMAA::MO::GlobalWaypointControl::GlobalWaypointCommandAckReportType,
    UMAA::MO::GlobalWaypointControl::GlobalWaypointCommandStatusType,
    UMAA::MO::GlobalWaypointControl::GlobalWaypointExecutionStatusReportType>;

using PrimitiveDriverControlProvider = umaa::sdk::CommandProviderWithExec<
    UMAA::MO::PrimitiveDriverControl::PrimitiveDriverCommandType,
    UMAA::MO::PrimitiveDriverControl::PrimitiveDriverCommandAckReportType,
    UMAA::MO::PrimitiveDriverControl::PrimitiveDriverCommandStatusType,
    UMAA::MO::PrimitiveDriverControl::PrimitiveDriverExecutionStatusReportType>;

using PrimitiveDriverControlConsumer = umaa::sdk::CommandConsumerWithExec<
    UMAA::MO::PrimitiveDriverControl::PrimitiveDriverCommandType,
    UMAA::MO::PrimitiveDriverControl::PrimitiveDriverCommandAckReportType,
    UMAA::MO::PrimitiveDriverControl::PrimitiveDriverCommandStatusType,
    UMAA::MO::PrimitiveDriverControl::PrimitiveDriverExecutionStatusReportType>;

using ContactManeuverInfluenceReportProvider = umaa::sdk::ReportProvider<UMAA::MO::ContactManeuverInfluenceStatus::ContactManeuverInfluenceReportType>;
using ContactManeuverInfluenceReportConsumer = umaa::sdk::ReportConsumer<UMAA::MO::ContactManeuverInfluenceStatus::ContactManeuverInfluenceReportType>;

using CoordinationSituationalSignalReportProvider = umaa::sdk::ReportProvider<UMAA::MO::CoordinationSituationalSignalStatus::CoordinationSituationalSignalReportType>;
using CoordinationSituationalSignalReportConsumer = umaa::sdk::ReportConsumer<UMAA::MO::CoordinationSituationalSignalStatus::CoordinationSituationalSignalReportType>;

using HazardAvoidanceConfigReportProvider = umaa::sdk::ReportProvider<UMAA::MO::HazardAvoidanceConfig::HazardAvoidanceConfigReportType>;
using HazardAvoidanceConfigReportConsumer = umaa::sdk::ReportConsumer<UMAA::MO::HazardAvoidanceConfig::HazardAvoidanceConfigReportType>;

} // namespace umaa::sdk::services::mo

namespace umaa::sdk::topics::mo {

inline constexpr const char* FreeFloatCommandTopic = "UMAA::MO::FreeFloatControl::FreeFloatCommandType";
inline constexpr const char* FreeFloatCommandAckTopic = "UMAA::MO::FreeFloatControl::FreeFloatCommandAckReportType";
inline constexpr const char* FreeFloatCommandStatusTopic = "UMAA::MO::FreeFloatControl::FreeFloatCommandStatusType";
inline constexpr const char* FreeFloatExecStatusTopic = "UMAA::MO::FreeFloatControl::FreeFloatExecutionStatusReportType";

inline constexpr const char* GlobalDriftCommandTopic = "UMAA::MO::GlobalDriftControl::GlobalDriftCommandType";
inline constexpr const char* GlobalDriftCommandAckTopic = "UMAA::MO::GlobalDriftControl::GlobalDriftCommandAckReportType";
inline constexpr const char* GlobalDriftCommandStatusTopic = "UMAA::MO::GlobalDriftControl::GlobalDriftCommandStatusType";
inline constexpr const char* GlobalDriftExecStatusTopic = "UMAA::MO::GlobalDriftControl::GlobalDriftExecutionStatusReportType";

inline constexpr const char* GlobalHoverCommandTopic = "UMAA::MO::GlobalHoverControl::GlobalHoverCommandType";
inline constexpr const char* GlobalHoverCommandAckTopic = "UMAA::MO::GlobalHoverControl::GlobalHoverCommandAckReportType";
inline constexpr const char* GlobalHoverCommandStatusTopic = "UMAA::MO::GlobalHoverControl::GlobalHoverCommandStatusType";
inline constexpr const char* GlobalHoverExecStatusTopic = "UMAA::MO::GlobalHoverControl::GlobalHoverExecutionStatusReportType";

inline constexpr const char* GlobalVectorCommandTopic = "UMAA::MO::GlobalVectorControl::GlobalVectorCommandType";
inline constexpr const char* GlobalVectorCommandAckTopic = "UMAA::MO::GlobalVectorControl::GlobalVectorCommandAckReportType";
inline constexpr const char* GlobalVectorCommandStatusTopic = "UMAA::MO::GlobalVectorControl::GlobalVectorCommandStatusType";
inline constexpr const char* GlobalVectorExecStatusTopic = "UMAA::MO::GlobalVectorControl::GlobalVectorExecutionStatusReportType";

inline constexpr const char* GlobalWaypointCommandTopic = "UMAA::MO::GlobalWaypointControl::GlobalWaypointCommandType";
inline constexpr const char* GlobalWaypointCommandAckTopic = "UMAA::MO::GlobalWaypointControl::GlobalWaypointCommandAckReportType";
inline constexpr const char* GlobalWaypointCommandStatusTopic = "UMAA::MO::GlobalWaypointControl::GlobalWaypointCommandStatusType";
inline constexpr const char* GlobalWaypointExecStatusTopic = "UMAA::MO::GlobalWaypointControl::GlobalWaypointExecutionStatusReportType";

inline constexpr const char* PrimitiveDriverCommandTopic = "UMAA::MO::PrimitiveDriverControl::PrimitiveDriverCommandType";
inline constexpr const char* PrimitiveDriverCommandAckTopic = "UMAA::MO::PrimitiveDriverControl::PrimitiveDriverCommandAckReportType";
inline constexpr const char* PrimitiveDriverCommandStatusTopic = "UMAA::MO::PrimitiveDriverControl::PrimitiveDriverCommandStatusType";
inline constexpr const char* PrimitiveDriverExecStatusTopic = "UMAA::MO::PrimitiveDriverControl::PrimitiveDriverExecutionStatusReportType";

inline constexpr const char* ContactManeuverInfluenceReportTopic = "UMAA::MO::ContactManeuverInfluenceStatus::ContactManeuverInfluenceReportType";
inline constexpr const char* CoordinationSituationalSignalReportTopic = "UMAA::MO::CoordinationSituationalSignalStatus::CoordinationSituationalSignalReportType";
inline constexpr const char* HazardAvoidanceConfigReportTopic = "UMAA::MO::HazardAvoidanceConfig::HazardAvoidanceConfigReportType";

} // namespace umaa::sdk::topics::mo

#endif // UMAA_SDK_SERVICES_MO_HPP
