// Auto-generated by cpp/sdk/tools/generate_services.py — DO NOT EDIT
#ifndef UMAA_SDK_SERVICES_SA_HPP
#define UMAA_SDK_SERVICES_SA_HPP

#include "umaa/sdk/command_provider.hpp"
#include "umaa/sdk/command_consumer.hpp"
#include "umaa/sdk/report_provider.hpp"
#include "umaa/sdk/report_consumer.hpp"

#include "UMAA/SA/ContactFilterConfig/ContactFilterConfigCommandType.hpp"
#include "UMAA/SA/ContactFilterConfig/ContactFilterConfigAckReportType.hpp"
#include "UMAA/SA/ContactFilterConfig/ContactFilterConfigCommandStatusType.hpp"
#include "UMAA/SA/GlobalPoseConfig/GlobalPoseConfigCommandType.hpp"
#include "UMAA/SA/GlobalPoseConfig/GlobalPoseConfigAckReportType.hpp"
#include "UMAA/SA/GlobalPoseConfig/GlobalPoseConfigCommandStatusType.hpp"
#include "UMAA/SA/AccelerationStatus/AccelerationReportType.hpp"
#include "UMAA/SA/CompartmentStatus/CompartmentReportType.hpp"
#include "UMAA/SA/CompartmentConfig/CompartmentConfigReportType.hpp"
#include "UMAA/SA/ContactReport/ContactReportType.hpp"
#include "UMAA/SA/ContactCOLREGSClassificationStatus/ContactCOLREGSClassificationReportType.hpp"
#include "UMAA/SA/ContactCategoryReport/ContactCategoryReportType.hpp"
#include "UMAA/SA/ContactIdentityReport/ContactIdentityReportType.hpp"
#include "UMAA/SA/ContactVisualClassificationStatus/ContactVisualClassificationReportType.hpp"
#include "UMAA/SA/DateTimeStatus/DateTimeReportType.hpp"
#include "UMAA/SA/ECEFPoseStatus/ECEFPoseReportType.hpp"
#include "UMAA/SA/GlobalPoseStatus/GlobalPoseReportType.hpp"
#include "UMAA/SA/GlobalPoseConfig/GlobalPoseConfigReportType.hpp"
#include "UMAA/SA/LandmarkReport/LandmarkReportType.hpp"
#include "UMAA/SA/MagneticVariationStatus/MagneticVariationReportType.hpp"
#include "UMAA/SA/MagneticVariationSpecs/MagneticVariationSpecsReportType.hpp"
#include "UMAA/SA/OrientationStatus/OrientationReportType.hpp"
#include "UMAA/SA/PassiveContactReport/PassiveContactReportType.hpp"
#include "UMAA/SA/PathReporterStatus/PathReporterReportType.hpp"
#include "UMAA/SA/PathReporterSpecs/PathReporterSpecsReportType.hpp"
#include "UMAA/SA/RelativeContactReport/RelativeContactReportType.hpp"
#include "UMAA/SA/SeaStateReport/SeaStateReportType.hpp"
#include "UMAA/SA/SoundVelocityProfileReport/SoundVelocityProfileReportType.hpp"
#include "UMAA/SA/SpeedStatus/SpeedReportType.hpp"
#include "UMAA/SA/StillImageStatus/StillImageReportType.hpp"
#include "UMAA/SA/TerrainReport/TerrainReportType.hpp"
#include "UMAA/SA/TranslationalShipMotionStatus/TranslationalShipMotionReportType.hpp"
#include "UMAA/SA/VelocityStatus/VelocityReportType.hpp"
#include "UMAA/SA/WaterCharacteristicsStatus/WaterCharacteristicsReportType.hpp"
#include "UMAA/SA/WaterCurrentStatus/WaterCurrentReportType.hpp"
#include "UMAA/SA/WeatherStatus/WeatherReportType.hpp"
#include "UMAA/SA/WindStatus/WindReportType.hpp"

namespace umaa::sdk::services::sa {

using ContactFilterConfigProvider = umaa::sdk::CommandProvider<
    UMAA::SA::ContactFilterConfig::ContactFilterConfigCommandType,
    UMAA::SA::ContactFilterConfig::ContactFilterConfigAckReportType,
    UMAA::SA::ContactFilterConfig::ContactFilterConfigCommandStatusType>;

using ContactFilterConfigConsumer = umaa::sdk::CommandConsumer<
    UMAA::SA::ContactFilterConfig::ContactFilterConfigCommandType,
    UMAA::SA::ContactFilterConfig::ContactFilterConfigAckReportType,
    UMAA::SA::ContactFilterConfig::ContactFilterConfigCommandStatusType>;

using GlobalPoseConfigProvider = umaa::sdk::CommandProvider<
    UMAA::SA::GlobalPoseConfig::GlobalPoseConfigCommandType,
    UMAA::SA::GlobalPoseConfig::GlobalPoseConfigAckReportType,
    UMAA::SA::GlobalPoseConfig::GlobalPoseConfigCommandStatusType>;

using GlobalPoseConfigConsumer = umaa::sdk::CommandConsumer<
    UMAA::SA::GlobalPoseConfig::GlobalPoseConfigCommandType,
    UMAA::SA::GlobalPoseConfig::GlobalPoseConfigAckReportType,
    UMAA::SA::GlobalPoseConfig::GlobalPoseConfigCommandStatusType>;

using AccelerationReportProvider = umaa::sdk::ReportProvider<UMAA::SA::AccelerationStatus::AccelerationReportType>;
using AccelerationReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::AccelerationStatus::AccelerationReportType>;

using CompartmentReportProvider = umaa::sdk::ReportProvider<UMAA::SA::CompartmentStatus::CompartmentReportType>;
using CompartmentReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::CompartmentStatus::CompartmentReportType>;

using CompartmentConfigReportProvider = umaa::sdk::ReportProvider<UMAA::SA::CompartmentConfig::CompartmentConfigReportType>;
using CompartmentConfigReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::CompartmentConfig::CompartmentConfigReportType>;

using ContactReportProvider = umaa::sdk::ReportProvider<UMAA::SA::ContactReport::ContactReportType>;
using ContactReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::ContactReport::ContactReportType>;

using ContactCOLREGSClassificationReportProvider = umaa::sdk::ReportProvider<UMAA::SA::ContactCOLREGSClassificationStatus::ContactCOLREGSClassificationReportType>;
using ContactCOLREGSClassificationReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::ContactCOLREGSClassificationStatus::ContactCOLREGSClassificationReportType>;

using ContactCategoryReportProvider = umaa::sdk::ReportProvider<UMAA::SA::ContactCategoryReport::ContactCategoryReportType>;
using ContactCategoryReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::ContactCategoryReport::ContactCategoryReportType>;

using ContactIdentityReportProvider = umaa::sdk::ReportProvider<UMAA::SA::ContactIdentityReport::ContactIdentityReportType>;
using ContactIdentityReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::ContactIdentityReport::ContactIdentityReportType>;

using ContactVisualClassificationReportProvider = umaa::sdk::ReportProvider<UMAA::SA::ContactVisualClassificationStatus::ContactVisualClassificationReportType>;
using ContactVisualClassificationReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::ContactVisualClassificationStatus::ContactVisualClassificationReportType>;

using DateTimeReportProvider = umaa::sdk::ReportProvider<UMAA::SA::DateTimeStatus::DateTimeReportType>;
using DateTimeReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::DateTimeStatus::DateTimeReportType>;

using ECEFPoseReportProvider = umaa::sdk::ReportProvider<UMAA::SA::ECEFPoseStatus::ECEFPoseReportType>;
using ECEFPoseReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::ECEFPoseStatus::ECEFPoseReportType>;

using GlobalPoseReportProvider = umaa::sdk::ReportProvider<UMAA::SA::GlobalPoseStatus::GlobalPoseReportType>;
using GlobalPoseReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::GlobalPoseStatus::GlobalPoseReportType>;

using GlobalPoseConfigReportProvider = umaa::sdk::ReportProvider<UMAA::SA::GlobalPoseConfig::GlobalPoseConfigReportType>;
using GlobalPoseConfigReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::GlobalPoseConfig::GlobalPoseConfigReportType>;

using LandmarkReportProvider = umaa::sdk::ReportProvider<UMAA::SA::LandmarkReport::LandmarkReportType>;
using LandmarkReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::LandmarkReport::LandmarkReportType>;

using MagneticVariationReportProvider = umaa::sdk::ReportProvider<UMAA::SA::MagneticVariationStatus::MagneticVariationReportType>;
using MagneticVariationReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::MagneticVariationStatus::MagneticVariationReportType>;

using MagneticVariationSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::SA::MagneticVariationSpecs::MagneticVariationSpecsReportType>;
using MagneticVariationSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::MagneticVariationSpecs::MagneticVariationSpecsReportType>;

using OrientationReportProvider = umaa::sdk::ReportProvider<UMAA::SA::OrientationStatus::OrientationReportType>;
using OrientationReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::OrientationStatus::OrientationReportType>;

using PassiveContactReportProvider = umaa::sdk::ReportProvider<UMAA::SA::PassiveContactReport::PassiveContactReportType>;
using PassiveContactReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::PassiveContactReport::PassiveContactReportType>;

using PathReporterReportProvider = umaa::sdk::ReportProvider<UMAA::SA::PathReporterStatus::PathReporterReportType>;
using PathReporterReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::PathReporterStatus::PathReporterReportType>;

using PathReporterSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::SA::PathReporterSpecs::PathReporterSpecsReportType>;
using PathReporterSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::PathReporterSpecs::PathReporterSpecsReportType>;

using RelativeContactReportProvider = umaa::sdk::ReportProvider<UMAA::SA::RelativeContactReport::RelativeContactReportType>;
using RelativeContactReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::RelativeContactReport::RelativeContactReportType>;

using SeaStateReportProvider = umaa::sdk::ReportProvider<UMAA::SA::SeaStateReport::SeaStateReportType>;
using SeaStateReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::SeaStateReport::SeaStateReportType>;

using SoundVelocityProfileReportProvider = umaa::sdk::ReportProvider<UMAA::SA::SoundVelocityProfileReport::SoundVelocityProfileReportType>;
using SoundVelocityProfileReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::SoundVelocityProfileReport::SoundVelocityProfileReportType>;

using SpeedReportProvider = umaa::sdk::ReportProvider<UMAA::SA::SpeedStatus::SpeedReportType>;
using SpeedReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::SpeedStatus::SpeedReportType>;

using StillImageReportProvider = umaa::sdk::ReportProvider<UMAA::SA::StillImageStatus::StillImageReportType>;
using StillImageReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::StillImageStatus::StillImageReportType>;

using TerrainReportProvider = umaa::sdk::ReportProvider<UMAA::SA::TerrainReport::TerrainReportType>;
using TerrainReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::TerrainReport::TerrainReportType>;

using TranslationalShipMotionReportProvider = umaa::sdk::ReportProvider<UMAA::SA::TranslationalShipMotionStatus::TranslationalShipMotionReportType>;
using TranslationalShipMotionReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::TranslationalShipMotionStatus::TranslationalShipMotionReportType>;

using VelocityReportProvider = umaa::sdk::ReportProvider<UMAA::SA::VelocityStatus::VelocityReportType>;
using VelocityReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::VelocityStatus::VelocityReportType>;

using WaterCharacteristicsReportProvider = umaa::sdk::ReportProvider<UMAA::SA::WaterCharacteristicsStatus::WaterCharacteristicsReportType>;
using WaterCharacteristicsReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::WaterCharacteristicsStatus::WaterCharacteristicsReportType>;

using WaterCurrentReportProvider = umaa::sdk::ReportProvider<UMAA::SA::WaterCurrentStatus::WaterCurrentReportType>;
using WaterCurrentReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::WaterCurrentStatus::WaterCurrentReportType>;

using WeatherReportProvider = umaa::sdk::ReportProvider<UMAA::SA::WeatherStatus::WeatherReportType>;
using WeatherReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::WeatherStatus::WeatherReportType>;

using WindReportProvider = umaa::sdk::ReportProvider<UMAA::SA::WindStatus::WindReportType>;
using WindReportConsumer = umaa::sdk::ReportConsumer<UMAA::SA::WindStatus::WindReportType>;

} // namespace umaa::sdk::services::sa

namespace umaa::sdk::topics::sa {

inline constexpr const char* ContactFilterConfigCommandTopic = "UMAA::SA::ContactFilterConfig::ContactFilterConfigCommandType";
inline constexpr const char* ContactFilterConfigAckTopic = "UMAA::SA::ContactFilterConfig::ContactFilterConfigAckReportType";
inline constexpr const char* ContactFilterConfigCommandStatusTopic = "UMAA::SA::ContactFilterConfig::ContactFilterConfigCommandStatusType";

inline constexpr const char* GlobalPoseConfigCommandTopic = "UMAA::SA::GlobalPoseConfig::GlobalPoseConfigCommandType";
inline constexpr const char* GlobalPoseConfigAckTopic = "UMAA::SA::GlobalPoseConfig::GlobalPoseConfigAckReportType";
inline constexpr const char* GlobalPoseConfigCommandStatusTopic = "UMAA::SA::GlobalPoseConfig::GlobalPoseConfigCommandStatusType";

inline constexpr const char* AccelerationReportTopic = "UMAA::SA::AccelerationStatus::AccelerationReportType";
inline constexpr const char* CompartmentReportTopic = "UMAA::SA::CompartmentStatus::CompartmentReportType";
inline constexpr const char* CompartmentConfigReportTopic = "UMAA::SA::CompartmentConfig::CompartmentConfigReportType";
inline constexpr const char* ContactReportTopic = "UMAA::SA::ContactReport::ContactReportType";
inline constexpr const char* ContactCOLREGSClassificationReportTopic = "UMAA::SA::ContactCOLREGSClassificationStatus::ContactCOLREGSClassificationReportType";
inline constexpr const char* ContactCategoryReportTopic = "UMAA::SA::ContactCategoryReport::ContactCategoryReportType";
inline constexpr const char* ContactIdentityReportTopic = "UMAA::SA::ContactIdentityReport::ContactIdentityReportType";
inline constexpr const char* ContactVisualClassificationReportTopic = "UMAA::SA::ContactVisualClassificationStatus::ContactVisualClassificationReportType";
inline constexpr const char* DateTimeReportTopic = "UMAA::SA::DateTimeStatus::DateTimeReportType";
inline constexpr const char* ECEFPoseReportTopic = "UMAA::SA::ECEFPoseStatus::ECEFPoseReportType";
inline constexpr const char* GlobalPoseReportTopic = "UMAA::SA::GlobalPoseStatus::GlobalPoseReportType";
inline constexpr const char* GlobalPoseConfigReportTopic = "UMAA::SA::GlobalPoseConfig::GlobalPoseConfigReportType";
inline constexpr const char* LandmarkReportTopic = "UMAA::SA::LandmarkReport::LandmarkReportType";
inline constexpr const char* MagneticVariationReportTopic = "UMAA::SA::MagneticVariationStatus::MagneticVariationReportType";
inline constexpr const char* MagneticVariationSpecsReportTopic = "UMAA::SA::MagneticVariationSpecs::MagneticVariationSpecsReportType";
inline constexpr const char* OrientationReportTopic = "UMAA::SA::OrientationStatus::OrientationReportType";
inline constexpr const char* PassiveContactReportTopic = "UMAA::SA::PassiveContactReport::PassiveContactReportType";
inline constexpr const char* PathReporterReportTopic = "UMAA::SA::PathReporterStatus::PathReporterReportType";
inline constexpr const char* PathReporterSpecsReportTopic = "UMAA::SA::PathReporterSpecs::PathReporterSpecsReportType";
inline constexpr const char* RelativeContactReportTopic = "UMAA::SA::RelativeContactReport::RelativeContactReportType";
inline constexpr const char* SeaStateReportTopic = "UMAA::SA::SeaStateReport::SeaStateReportType";
inline constexpr const char* SoundVelocityProfileReportTopic = "UMAA::SA::SoundVelocityProfileReport::SoundVelocityProfileReportType";
inline constexpr const char* SpeedReportTopic = "UMAA::SA::SpeedStatus::SpeedReportType";
inline constexpr const char* StillImageReportTopic = "UMAA::SA::StillImageStatus::StillImageReportType";
inline constexpr const char* TerrainReportTopic = "UMAA::SA::TerrainReport::TerrainReportType";
inline constexpr const char* TranslationalShipMotionReportTopic = "UMAA::SA::TranslationalShipMotionStatus::TranslationalShipMotionReportType";
inline constexpr const char* VelocityReportTopic = "UMAA::SA::VelocityStatus::VelocityReportType";
inline constexpr const char* WaterCharacteristicsReportTopic = "UMAA::SA::WaterCharacteristicsStatus::WaterCharacteristicsReportType";
inline constexpr const char* WaterCurrentReportTopic = "UMAA::SA::WaterCurrentStatus::WaterCurrentReportType";
inline constexpr const char* WeatherReportTopic = "UMAA::SA::WeatherStatus::WeatherReportType";
inline constexpr const char* WindReportTopic = "UMAA::SA::WindStatus::WindReportType";

} // namespace umaa::sdk::topics::sa

#endif // UMAA_SDK_SERVICES_SA_HPP
