// Auto-generated by cpp/sdk/tools/generate_services.py — DO NOT EDIT
#ifndef UMAA_SDK_SERVICES_SEM_HPP
#define UMAA_SDK_SERVICES_SEM_HPP

#include "umaa/sdk/command_provider.hpp"
#include "umaa/sdk/command_consumer.hpp"
#include "umaa/sdk/report_provider.hpp"
#include "umaa/sdk/report_consumer.hpp"

#include "UMAA/SEM/FLSControl/FLSCommandType.hpp"
#include "UMAA/SEM/FLSControl/FLSCommandAckReportType.hpp"
#include "UMAA/SEM/FLSControl/FLSCommandStatusType.hpp"
#include "UMAA/SEM/FLSPreCalcControl/FLSPreCalcCommandType.hpp"
#include "UMAA/SEM/FLSPreCalcControl/FLSPreCalcCommandAckReportType.hpp"
#include "UMAA/SEM/FLSPreCalcControl/FLSPreCalcCommandStatusType.hpp"
#include "UMAA/SEM/IlluminatorControl/IlluminatorCommandType.hpp"
#include "UMAA/SEM/IlluminatorControl/IlluminatorCommandAckReportType.hpp"
#include "UMAA/SEM/IlluminatorControl/IlluminatorCommandStatusType.hpp"
#include "UMAA/SEM/InertialSensorControl/InertialSensorCommandType.hpp"
#include "UMAA/SEM/InertialSensorControl/InertialSensorCommandAckReportType.hpp"
#include "UMAA/SEM/InertialSensorControl/InertialSensorCommandStatusType.hpp"
#include "UMAA/SEM/MapSegmentControl/MapSegmentCommandType.hpp"
#include "UMAA/SEM/MapSegmentControl/MapSegmentCommandAckReportType.hpp"
#include "UMAA/SEM/MapSegmentControl/MapSegmentCommandStatusType.hpp"
#include "UMAA/SEM/SASControl/SASCommandType.hpp"
#include "UMAA/SEM/SASControl/SASCommandAckReportType.hpp"
#include "UMAA/SEM/SASControl/SASCommandStatusType.hpp"
#include "UMAA/SEM/SASConfig/SASConfigCommandType.hpp"
#include "UMAA/SEM/SASConfig/SASConfigAckReportType.hpp"
#include "UMAA/SEM/SASConfig/SASConfigCommandStatusType.hpp"
#include "UMAA/SEM/GPSStatus/GPSReportType.hpp"
#include "UMAA/SEM/IlluminatorStatus/IlluminatorReportType.hpp"
#include "UMAA/SEM/IlluminatorSpecs/IlluminatorSpecsReportType.hpp"
#include "UMAA/SEM/InertialSensorStatus/InertialSensorReportType.hpp"
#include "UMAA/SEM/SASConfig/SASConfigReportType.hpp"
#include "UMAA/SEM/SASStatus/SASStatusReportType.hpp"

namespace umaa::sdk::services::sem {

using FLSControlProvider = umaa::sdk::CommandProvider<
    UMAA::SEM::FLSControl::FLSCommandType,
    UMAA::SEM::FLSControl::FLSCommandAckReportType,
    UMAA::SEM::FLSControl::FLSCommandStatusType>;

using FLSControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SEM::FLSControl::FLSCommandType,
    UMAA::SEM::FLSControl::FLSCommandAckReportType,
    UMAA::SEM::FLSControl::FLSCommandStatusType>;

using FLSPreCalcControlProvider = umaa::sdk::CommandProvider<
    UMAA::SEM::FLSPreCalcControl::FLSPreCalcCommandType,
    UMAA::SEM::FLSPreCalcControl::FLSPreCalcCommandAckReportType,
    UMAA::SEM::FLSPreCalcControl::FLSPreCalcCommandStatusType>;

using FLSPreCalcControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SEM::FLSPreCalcControl::FLSPreCalcCommandType,
    UMAA::SEM::FLSPreCalcControl::FLSPreCalcCommandAckReportType,
    UMAA::SEM::FLSPreCalcControl::FLSPreCalcCommandStatusType>;

using IlluminatorControlProvider = umaa::sdk::CommandProvider<
    UMAA::SEM::IlluminatorControl::IlluminatorCommandType,
    UMAA::SEM::IlluminatorControl::IlluminatorCommandAckReportType,
    UMAA::SEM::IlluminatorControl::IlluminatorCommandStatusType>;

using IlluminatorControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SEM::IlluminatorControl::IlluminatorCommandType,
    UMAA::SEM::IlluminatorControl::IlluminatorCommandAckReportType,
    UMAA::SEM::IlluminatorControl::IlluminatorCommandStatusType>;

using InertialSensorControlProvider = umaa::sdk::CommandProvider<
    UMAA::SEM::InertialSensorControl::InertialSensorCommandType,
    UMAA::SEM::InertialSensorControl::InertialSensorCommandAckReportType,
    UMAA::SEM::InertialSensorControl::InertialSensorCommandStatusType>;

using InertialSensorControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SEM::InertialSensorControl::InertialSensorCommandType,
    UMAA::SEM::InertialSensorControl::InertialSensorCommandAckReportType,
    UMAA::SEM::InertialSensorControl::InertialSensorCommandStatusType>;

using MapSegmentControlProvider = umaa::sdk::CommandProvider<
    UMAA::SEM::MapSegmentControl::MapSegmentCommandType,
    UMAA::SEM::MapSegmentControl::MapSegmentCommandAckReportType,
    UMAA::SEM::MapSegmentControl::MapSegmentCommandStatusType>;

using MapSegmentControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SEM::MapSegmentControl::MapSegmentCommandType,
    UMAA::SEM::MapSegmentControl::MapSegmentCommandAckReportType,
    UMAA::SEM::MapSegmentControl::MapSegmentCommandStatusType>;

using SASControlProvider = umaa::sdk::CommandProvider<
    UMAA::SEM::SASControl::SASCommandType,
    UMAA::SEM::SASControl::SASCommandAckReportType,
    UMAA::SEM::SASControl::SASCommandStatusType>;

using SASControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SEM::SASControl::SASCommandType,
    UMAA::SEM::SASControl::SASCommandAckReportType,
    UMAA::SEM::SASControl::SASCommandStatusType>;

using SASConfigProvider = umaa::sdk::CommandProvider<
    UMAA::SEM::SASConfig::SASConfigCommandType,
    UMAA::SEM::SASConfig::SASConfigAckReportType,
    UMAA::SEM::SASConfig::SASConfigCommandStatusType>;

using SASConfigConsumer = umaa::sdk::CommandConsumer<
    UMAA::SEM::SASConfig::SASConfigCommandType,
    UMAA::SEM::SASConfig::SASConfigAckReportType,
    UMAA::SEM::SASConfig::SASConfigCommandStatusType>;

using GPSReportProvider = umaa::sdk::ReportProvider<UMAA::SEM::GPSStatus::GPSReportType>;
using GPSReportConsumer = umaa::sdk::ReportConsumer<UMAA::SEM::GPSStatus::GPSReportType>;

using IlluminatorReportProvider = umaa::sdk::ReportProvider<UMAA::SEM::IlluminatorStatus::IlluminatorReportType>;
using IlluminatorReportConsumer = umaa::sdk::ReportConsumer<UMAA::SEM::IlluminatorStatus::IlluminatorReportType>;

using IlluminatorSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::SEM::IlluminatorSpecs::IlluminatorSpecsReportType>;
using IlluminatorSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::SEM::IlluminatorSpecs::IlluminatorSpecsReportType>;

using InertialSensorReportProvider = umaa::sdk::ReportProvider<UMAA::SEM::InertialSensorStatus::InertialSensorReportType>;
using InertialSensorReportConsumer = umaa::sdk::ReportConsumer<UMAA::SEM::InertialSensorStatus::InertialSensorReportType>;

using SASConfigReportProvider = umaa::sdk::ReportProvider<UMAA::SEM::SASConfig::SASConfigReportType>;
using SASConfigReportConsumer = umaa::sdk::ReportConsumer<UMAA::SEM::SASConfig::SASConfigReportType>;

using SASStatusReportProvider = umaa::sdk::ReportProvider<UMAA::SEM::SASStatus::SASStatusReportType>;
using SASStatusReportConsumer = umaa::sdk::ReportConsumer<UMAA::SEM::SASStatus::SASStatusReportType>;

} // namespace umaa::sdk::services::sem

namespace umaa::sdk::topics::sem {

inline constexpr const char* FLSCommandTopic = "UMAA::SEM::FLSControl::FLSCommandType";
inline constexpr const char* FLSCommandAckTopic = "UMAA::SEM::FLSControl::FLSCommandAckReportType";
inline constexpr const char* FLSCommandStatusTopic = "UMAA::SEM::FLSControl::FLSCommandStatusType";

inline constexpr const char* FLSPreCalcCommandTopic = "UMAA::SEM::FLSPreCalcControl::FLSPreCalcCommandType";
inline constexpr const char* FLSPreCalcCommandAckTopic = "UMAA::SEM::FLSPreCalcControl::FLSPreCalcCommandAckReportType";
inline constexpr const char* FLSPreCalcCommandStatusTopic = "UMAA::SEM::FLSPreCalcControl::FLSPreCalcCommandStatusType";

inline constexpr const char* IlluminatorCommandTopic = "UMAA::SEM::IlluminatorControl::IlluminatorCommandType";
inline constexpr const char* IlluminatorCommandAckTopic = "UMAA::SEM::IlluminatorControl::IlluminatorCommandAckReportType";
inline constexpr const char* IlluminatorCommandStatusTopic = "UMAA::SEM::IlluminatorControl::IlluminatorCommandStatusType";

inline constexpr const char* InertialSensorCommandTopic = "UMAA::SEM::InertialSensorControl::InertialSensorCommandType";
inline constexpr const char* InertialSensorCommandAckTopic = "UMAA::SEM::InertialSensorControl::InertialSensorCommandAckReportType";
inline constexpr const char* InertialSensorCommandStatusTopic = "UMAA::SEM::InertialSensorControl::InertialSensorCommandStatusType";

inline constexpr const char* MapSegmentCommandTopic = "UMAA::SEM::MapSegmentControl::MapSegmentCommandType";
inline constexpr const char* MapSegmentCommandAckTopic = "UMAA::SEM::MapSegmentControl::MapSegmentCommandAckReportType";
inline constexpr const char* MapSegmentCommandStatusTopic = "UMAA::SEM::MapSegmentControl::MapSegmentCommandStatusType";

inline constexpr const char* SASCommandTopic = "UMAA::SEM::SASControl::SASCommandType";
inline constexpr const char* SASCommandAckTopic = "UMAA::SEM::SASControl::SASCommandAckReportType";
inline constexpr const char* SASCommandStatusTopic = "UMAA::SEM::SASControl::SASCommandStatusType";

inline constexpr const char* SASConfigCommandTopic = "UMAA::SEM::SASConfig::SASConfigCommandType";
inline constexpr const char* SASConfigAckTopic = "UMAA::SEM::SASConfig::SASConfigAckReportType";
inline constexpr const char* SASConfigCommandStatusTopic = "UMAA::SEM::SASConfig::SASConfigCommandStatusType";

inline constexpr const char* GPSReportTopic = "UMAA::SEM::GPSStatus::GPSReportType";
inline constexpr const char* IlluminatorReportTopic = "UMAA::SEM::IlluminatorStatus::IlluminatorReportType";
inline constexpr const char* IlluminatorSpecsReportTopic = "UMAA::SEM::IlluminatorSpecs::IlluminatorSpecsReportType";
inline constexpr const char* InertialSensorReportTopic = "UMAA::SEM::InertialSensorStatus::InertialSensorReportType";
inline constexpr const char* SASConfigReportTopic = "UMAA::SEM::SASConfig::SASConfigReportType";
inline constexpr const char* SASStatusReportTopic = "UMAA::SEM::SASStatus::SASStatusReportType";

} // namespace umaa::sdk::topics::sem

#endif // UMAA_SDK_SERVICES_SEM_HPP
