// Auto-generated by cpp/sdk/tools/generate_services.py — DO NOT EDIT
#ifndef UMAA_SDK_SERVICES_SO_HPP
#define UMAA_SDK_SERVICES_SO_HPP

#include "umaa/sdk/command_provider.hpp"
#include "umaa/sdk/command_consumer.hpp"
#include "umaa/sdk/report_provider.hpp"
#include "umaa/sdk/report_consumer.hpp"

#include "UMAA/SO/BITControl/BITCommandType.hpp"
#include "UMAA/SO/BITControl/BITCommandAckReportType.hpp"
#include "UMAA/SO/BITControl/BITCommandStatusType.hpp"
#include "UMAA/SO/BITControl/BITExecutionStatusReportType.hpp"
#include "UMAA/SO/BITConfig/BITConfigCommandType.hpp"
#include "UMAA/SO/BITConfig/BITConfigAckReportType.hpp"
#include "UMAA/SO/BITConfig/BITConfigCommandStatusType.hpp"
#include "UMAA/SO/ClearDataControl/ClearDataCommandType.hpp"
#include "UMAA/SO/ClearDataControl/ClearDataCommandAckReportType.hpp"
#include "UMAA/SO/ClearDataControl/ClearDataCommandStatusType.hpp"
#include "UMAA/SO/ControlSystemID/ControlSystemIDCommandType.hpp"
#include "UMAA/SO/ControlSystemID/ControlSystemIDCommandAckReportType.hpp"
#include "UMAA/SO/ControlSystemID/ControlSystemIDCommandStatusType.hpp"
#include "UMAA/SO/EmitterControl/EmitterCommandType.hpp"
#include "UMAA/SO/EmitterControl/EmitterCommandAckReportType.hpp"
#include "UMAA/SO/EmitterControl/EmitterCommandStatusType.hpp"
#include "UMAA/SO/EmitterPresetControl/EmitterPresetCommandType.hpp"
#include "UMAA/SO/EmitterPresetControl/EmitterPresetCommandAckReportType.hpp"
#include "UMAA/SO/EmitterPresetControl/EmitterPresetCommandStatusType.hpp"
#include "UMAA/SO/EmitterPresetConfig/EmitterPresetConfigCommandType.hpp"
#include "UMAA/SO/EmitterPresetConfig/EmitterPresetConfigAckReportType.hpp"
#include "UMAA/SO/EmitterPresetConfig/EmitterPresetConfigCommandStatusType.hpp"
#include "UMAA/SO/ResourceAllocation/ResourceAllocationCommandType.hpp"
#include "UMAA/SO/ResourceAllocation/ResourceAllocationCommandAckReportType.hpp"
#include "UMAA/SO/ResourceAllocation/ResourceAllocationCommandStatusType.hpp"
#include "UMAA/SO/ResourceAllocation/ResourceAllocationPriorityCommandType.hpp"
#include "UMAA/SO/ResourceAllocation/ResourceAllocationPriorityCommandAckReportType.hpp"
#include "UMAA/SO/ResourceAllocation/ResourceAllocationPriorityCommandStatusType.hpp"
#include "UMAA/SO/SyncDataControl/SyncDataCommandType.hpp"
#include "UMAA/SO/SyncDataControl/SyncDataCommandAckReportType.hpp"
#include "UMAA/SO/SyncDataControl/SyncDataCommandStatusType.hpp"
#include "UMAA/SO/TamperDetectionControl/TamperDetectionCommandType.hpp"
#include "UMAA/SO/TamperDetectionControl/TamperDetectionCommandAckReportType.hpp"
#include "UMAA/SO/TamperDetectionControl/TamperDetectionCommandStatusType.hpp"
#include "UMAA/SO/BITReport/BITReportType.hpp"
#include "UMAA/SO/BITConfig/BITConfigReportType.hpp"
#include "UMAA/SO/BITSpecs/BITSpecsReportType.hpp"
#include "UMAA/SO/ControlSystemID/ClientIDReportType.hpp"
#include "UMAA/SO/ControlSystemID/ControlSystemIDReportType.hpp"
#include "UMAA/SO/EmitterReport/EmitterReportType.hpp"
#include "UMAA/SO/EmitterPresetReport/EmitterPresetReportType.hpp"
#include "UMAA/SO/EmitterPresetConfig/EmitterPresetConfigReportType.hpp"
#include "UMAA/SO/EmitterSpecs/EmitterSpecsReportType.hpp"
#include "UMAA/SO/FileSystemStatus/FileSystemReportType.hpp"
#include "UMAA/SO/HealthReport/HealthReportType.hpp"
#include "UMAA/SO/HeartbeatPulseStatus/HeartbeatPulseReportType.hpp"
#include "UMAA/SO/LogReport/LogReportType.hpp"
#include "UMAA/SO/MemoryStatus/MemoryReportType.hpp"
#include "UMAA/SO/ProcessingUnitStatus/ProcessingUnitReportType.hpp"
#include "UMAA/SO/RecordingSpecs/RecordingSpecsReportType.hpp"
#include "UMAA/SO/RecordingStatus/RecordingStatusReportType.hpp"
#include "UMAA/SO/ResourceAllocation/ResourceAllocationReportType.hpp"
#include "UMAA/SO/ResourceAllocation/ResourceAllocationConfigReportType.hpp"
#include "UMAA/SO/ResourceAllocation/ResourceAllocationPriorityReportType.hpp"
#include "UMAA/SO/ResourceIdentification/ResourceAuthorizationReportType.hpp"
#include "UMAA/SO/ResourceIdentification/SubsystemIDReportType.hpp"
#include "UMAA/SO/TamperDetectionStatus/TamperDetectionReportType.hpp"
#include "UMAA/SO/ResourceIdentification/VehicleIDReportType.hpp"

namespace umaa::sdk::services::so {

using BITControlProvider = umaa::sdk::CommandProviderWithExec<
    UMAA::SO::BITControl::BITCommandType,
    UMAA::SO::BITControl::BITCommandAckReportType,
    UMAA::SO::BITControl::BITCommandStatusType,
    UMAA::SO::BITControl::BITExecutionStatusReportType>;

using BITControlConsumer = umaa::sdk::CommandConsumerWithExec<
    UMAA::SO::BITControl::BITCommandType,
    UMAA::SO::BITControl::BITCommandAckReportType,
    UMAA::SO::BITControl::BITCommandStatusType,
    UMAA::SO::BITControl::BITExecutionStatusReportType>;

using BITConfigProvider = umaa::sdk::CommandProvider<
    UMAA::SO::BITConfig::BITConfigCommandType,
    UMAA::SO::BITConfig::BITConfigAckReportType,
    UMAA::SO::BITConfig::BITConfigCommandStatusType>;

using BITConfigConsumer = umaa::sdk::CommandConsumer<
    UMAA::SO::BITConfig::BITConfigCommandType,
    UMAA::SO::BITConfig::BITConfigAckReportType,
    UMAA::SO::BITConfig::BITConfigCommandStatusType>;

using ClearDataControlProvider = umaa::sdk::CommandProvider<
    UMAA::SO::ClearDataControl::ClearDataCommandType,
    UMAA::SO::ClearDataControl::ClearDataCommandAckReportType,
    UMAA::SO::ClearDataControl::ClearDataCommandStatusType>;

using ClearDataControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SO::ClearDataControl::ClearDataCommandType,
    UMAA::SO::ClearDataControl::ClearDataCommandAckReportType,
    UMAA::SO::ClearDataControl::ClearDataCommandStatusType>;

using ControlSystemIDControlProvider = umaa::sdk::CommandProvider<
    UMAA::SO::ControlSystemID::ControlSystemIDCommandType,
    UMAA::SO::ControlSystemID::ControlSystemIDCommandAckReportType,
    UMAA::SO::ControlSystemID::ControlSystemIDCommandStatusType>;

using ControlSystemIDControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SO::ControlSystemID::ControlSystemIDCommandType,
    UMAA::SO::ControlSystemID::ControlSystemIDCommandAckReportType,
    UMAA::SO::ControlSystemID::ControlSystemIDCommandStatusType>;

using EmitterControlProvider = umaa::sdk::CommandProvider<
    UMAA::SO::EmitterControl::EmitterCommandType,
    UMAA::SO::EmitterControl::EmitterCommandAckReportType,
    UMAA::SO::EmitterControl::EmitterCommandStatusType>;

using EmitterControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SO::EmitterControl::EmitterCommandType,
    UMAA::SO::EmitterControl::EmitterCommandAckReportType,
    UMAA::SO::EmitterControl::EmitterCommandStatusType>;

using EmitterPresetControlProvider = umaa::sdk::CommandProvider<
    UMAA::SO::EmitterPresetControl::EmitterPresetCommandType,
    UMAA::SO::EmitterPresetControl::EmitterPresetCommandAckReportType,
    UMAA::SO::EmitterPresetControl::EmitterPresetCommandStatusType>;

using EmitterPresetControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SO::EmitterPresetControl::EmitterPresetCommandType,
    UMAA::SO::EmitterPresetControl::EmitterPresetCommandAckReportType,
    UMAA::SO::EmitterPresetControl::EmitterPresetCommandStatusType>;

using EmitterPresetConfigProvider = umaa::sdk::CommandProvider<
    UMAA::SO::EmitterPresetConfig::EmitterPresetConfigCommandType,
    UMAA::SO::EmitterPresetConfig::EmitterPresetConfigAckReportType,
    UMAA::SO::EmitterPresetConfig::EmitterPresetConfigCommandStatusType>;

using EmitterPresetConfigConsumer = umaa::sdk::CommandConsumer<
    UMAA::SO::EmitterPresetConfig::EmitterPresetConfigCommandType,
    UMAA::SO::EmitterPresetConfig::EmitterPresetConfigAckReportType,
    UMAA::SO::EmitterPresetConfig::EmitterPresetConfigCommandStatusType>;

using ResourceAllocationControlProvider = umaa::sdk::CommandProvider<
    UMAA::SO::ResourceAllocation::ResourceAllocationCommandType,
    UMAA::SO::ResourceAllocation::ResourceAllocationCommandAckReportType,
    UMAA::SO::ResourceAllocation::ResourceAllocationCommandStatusType>;

using ResourceAllocationControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SO::ResourceAllocation::ResourceAllocationCommandType,
    UMAA::SO::ResourceAllocation::ResourceAllocationCommandAckReportType,
    UMAA::SO::ResourceAllocation::ResourceAllocationCommandStatusType>;

using ResourceAllocationPriorityControlProvider = umaa::sdk::CommandProvider<
    UMAA::SO::ResourceAllocation::ResourceAllocationPriorityCommandType,
    UMAA::SO::ResourceAllocation::ResourceAllocationPriorityCommandAckReportType,
    UMAA::SO::ResourceAllocation::ResourceAllocationPriorityCommandStatusType>;

using ResourceAllocationPriorityControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SO::ResourceAllocation::ResourceAllocationPriorityCommandType,
    UMAA::SO::ResourceAllocation::ResourceAllocationPriorityCommandAckReportType,
    UMAA::SO::ResourceAllocation::ResourceAllocationPriorityCommandStatusType>;

using SyncDataControlProvider = umaa::sdk::CommandProvider<
    UMAA::SO::SyncDataControl::SyncDataCommandType,
    UMAA::SO::SyncDataControl::SyncDataCommandAckReportType,
    UMAA::SO::SyncDataControl::SyncDataCommandStatusType>;

using SyncDataControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SO::SyncDataControl::SyncDataCommandType,
    UMAA::SO::SyncDataControl::SyncDataCommandAckReportType,
    UMAA::SO::SyncDataControl::SyncDataCommandStatusType>;

using TamperDetectionControlProvider = umaa::sdk::CommandProvider<
    UMAA::SO::TamperDetectionControl::TamperDetectionCommandType,
    UMAA::SO::TamperDetectionControl::TamperDetectionCommandAckReportType,
    UMAA::SO::TamperDetectionControl::TamperDetectionCommandStatusType>;

using TamperDetectionControlConsumer = umaa::sdk::CommandConsumer<
    UMAA::SO::TamperDetectionControl::TamperDetectionCommandType,
    UMAA::SO::TamperDetectionControl::TamperDetectionCommandAckReportType,
    UMAA::SO::TamperDetectionControl::TamperDetectionCommandStatusType>;

using BITReportProvider = umaa::sdk::ReportProvider<UMAA::SO::BITReport::BITReportType>;
using BITReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::BITReport::BITReportType>;

using BITConfigReportProvider = umaa::sdk::ReportProvider<UMAA::SO::BITConfig::BITConfigReportType>;
using BITConfigReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::BITConfig::BITConfigReportType>;

using BITSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::SO::BITSpecs::BITSpecsReportType>;
using BITSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::BITSpecs::BITSpecsReportType>;

using ClientIDReportProvider = umaa::sdk::ReportProvider<UMAA::SO::ControlSystemID::ClientIDReportType>;
using ClientIDReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::ControlSystemID::ClientIDReportType>;

using ControlSystemIDReportProvider = umaa::sdk::ReportProvider<UMAA::SO::ControlSystemID::ControlSystemIDReportType>;
using ControlSystemIDReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::ControlSystemID::ControlSystemIDReportType>;

using EmitterReportProvider = umaa::sdk::ReportProvider<UMAA::SO::EmitterReport::EmitterReportType>;
using EmitterReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::EmitterReport::EmitterReportType>;

using EmitterPresetReportProvider = umaa::sdk::ReportProvider<UMAA::SO::EmitterPresetReport::EmitterPresetReportType>;
using EmitterPresetReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::EmitterPresetReport::EmitterPresetReportType>;

using EmitterPresetConfigReportProvider = umaa::sdk::ReportProvider<UMAA::SO::EmitterPresetConfig::EmitterPresetConfigReportType>;
using EmitterPresetConfigReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::EmitterPresetConfig::EmitterPresetConfigReportType>;

using EmitterSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::SO::EmitterSpecs::EmitterSpecsReportType>;
using EmitterSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::EmitterSpecs::EmitterSpecsReportType>;

using FileSystemReportProvider = umaa::sdk::ReportProvider<UMAA::SO::FileSystemStatus::FileSystemReportType>;
using FileSystemReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::FileSystemStatus::FileSystemReportType>;

using HealthReportProvider = umaa::sdk::ReportProvider<UMAA::SO::HealthReport::HealthReportType>;
using HealthReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::HealthReport::HealthReportType>;

using HeartbeatPulseReportProvider = umaa::sdk::ReportProvider<UMAA::SO::HeartbeatPulseStatus::HeartbeatPulseReportType>;
using HeartbeatPulseReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::HeartbeatPulseStatus::HeartbeatPulseReportType>;

using LogReportProvider = umaa::sdk::ReportProvider<UMAA::SO::LogReport::LogReportType>;
using LogReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::LogReport::LogReportType>;

using MemoryReportProvider = umaa::sdk::ReportProvider<UMAA::SO::MemoryStatus::MemoryReportType>;
using MemoryReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::MemoryStatus::MemoryReportType>;

using ProcessingUnitReportProvider = umaa::sdk::ReportProvider<UMAA::SO::ProcessingUnitStatus::ProcessingUnitReportType>;
using ProcessingUnitReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::ProcessingUnitStatus::ProcessingUnitReportType>;

using RecordingSpecsReportProvider = umaa::sdk::ReportProvider<UMAA::SO::RecordingSpecs::RecordingSpecsReportType>;
using RecordingSpecsReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::RecordingSpecs::RecordingSpecsReportType>;

using RecordingStatusReportProvider = umaa::sdk::ReportProvider<UMAA::SO::RecordingStatus::RecordingStatusReportType>;
using RecordingStatusReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::RecordingStatus::RecordingStatusReportType>;

using ResourceAllocationReportProvider = umaa::sdk::ReportProvider<UMAA::SO::ResourceAllocation::ResourceAllocationReportType>;
using ResourceAllocationReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::ResourceAllocation::ResourceAllocationReportType>;

using ResourceAllocationConfigReportProvider = umaa::sdk::ReportProvider<UMAA::SO::ResourceAllocation::ResourceAllocationConfigReportType>;
using ResourceAllocationConfigReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::ResourceAllocation::ResourceAllocationConfigReportType>;

using ResourceAllocationPriorityReportProvider = umaa::sdk::ReportProvider<UMAA::SO::ResourceAllocation::ResourceAllocationPriorityReportType>;
using ResourceAllocationPriorityReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::ResourceAllocation::ResourceAllocationPriorityReportType>;

using ResourceAuthorizationReportProvider = umaa::sdk::ReportProvider<UMAA::SO::ResourceIdentification::ResourceAuthorizationReportType>;
using ResourceAuthorizationReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::ResourceIdentification::ResourceAuthorizationReportType>;

using SubsystemIDReportProvider = umaa::sdk::ReportProvider<UMAA::SO::ResourceIdentification::SubsystemIDReportType>;
using SubsystemIDReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::ResourceIdentification::SubsystemIDReportType>;

using TamperDetectionReportProvider = umaa::sdk::ReportProvider<UMAA::SO::TamperDetectionStatus::TamperDetectionReportType>;
using TamperDetectionReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::TamperDetectionStatus::TamperDetectionReportType>;

using VehicleIDReportProvider = umaa::sdk::ReportProvider<UMAA::SO::ResourceIdentification::VehicleIDReportType>;
using VehicleIDReportConsumer = umaa::sdk::ReportConsumer<UMAA::SO::ResourceIdentification::VehicleIDReportType>;

} // namespace umaa::sdk::services::so

namespace umaa::sdk::topics::so {

inline constexpr const char* BITCommandTopic = "UMAA::SO::BITControl::BITCommandType";
inline constexpr const char* BITCommandAckTopic = "UMAA::SO::BITControl::BITCommandAckReportType";
inline constexpr const char* BITCommandStatusTopic = "UMAA::SO::BITControl::BITCommandStatusType";
inline constexpr const char* BITExecStatusTopic = "UMAA::SO::BITControl::BITExecutionStatusReportType";

inline constexpr const char* BITConfigCommandTopic = "UMAA::SO::BITConfig::BITConfigCommandType";
inline constexpr const char* BITConfigAckTopic = "UMAA::SO::BITConfig::BITConfigAckReportType";
inline constexpr const char* BITConfigCommandStatusTopic = "UMAA::SO::BITConfig::BITConfigCommandStatusType";

inline constexpr const char* ClearDataCommandTopic = "UMAA::SO::ClearDataControl::ClearDataCommandType";
inline constexpr const char* ClearDataCommandAckTopic = "UMAA::SO::ClearDataControl::ClearDataCommandAckReportType";
inline constexpr const char* ClearDataCommandStatusTopic = "UMAA::SO::ClearDataControl::ClearDataCommandStatusType";

inline constexpr const char* ControlSystemIDCommandTopic = "UMAA::SO::ControlSystemID::ControlSystemIDCommandType";
inline constexpr const char* ControlSystemIDCommandAckTopic = "UMAA::SO::ControlSystemID::ControlSystemIDCommandAckReportType";
inline constexpr const char* ControlSystemIDCommandStatusTopic = "UMAA::SO::ControlSystemID::ControlSystemIDCommandStatusType";

inline constexpr const char* EmitterCommandTopic = "UMAA::SO::EmitterControl::EmitterCommandType";
inline constexpr const char* EmitterCommandAckTopic = "UMAA::SO::EmitterControl::EmitterCommandAckReportType";
inline constexpr const char* EmitterCommandStatusTopic = "UMAA::SO::EmitterControl::EmitterCommandStatusType";

inline constexpr const char* EmitterPresetCommandTopic = "UMAA::SO::EmitterPresetControl::EmitterPresetCommandType";
inline constexpr const char* EmitterPresetCommandAckTopic = "UMAA::SO::EmitterPresetControl::EmitterPresetCommandAckReportType";
inline constexpr const char* EmitterPresetCommandStatusTopic = "UMAA::SO::EmitterPresetControl::EmitterPresetCommandStatusType";

inline constexpr const char* EmitterPresetConfigCommandTopic = "UMAA::SO::EmitterPresetConfig::EmitterPresetConfigCommandType";
inline constexpr const char* EmitterPresetConfigAckTopic = "UMAA::SO::EmitterPresetConfig::EmitterPresetConfigAckReportType";
inline constexpr const char* EmitterPresetConfigCommandStatusTopic = "UMAA::SO::EmitterPresetConfig::EmitterPresetConfigCommandStatusType";

inline constexpr const char* ResourceAllocationCommandTopic = "UMAA::SO::ResourceAllocation::ResourceAllocationCommandType";
inline constexpr const char* ResourceAllocationCommandAckTopic = "UMAA::SO::ResourceAllocation::ResourceAllocationCommandAckReportType";
inline constexpr const char* ResourceAllocationCommandStatusTopic = "UMAA::SO::ResourceAllocation::ResourceAllocationCommandStatusType";

inline constexpr const char* ResourceAllocationPriorityCommandTopic = "UMAA::SO::ResourceAllocation::ResourceAllocationPriorityCommandType";
inline constexpr const char* ResourceAllocationPriorityCommandAckTopic = "UMAA::SO::ResourceAllocation::ResourceAllocationPriorityCommandAckReportType";
inline constexpr const char* ResourceAllocationPriorityCommandStatusTopic = "UMAA::SO::ResourceAllocation::ResourceAllocationPriorityCommandStatusType";

inline constexpr const char* SyncDataCommandTopic = "UMAA::SO::SyncDataControl::SyncDataCommandType";
inline constexpr const char* SyncDataCommandAckTopic = "UMAA::SO::SyncDataControl::SyncDataCommandAckReportType";
inline constexpr const char* SyncDataCommandStatusTopic = "UMAA::SO::SyncDataControl::SyncDataCommandStatusType";

inline constexpr const char* TamperDetectionCommandTopic = "UMAA::SO::TamperDetectionControl::TamperDetectionCommandType";
inline constexpr const char* TamperDetectionCommandAckTopic = "UMAA::SO::TamperDetectionControl::TamperDetectionCommandAckReportType";
inline constexpr const char* TamperDetectionCommandStatusTopic = "UMAA::SO::TamperDetectionControl::TamperDetectionCommandStatusType";

inline constexpr const char* BITReportTopic = "UMAA::SO::BITReport::BITReportType";
inline constexpr const char* BITConfigReportTopic = "UMAA::SO::BITConfig::BITConfigReportType";
inline constexpr const char* BITSpecsReportTopic = "UMAA::SO::BITSpecs::BITSpecsReportType";
inline constexpr const char* ClientIDReportTopic = "UMAA::SO::ControlSystemID::ClientIDReportType";
inline constexpr const char* ControlSystemIDReportTopic = "UMAA::SO::ControlSystemID::ControlSystemIDReportType";
inline constexpr const char* EmitterReportTopic = "UMAA::SO::EmitterReport::EmitterReportType";
inline constexpr const char* EmitterPresetReportTopic = "UMAA::SO::EmitterPresetReport::EmitterPresetReportType";
inline constexpr const char* EmitterPresetConfigReportTopic = "UMAA::SO::EmitterPresetConfig::EmitterPresetConfigReportType";
inline constexpr const char* EmitterSpecsReportTopic = "UMAA::SO::EmitterSpecs::EmitterSpecsReportType";
inline constexpr const char* FileSystemReportTopic = "UMAA::SO::FileSystemStatus::FileSystemReportType";
inline constexpr const char* HealthReportTopic = "UMAA::SO::HealthReport::HealthReportType";
inline constexpr const char* HeartbeatPulseReportTopic = "UMAA::SO::HeartbeatPulseStatus::HeartbeatPulseReportType";
inline constexpr const char* LogReportTopic = "UMAA::SO::LogReport::LogReportType";
inline constexpr const char* MemoryReportTopic = "UMAA::SO::MemoryStatus::MemoryReportType";
inline constexpr const char* ProcessingUnitReportTopic = "UMAA::SO::ProcessingUnitStatus::ProcessingUnitReportType";
inline constexpr const char* RecordingSpecsReportTopic = "UMAA::SO::RecordingSpecs::RecordingSpecsReportType";
inline constexpr const char* RecordingStatusReportTopic = "UMAA::SO::RecordingStatus::RecordingStatusReportType";
inline constexpr const char* ResourceAllocationReportTopic = "UMAA::SO::ResourceAllocation::ResourceAllocationReportType";
inline constexpr const char* ResourceAllocationConfigReportTopic = "UMAA::SO::ResourceAllocation::ResourceAllocationConfigReportType";
inline constexpr const char* ResourceAllocationPriorityReportTopic = "UMAA::SO::ResourceAllocation::ResourceAllocationPriorityReportType";
inline constexpr const char* ResourceAuthorizationReportTopic = "UMAA::SO::ResourceIdentification::ResourceAuthorizationReportType";
inline constexpr const char* SubsystemIDReportTopic = "UMAA::SO::ResourceIdentification::SubsystemIDReportType";
inline constexpr const char* TamperDetectionReportTopic = "UMAA::SO::TamperDetectionStatus::TamperDetectionReportType";
inline constexpr const char* VehicleIDReportTopic = "UMAA::SO::ResourceIdentification::VehicleIDReportType";

} // namespace umaa::sdk::topics::so

#endif // UMAA_SDK_SERVICES_SO_HPP
