"""rtiumaapy.services.eo — Engineering/Operations service classes.

Auto-generated by tools/generate_services.py. Do not edit manually.
"""

from __future__ import annotations
from typing import Optional

from rtiumaapy.command_provider import CommandProvider
from rtiumaapy.command_consumer import CommandConsumer
from rtiumaapy.report_provider import ReportProvider
from rtiumaapy.report_consumer import ReportConsumer
from rtiumaapy.dds_context import DDSContext

__all__ = [
    "AnchorControlConsumer",
    "AnchorControlProvider",
    "AnchorReportConsumer",
    "AnchorReportProvider",
    "AnchorSpecsReportConsumer",
    "AnchorSpecsReportProvider",
    "BallastPumpControlConsumer",
    "BallastPumpControlProvider",
    "BallastPumpReportConsumer",
    "BallastPumpReportProvider",
    "BallastPumpSpecsReportConsumer",
    "BallastPumpSpecsReportProvider",
    "BallastTankControlConsumer",
    "BallastTankControlProvider",
    "BallastTankReportConsumer",
    "BallastTankReportProvider",
    "BallastTankSpecsReportConsumer",
    "BallastTankSpecsReportProvider",
    "BatteryReportConsumer",
    "BatteryReportProvider",
    "BatterySpecsReportConsumer",
    "BatterySpecsReportProvider",
    "BilgePumpReportConsumer",
    "BilgePumpReportProvider",
    "EngineControlConsumer",
    "EngineControlProvider",
    "EngineReportConsumer",
    "EngineReportProvider",
    "EngineSpecsReportConsumer",
    "EngineSpecsReportProvider",
    "FinsControlConsumer",
    "FinsControlProvider",
    "FinsSpecsReportConsumer",
    "FinsSpecsReportProvider",
    "FuelTankReportConsumer",
    "FuelTankReportProvider",
    "FuelTankSpecsReportConsumer",
    "FuelTankSpecsReportProvider",
    "GeneratorReportConsumer",
    "GeneratorReportProvider",
    "GeneratorSpecsReportConsumer",
    "GeneratorSpecsReportProvider",
    "MastControlConsumer",
    "MastControlProvider",
    "MastReportConsumer",
    "MastReportProvider",
    "PowerControlConsumer",
    "PowerControlProvider",
    "PowerReportConsumer",
    "PowerReportProvider",
    "PropulsorsControlConsumer",
    "PropulsorsControlProvider",
    "PropulsorsSpecsReportConsumer",
    "PropulsorsSpecsReportProvider",
    "UVPlatformCapabilitiesReportConsumer",
    "UVPlatformCapabilitiesReportProvider",
    "UVPlatformSpecsReportConsumer",
    "UVPlatformSpecsReportProvider",
]

from rtiumaapy.datamodel.AnchorCommandType import (
    UMAA_EO_AnchorControl_AnchorCommandType,
    UMAA_EO_AnchorControl_AnchorCommandTypeTopic,
)
from rtiumaapy.datamodel.AnchorCommandAckReportType import (
    UMAA_EO_AnchorControl_AnchorCommandAckReportType,
    UMAA_EO_AnchorControl_AnchorCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.AnchorCommandStatusType import (
    UMAA_EO_AnchorControl_AnchorCommandStatusType,
    UMAA_EO_AnchorControl_AnchorCommandStatusTypeTopic,
)


class AnchorControlProvider(CommandProvider):
    """Anchor command provider (EO::AnchorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="AnchorProvider",
            command_type=UMAA_EO_AnchorControl_AnchorCommandType,
            command_topic=UMAA_EO_AnchorControl_AnchorCommandTypeTopic,
            ack_type=UMAA_EO_AnchorControl_AnchorCommandAckReportType,
            ack_topic=UMAA_EO_AnchorControl_AnchorCommandAckReportTypeTopic,
            status_type=UMAA_EO_AnchorControl_AnchorCommandStatusType,
            status_topic=UMAA_EO_AnchorControl_AnchorCommandStatusTypeTopic,
            source_id=source_id,
        )


class AnchorControlConsumer(CommandConsumer):
    """Anchor command consumer (EO::AnchorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="AnchorConsumer",
            command_type=UMAA_EO_AnchorControl_AnchorCommandType,
            command_topic=UMAA_EO_AnchorControl_AnchorCommandTypeTopic,
            ack_type=UMAA_EO_AnchorControl_AnchorCommandAckReportType,
            ack_topic=UMAA_EO_AnchorControl_AnchorCommandAckReportTypeTopic,
            status_type=UMAA_EO_AnchorControl_AnchorCommandStatusType,
            status_topic=UMAA_EO_AnchorControl_AnchorCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.BallastPumpCommandType import (
    UMAA_EO_BallastTank_BallastPumpCommandType,
    UMAA_EO_BallastTank_BallastPumpCommandTypeTopic,
)
from rtiumaapy.datamodel.BallastPumpCommandAckReportType import (
    UMAA_EO_BallastTank_BallastPumpCommandAckReportType,
    UMAA_EO_BallastTank_BallastPumpCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.BallastPumpCommandStatusType import (
    UMAA_EO_BallastTank_BallastPumpCommandStatusType,
    UMAA_EO_BallastTank_BallastPumpCommandStatusTypeTopic,
)


class BallastPumpControlProvider(CommandProvider):
    """BallastPump command provider (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="BallastPumpProvider",
            command_type=UMAA_EO_BallastTank_BallastPumpCommandType,
            command_topic=UMAA_EO_BallastTank_BallastPumpCommandTypeTopic,
            ack_type=UMAA_EO_BallastTank_BallastPumpCommandAckReportType,
            ack_topic=UMAA_EO_BallastTank_BallastPumpCommandAckReportTypeTopic,
            status_type=UMAA_EO_BallastTank_BallastPumpCommandStatusType,
            status_topic=UMAA_EO_BallastTank_BallastPumpCommandStatusTypeTopic,
            source_id=source_id,
        )


class BallastPumpControlConsumer(CommandConsumer):
    """BallastPump command consumer (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="BallastPumpConsumer",
            command_type=UMAA_EO_BallastTank_BallastPumpCommandType,
            command_topic=UMAA_EO_BallastTank_BallastPumpCommandTypeTopic,
            ack_type=UMAA_EO_BallastTank_BallastPumpCommandAckReportType,
            ack_topic=UMAA_EO_BallastTank_BallastPumpCommandAckReportTypeTopic,
            status_type=UMAA_EO_BallastTank_BallastPumpCommandStatusType,
            status_topic=UMAA_EO_BallastTank_BallastPumpCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.BallastTankCommandType import (
    UMAA_EO_BallastTank_BallastTankCommandType,
    UMAA_EO_BallastTank_BallastTankCommandTypeTopic,
)
from rtiumaapy.datamodel.BallastTankCommandAckReportType import (
    UMAA_EO_BallastTank_BallastTankCommandAckReportType,
    UMAA_EO_BallastTank_BallastTankCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.BallastTankCommandStatusType import (
    UMAA_EO_BallastTank_BallastTankCommandStatusType,
    UMAA_EO_BallastTank_BallastTankCommandStatusTypeTopic,
)


class BallastTankControlProvider(CommandProvider):
    """BallastTank command provider (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="BallastTankProvider",
            command_type=UMAA_EO_BallastTank_BallastTankCommandType,
            command_topic=UMAA_EO_BallastTank_BallastTankCommandTypeTopic,
            ack_type=UMAA_EO_BallastTank_BallastTankCommandAckReportType,
            ack_topic=UMAA_EO_BallastTank_BallastTankCommandAckReportTypeTopic,
            status_type=UMAA_EO_BallastTank_BallastTankCommandStatusType,
            status_topic=UMAA_EO_BallastTank_BallastTankCommandStatusTypeTopic,
            source_id=source_id,
        )


class BallastTankControlConsumer(CommandConsumer):
    """BallastTank command consumer (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="BallastTankConsumer",
            command_type=UMAA_EO_BallastTank_BallastTankCommandType,
            command_topic=UMAA_EO_BallastTank_BallastTankCommandTypeTopic,
            ack_type=UMAA_EO_BallastTank_BallastTankCommandAckReportType,
            ack_topic=UMAA_EO_BallastTank_BallastTankCommandAckReportTypeTopic,
            status_type=UMAA_EO_BallastTank_BallastTankCommandStatusType,
            status_topic=UMAA_EO_BallastTank_BallastTankCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.EngineCommandType import (
    UMAA_EO_EngineControl_EngineCommandType,
    UMAA_EO_EngineControl_EngineCommandTypeTopic,
)
from rtiumaapy.datamodel.EngineCommandAckReportType import (
    UMAA_EO_EngineControl_EngineCommandAckReportType,
    UMAA_EO_EngineControl_EngineCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.EngineCommandStatusType import (
    UMAA_EO_EngineControl_EngineCommandStatusType,
    UMAA_EO_EngineControl_EngineCommandStatusTypeTopic,
)


class EngineControlProvider(CommandProvider):
    """Engine command provider (EO::EngineControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="EngineProvider",
            command_type=UMAA_EO_EngineControl_EngineCommandType,
            command_topic=UMAA_EO_EngineControl_EngineCommandTypeTopic,
            ack_type=UMAA_EO_EngineControl_EngineCommandAckReportType,
            ack_topic=UMAA_EO_EngineControl_EngineCommandAckReportTypeTopic,
            status_type=UMAA_EO_EngineControl_EngineCommandStatusType,
            status_topic=UMAA_EO_EngineControl_EngineCommandStatusTypeTopic,
            source_id=source_id,
        )


class EngineControlConsumer(CommandConsumer):
    """Engine command consumer (EO::EngineControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="EngineConsumer",
            command_type=UMAA_EO_EngineControl_EngineCommandType,
            command_topic=UMAA_EO_EngineControl_EngineCommandTypeTopic,
            ack_type=UMAA_EO_EngineControl_EngineCommandAckReportType,
            ack_topic=UMAA_EO_EngineControl_EngineCommandAckReportTypeTopic,
            status_type=UMAA_EO_EngineControl_EngineCommandStatusType,
            status_topic=UMAA_EO_EngineControl_EngineCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.FinsCommandType import (
    UMAA_EO_FinsControl_FinsCommandType,
    UMAA_EO_FinsControl_FinsCommandTypeTopic,
)
from rtiumaapy.datamodel.FinsCommandAckReportType import (
    UMAA_EO_FinsControl_FinsCommandAckReportType,
    UMAA_EO_FinsControl_FinsCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.FinsCommandStatusType import (
    UMAA_EO_FinsControl_FinsCommandStatusType,
    UMAA_EO_FinsControl_FinsCommandStatusTypeTopic,
)


class FinsControlProvider(CommandProvider):
    """Fins command provider (EO::FinsControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="FinsProvider",
            command_type=UMAA_EO_FinsControl_FinsCommandType,
            command_topic=UMAA_EO_FinsControl_FinsCommandTypeTopic,
            ack_type=UMAA_EO_FinsControl_FinsCommandAckReportType,
            ack_topic=UMAA_EO_FinsControl_FinsCommandAckReportTypeTopic,
            status_type=UMAA_EO_FinsControl_FinsCommandStatusType,
            status_topic=UMAA_EO_FinsControl_FinsCommandStatusTypeTopic,
            source_id=source_id,
        )


class FinsControlConsumer(CommandConsumer):
    """Fins command consumer (EO::FinsControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="FinsConsumer",
            command_type=UMAA_EO_FinsControl_FinsCommandType,
            command_topic=UMAA_EO_FinsControl_FinsCommandTypeTopic,
            ack_type=UMAA_EO_FinsControl_FinsCommandAckReportType,
            ack_topic=UMAA_EO_FinsControl_FinsCommandAckReportTypeTopic,
            status_type=UMAA_EO_FinsControl_FinsCommandStatusType,
            status_topic=UMAA_EO_FinsControl_FinsCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MastCommandType import (
    UMAA_EO_MastControl_MastCommandType,
    UMAA_EO_MastControl_MastCommandTypeTopic,
)
from rtiumaapy.datamodel.MastCommandAckReportType import (
    UMAA_EO_MastControl_MastCommandAckReportType,
    UMAA_EO_MastControl_MastCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MastCommandStatusType import (
    UMAA_EO_MastControl_MastCommandStatusType,
    UMAA_EO_MastControl_MastCommandStatusTypeTopic,
)


class MastControlProvider(CommandProvider):
    """Mast command provider (EO::MastControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MastProvider",
            command_type=UMAA_EO_MastControl_MastCommandType,
            command_topic=UMAA_EO_MastControl_MastCommandTypeTopic,
            ack_type=UMAA_EO_MastControl_MastCommandAckReportType,
            ack_topic=UMAA_EO_MastControl_MastCommandAckReportTypeTopic,
            status_type=UMAA_EO_MastControl_MastCommandStatusType,
            status_topic=UMAA_EO_MastControl_MastCommandStatusTypeTopic,
            source_id=source_id,
        )


class MastControlConsumer(CommandConsumer):
    """Mast command consumer (EO::MastControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MastConsumer",
            command_type=UMAA_EO_MastControl_MastCommandType,
            command_topic=UMAA_EO_MastControl_MastCommandTypeTopic,
            ack_type=UMAA_EO_MastControl_MastCommandAckReportType,
            ack_topic=UMAA_EO_MastControl_MastCommandAckReportTypeTopic,
            status_type=UMAA_EO_MastControl_MastCommandStatusType,
            status_topic=UMAA_EO_MastControl_MastCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.PowerCommandType import (
    UMAA_EO_PowerControl_PowerCommandType,
    UMAA_EO_PowerControl_PowerCommandTypeTopic,
)
from rtiumaapy.datamodel.PowerCommandAckReportType import (
    UMAA_EO_PowerControl_PowerCommandAckReportType,
    UMAA_EO_PowerControl_PowerCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.PowerCommandStatusType import (
    UMAA_EO_PowerControl_PowerCommandStatusType,
    UMAA_EO_PowerControl_PowerCommandStatusTypeTopic,
)


class PowerControlProvider(CommandProvider):
    """Power command provider (EO::PowerControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="PowerProvider",
            command_type=UMAA_EO_PowerControl_PowerCommandType,
            command_topic=UMAA_EO_PowerControl_PowerCommandTypeTopic,
            ack_type=UMAA_EO_PowerControl_PowerCommandAckReportType,
            ack_topic=UMAA_EO_PowerControl_PowerCommandAckReportTypeTopic,
            status_type=UMAA_EO_PowerControl_PowerCommandStatusType,
            status_topic=UMAA_EO_PowerControl_PowerCommandStatusTypeTopic,
            source_id=source_id,
        )


class PowerControlConsumer(CommandConsumer):
    """Power command consumer (EO::PowerControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="PowerConsumer",
            command_type=UMAA_EO_PowerControl_PowerCommandType,
            command_topic=UMAA_EO_PowerControl_PowerCommandTypeTopic,
            ack_type=UMAA_EO_PowerControl_PowerCommandAckReportType,
            ack_topic=UMAA_EO_PowerControl_PowerCommandAckReportTypeTopic,
            status_type=UMAA_EO_PowerControl_PowerCommandStatusType,
            status_topic=UMAA_EO_PowerControl_PowerCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.PropulsorsCommandType import (
    UMAA_EO_PropulsorsControl_PropulsorsCommandType,
    UMAA_EO_PropulsorsControl_PropulsorsCommandTypeTopic,
)
from rtiumaapy.datamodel.PropulsorsCommandAckReportType import (
    UMAA_EO_PropulsorsControl_PropulsorsCommandAckReportType,
    UMAA_EO_PropulsorsControl_PropulsorsCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.PropulsorsCommandStatusType import (
    UMAA_EO_PropulsorsControl_PropulsorsCommandStatusType,
    UMAA_EO_PropulsorsControl_PropulsorsCommandStatusTypeTopic,
)


class PropulsorsControlProvider(CommandProvider):
    """Propulsors command provider (EO::PropulsorsControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="PropulsorsProvider",
            command_type=UMAA_EO_PropulsorsControl_PropulsorsCommandType,
            command_topic=UMAA_EO_PropulsorsControl_PropulsorsCommandTypeTopic,
            ack_type=UMAA_EO_PropulsorsControl_PropulsorsCommandAckReportType,
            ack_topic=UMAA_EO_PropulsorsControl_PropulsorsCommandAckReportTypeTopic,
            status_type=UMAA_EO_PropulsorsControl_PropulsorsCommandStatusType,
            status_topic=UMAA_EO_PropulsorsControl_PropulsorsCommandStatusTypeTopic,
            source_id=source_id,
        )


class PropulsorsControlConsumer(CommandConsumer):
    """Propulsors command consumer (EO::PropulsorsControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="PropulsorsConsumer",
            command_type=UMAA_EO_PropulsorsControl_PropulsorsCommandType,
            command_topic=UMAA_EO_PropulsorsControl_PropulsorsCommandTypeTopic,
            ack_type=UMAA_EO_PropulsorsControl_PropulsorsCommandAckReportType,
            ack_topic=UMAA_EO_PropulsorsControl_PropulsorsCommandAckReportTypeTopic,
            status_type=UMAA_EO_PropulsorsControl_PropulsorsCommandStatusType,
            status_topic=UMAA_EO_PropulsorsControl_PropulsorsCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.AnchorReportType import (
    UMAA_EO_AnchorStatus_AnchorReportType,
    UMAA_EO_AnchorStatus_AnchorReportTypeTopic,
)


class AnchorReportProvider(ReportProvider):
    """Anchor report provider (EO::AnchorStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_AnchorStatus_AnchorReportType,
            report_topic=UMAA_EO_AnchorStatus_AnchorReportTypeTopic,
        )


class AnchorReportConsumer(ReportConsumer):
    """Anchor report consumer (EO::AnchorStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_AnchorStatus_AnchorReportType,
            report_topic=UMAA_EO_AnchorStatus_AnchorReportTypeTopic,
        )

from rtiumaapy.datamodel.AnchorSpecsReportType import (
    UMAA_EO_AnchorSpecs_AnchorSpecsReportType,
    UMAA_EO_AnchorSpecs_AnchorSpecsReportTypeTopic,
)


class AnchorSpecsReportProvider(ReportProvider):
    """AnchorSpecs report provider (EO::AnchorSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_AnchorSpecs_AnchorSpecsReportType,
            report_topic=UMAA_EO_AnchorSpecs_AnchorSpecsReportTypeTopic,
        )


class AnchorSpecsReportConsumer(ReportConsumer):
    """AnchorSpecs report consumer (EO::AnchorSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_AnchorSpecs_AnchorSpecsReportType,
            report_topic=UMAA_EO_AnchorSpecs_AnchorSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.BallastPumpReportType import (
    UMAA_EO_BallastTank_BallastPumpReportType,
    UMAA_EO_BallastTank_BallastPumpReportTypeTopic,
)


class BallastPumpReportProvider(ReportProvider):
    """BallastPump report provider (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BallastTank_BallastPumpReportType,
            report_topic=UMAA_EO_BallastTank_BallastPumpReportTypeTopic,
        )


class BallastPumpReportConsumer(ReportConsumer):
    """BallastPump report consumer (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BallastTank_BallastPumpReportType,
            report_topic=UMAA_EO_BallastTank_BallastPumpReportTypeTopic,
        )

from rtiumaapy.datamodel.BallastPumpSpecsReportType import (
    UMAA_EO_BallastTank_BallastPumpSpecsReportType,
    UMAA_EO_BallastTank_BallastPumpSpecsReportTypeTopic,
)


class BallastPumpSpecsReportProvider(ReportProvider):
    """BallastPumpSpecs report provider (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BallastTank_BallastPumpSpecsReportType,
            report_topic=UMAA_EO_BallastTank_BallastPumpSpecsReportTypeTopic,
        )


class BallastPumpSpecsReportConsumer(ReportConsumer):
    """BallastPumpSpecs report consumer (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BallastTank_BallastPumpSpecsReportType,
            report_topic=UMAA_EO_BallastTank_BallastPumpSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.BallastTankReportType import (
    UMAA_EO_BallastTank_BallastTankReportType,
    UMAA_EO_BallastTank_BallastTankReportTypeTopic,
)


class BallastTankReportProvider(ReportProvider):
    """BallastTank report provider (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BallastTank_BallastTankReportType,
            report_topic=UMAA_EO_BallastTank_BallastTankReportTypeTopic,
        )


class BallastTankReportConsumer(ReportConsumer):
    """BallastTank report consumer (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BallastTank_BallastTankReportType,
            report_topic=UMAA_EO_BallastTank_BallastTankReportTypeTopic,
        )

from rtiumaapy.datamodel.BallastTankSpecsReportType import (
    UMAA_EO_BallastTank_BallastTankSpecsReportType,
    UMAA_EO_BallastTank_BallastTankSpecsReportTypeTopic,
)


class BallastTankSpecsReportProvider(ReportProvider):
    """BallastTankSpecs report provider (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BallastTank_BallastTankSpecsReportType,
            report_topic=UMAA_EO_BallastTank_BallastTankSpecsReportTypeTopic,
        )


class BallastTankSpecsReportConsumer(ReportConsumer):
    """BallastTankSpecs report consumer (EO::BallastTank)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BallastTank_BallastTankSpecsReportType,
            report_topic=UMAA_EO_BallastTank_BallastTankSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.BatteryReportType import (
    UMAA_EO_BatteryStatus_BatteryReportType,
    UMAA_EO_BatteryStatus_BatteryReportTypeTopic,
)


class BatteryReportProvider(ReportProvider):
    """Battery report provider (EO::BatteryStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BatteryStatus_BatteryReportType,
            report_topic=UMAA_EO_BatteryStatus_BatteryReportTypeTopic,
        )


class BatteryReportConsumer(ReportConsumer):
    """Battery report consumer (EO::BatteryStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BatteryStatus_BatteryReportType,
            report_topic=UMAA_EO_BatteryStatus_BatteryReportTypeTopic,
        )

from rtiumaapy.datamodel.BatterySpecsReportType import (
    UMAA_EO_BatterySpecs_BatterySpecsReportType,
    UMAA_EO_BatterySpecs_BatterySpecsReportTypeTopic,
)


class BatterySpecsReportProvider(ReportProvider):
    """BatterySpecs report provider (EO::BatterySpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BatterySpecs_BatterySpecsReportType,
            report_topic=UMAA_EO_BatterySpecs_BatterySpecsReportTypeTopic,
        )


class BatterySpecsReportConsumer(ReportConsumer):
    """BatterySpecs report consumer (EO::BatterySpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BatterySpecs_BatterySpecsReportType,
            report_topic=UMAA_EO_BatterySpecs_BatterySpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.BilgePumpReportType import (
    UMAA_EO_BilgePumpStatus_BilgePumpReportType,
    UMAA_EO_BilgePumpStatus_BilgePumpReportTypeTopic,
)


class BilgePumpReportProvider(ReportProvider):
    """BilgePump report provider (EO::BilgePumpStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BilgePumpStatus_BilgePumpReportType,
            report_topic=UMAA_EO_BilgePumpStatus_BilgePumpReportTypeTopic,
        )


class BilgePumpReportConsumer(ReportConsumer):
    """BilgePump report consumer (EO::BilgePumpStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_BilgePumpStatus_BilgePumpReportType,
            report_topic=UMAA_EO_BilgePumpStatus_BilgePumpReportTypeTopic,
        )

from rtiumaapy.datamodel.EngineReportType import (
    UMAA_EO_EngineStatus_EngineReportType,
    UMAA_EO_EngineStatus_EngineReportTypeTopic,
)


class EngineReportProvider(ReportProvider):
    """Engine report provider (EO::EngineStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_EngineStatus_EngineReportType,
            report_topic=UMAA_EO_EngineStatus_EngineReportTypeTopic,
        )


class EngineReportConsumer(ReportConsumer):
    """Engine report consumer (EO::EngineStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_EngineStatus_EngineReportType,
            report_topic=UMAA_EO_EngineStatus_EngineReportTypeTopic,
        )

from rtiumaapy.datamodel.EngineSpecsReportType import (
    UMAA_EO_EngineSpecs_EngineSpecsReportType,
    UMAA_EO_EngineSpecs_EngineSpecsReportTypeTopic,
)


class EngineSpecsReportProvider(ReportProvider):
    """EngineSpecs report provider (EO::EngineSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_EngineSpecs_EngineSpecsReportType,
            report_topic=UMAA_EO_EngineSpecs_EngineSpecsReportTypeTopic,
        )


class EngineSpecsReportConsumer(ReportConsumer):
    """EngineSpecs report consumer (EO::EngineSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_EngineSpecs_EngineSpecsReportType,
            report_topic=UMAA_EO_EngineSpecs_EngineSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.FinsSpecsReportType import (
    UMAA_EO_FinsSpecs_FinsSpecsReportType,
    UMAA_EO_FinsSpecs_FinsSpecsReportTypeTopic,
)


class FinsSpecsReportProvider(ReportProvider):
    """FinsSpecs report provider (EO::FinsSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_FinsSpecs_FinsSpecsReportType,
            report_topic=UMAA_EO_FinsSpecs_FinsSpecsReportTypeTopic,
        )


class FinsSpecsReportConsumer(ReportConsumer):
    """FinsSpecs report consumer (EO::FinsSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_FinsSpecs_FinsSpecsReportType,
            report_topic=UMAA_EO_FinsSpecs_FinsSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.FuelTankReportType import (
    UMAA_EO_FuelTankStatus_FuelTankReportType,
    UMAA_EO_FuelTankStatus_FuelTankReportTypeTopic,
)


class FuelTankReportProvider(ReportProvider):
    """FuelTank report provider (EO::FuelTankStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_FuelTankStatus_FuelTankReportType,
            report_topic=UMAA_EO_FuelTankStatus_FuelTankReportTypeTopic,
        )


class FuelTankReportConsumer(ReportConsumer):
    """FuelTank report consumer (EO::FuelTankStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_FuelTankStatus_FuelTankReportType,
            report_topic=UMAA_EO_FuelTankStatus_FuelTankReportTypeTopic,
        )

from rtiumaapy.datamodel.FuelTankSpecsReportType import (
    UMAA_EO_FuelTankSpecs_FuelTankSpecsReportType,
    UMAA_EO_FuelTankSpecs_FuelTankSpecsReportTypeTopic,
)


class FuelTankSpecsReportProvider(ReportProvider):
    """FuelTankSpecs report provider (EO::FuelTankSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_FuelTankSpecs_FuelTankSpecsReportType,
            report_topic=UMAA_EO_FuelTankSpecs_FuelTankSpecsReportTypeTopic,
        )


class FuelTankSpecsReportConsumer(ReportConsumer):
    """FuelTankSpecs report consumer (EO::FuelTankSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_FuelTankSpecs_FuelTankSpecsReportType,
            report_topic=UMAA_EO_FuelTankSpecs_FuelTankSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.GeneratorReportType import (
    UMAA_EO_GeneratorStatus_GeneratorReportType,
    UMAA_EO_GeneratorStatus_GeneratorReportTypeTopic,
)


class GeneratorReportProvider(ReportProvider):
    """Generator report provider (EO::GeneratorStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_GeneratorStatus_GeneratorReportType,
            report_topic=UMAA_EO_GeneratorStatus_GeneratorReportTypeTopic,
        )


class GeneratorReportConsumer(ReportConsumer):
    """Generator report consumer (EO::GeneratorStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_GeneratorStatus_GeneratorReportType,
            report_topic=UMAA_EO_GeneratorStatus_GeneratorReportTypeTopic,
        )

from rtiumaapy.datamodel.GeneratorSpecsReportType import (
    UMAA_EO_GeneratorSpecs_GeneratorSpecsReportType,
    UMAA_EO_GeneratorSpecs_GeneratorSpecsReportTypeTopic,
)


class GeneratorSpecsReportProvider(ReportProvider):
    """GeneratorSpecs report provider (EO::GeneratorSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_GeneratorSpecs_GeneratorSpecsReportType,
            report_topic=UMAA_EO_GeneratorSpecs_GeneratorSpecsReportTypeTopic,
        )


class GeneratorSpecsReportConsumer(ReportConsumer):
    """GeneratorSpecs report consumer (EO::GeneratorSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_GeneratorSpecs_GeneratorSpecsReportType,
            report_topic=UMAA_EO_GeneratorSpecs_GeneratorSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.MastReportType import (
    UMAA_EO_MastStatus_MastReportType,
    UMAA_EO_MastStatus_MastReportTypeTopic,
)


class MastReportProvider(ReportProvider):
    """Mast report provider (EO::MastStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_MastStatus_MastReportType,
            report_topic=UMAA_EO_MastStatus_MastReportTypeTopic,
        )


class MastReportConsumer(ReportConsumer):
    """Mast report consumer (EO::MastStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_MastStatus_MastReportType,
            report_topic=UMAA_EO_MastStatus_MastReportTypeTopic,
        )

from rtiumaapy.datamodel.PowerReportType import (
    UMAA_EO_PowerStatus_PowerReportType,
    UMAA_EO_PowerStatus_PowerReportTypeTopic,
)


class PowerReportProvider(ReportProvider):
    """Power report provider (EO::PowerStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_PowerStatus_PowerReportType,
            report_topic=UMAA_EO_PowerStatus_PowerReportTypeTopic,
        )


class PowerReportConsumer(ReportConsumer):
    """Power report consumer (EO::PowerStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_PowerStatus_PowerReportType,
            report_topic=UMAA_EO_PowerStatus_PowerReportTypeTopic,
        )

from rtiumaapy.datamodel.PropulsorsSpecsReportType import (
    UMAA_EO_PropulsorsSpecs_PropulsorsSpecsReportType,
    UMAA_EO_PropulsorsSpecs_PropulsorsSpecsReportTypeTopic,
)


class PropulsorsSpecsReportProvider(ReportProvider):
    """PropulsorsSpecs report provider (EO::PropulsorsSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_PropulsorsSpecs_PropulsorsSpecsReportType,
            report_topic=UMAA_EO_PropulsorsSpecs_PropulsorsSpecsReportTypeTopic,
        )


class PropulsorsSpecsReportConsumer(ReportConsumer):
    """PropulsorsSpecs report consumer (EO::PropulsorsSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_PropulsorsSpecs_PropulsorsSpecsReportType,
            report_topic=UMAA_EO_PropulsorsSpecs_PropulsorsSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.UVPlatformCapabilitiesReportType import (
    UMAA_EO_UVPlatformSpecs_UVPlatformCapabilitiesReportType,
    UMAA_EO_UVPlatformSpecs_UVPlatformCapabilitiesReportTypeTopic,
)


class UVPlatformCapabilitiesReportProvider(ReportProvider):
    """UVPlatformCapabilities report provider (EO::UVPlatformSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_UVPlatformSpecs_UVPlatformCapabilitiesReportType,
            report_topic=UMAA_EO_UVPlatformSpecs_UVPlatformCapabilitiesReportTypeTopic,
        )


class UVPlatformCapabilitiesReportConsumer(ReportConsumer):
    """UVPlatformCapabilities report consumer (EO::UVPlatformSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_UVPlatformSpecs_UVPlatformCapabilitiesReportType,
            report_topic=UMAA_EO_UVPlatformSpecs_UVPlatformCapabilitiesReportTypeTopic,
        )

from rtiumaapy.datamodel.UVPlatformSpecsReportType import (
    UMAA_EO_UVPlatformSpecs_UVPlatformSpecsReportType,
    UMAA_EO_UVPlatformSpecs_UVPlatformSpecsReportTypeTopic,
)


class UVPlatformSpecsReportProvider(ReportProvider):
    """UVPlatformSpecs report provider (EO::UVPlatformSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_UVPlatformSpecs_UVPlatformSpecsReportType,
            report_topic=UMAA_EO_UVPlatformSpecs_UVPlatformSpecsReportTypeTopic,
        )


class UVPlatformSpecsReportConsumer(ReportConsumer):
    """UVPlatformSpecs report consumer (EO::UVPlatformSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_EO_UVPlatformSpecs_UVPlatformSpecsReportType,
            report_topic=UMAA_EO_UVPlatformSpecs_UVPlatformSpecsReportTypeTopic,
        )
