"""rtiumaapy.services.sem — Sensors service classes.

Auto-generated by tools/generate_services.py. Do not edit manually.
"""

from __future__ import annotations

from rtiumaapy.command_provider import CommandProvider
from rtiumaapy.command_consumer import CommandConsumer
from rtiumaapy.report_provider import ReportProvider
from rtiumaapy.report_consumer import ReportConsumer
from rtiumaapy.dds_context import DDSContext

__all__ = [
    "FLSControlConsumer",
    "FLSControlProvider",
    "FLSPreCalcControlConsumer",
    "FLSPreCalcControlProvider",
    "GPSReportConsumer",
    "GPSReportProvider",
    "IlluminatorControlConsumer",
    "IlluminatorControlProvider",
    "IlluminatorReportConsumer",
    "IlluminatorReportProvider",
    "IlluminatorSpecsReportConsumer",
    "IlluminatorSpecsReportProvider",
    "InertialSensorControlConsumer",
    "InertialSensorControlProvider",
    "InertialSensorReportConsumer",
    "InertialSensorReportProvider",
    "MapSegmentControlConsumer",
    "MapSegmentControlProvider",
    "SASConfigConsumer",
    "SASConfigProvider",
    "SASConfigReportConsumer",
    "SASConfigReportProvider",
    "SASControlConsumer",
    "SASControlProvider",
    "SASStatusReportConsumer",
    "SASStatusReportProvider",
]

from rtiumaapy.datamodel.FLSCommandType import (
    UMAA_SEM_FLSControl_FLSCommandType,
    UMAA_SEM_FLSControl_FLSCommandTypeTopic,
)
from rtiumaapy.datamodel.FLSCommandAckReportType import (
    UMAA_SEM_FLSControl_FLSCommandAckReportType,
    UMAA_SEM_FLSControl_FLSCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.FLSCommandStatusType import (
    UMAA_SEM_FLSControl_FLSCommandStatusType,
    UMAA_SEM_FLSControl_FLSCommandStatusTypeTopic,
)


class FLSControlProvider(CommandProvider):
    """FLS command provider (SEM::FLSControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="FLSProvider",
            command_type=UMAA_SEM_FLSControl_FLSCommandType,
            command_topic=UMAA_SEM_FLSControl_FLSCommandTypeTopic,
            ack_type=UMAA_SEM_FLSControl_FLSCommandAckReportType,
            ack_topic=UMAA_SEM_FLSControl_FLSCommandAckReportTypeTopic,
            status_type=UMAA_SEM_FLSControl_FLSCommandStatusType,
            status_topic=UMAA_SEM_FLSControl_FLSCommandStatusTypeTopic,
            source_id=source_id,
        )


class FLSControlConsumer(CommandConsumer):
    """FLS command consumer (SEM::FLSControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="FLSConsumer",
            command_type=UMAA_SEM_FLSControl_FLSCommandType,
            command_topic=UMAA_SEM_FLSControl_FLSCommandTypeTopic,
            ack_type=UMAA_SEM_FLSControl_FLSCommandAckReportType,
            ack_topic=UMAA_SEM_FLSControl_FLSCommandAckReportTypeTopic,
            status_type=UMAA_SEM_FLSControl_FLSCommandStatusType,
            status_topic=UMAA_SEM_FLSControl_FLSCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.FLSPreCalcCommandType import (
    UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandType,
    UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandTypeTopic,
)
from rtiumaapy.datamodel.FLSPreCalcCommandAckReportType import (
    UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandAckReportType,
    UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.FLSPreCalcCommandStatusType import (
    UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandStatusType,
    UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandStatusTypeTopic,
)


class FLSPreCalcControlProvider(CommandProvider):
    """FLSPreCalc command provider (SEM::FLSPreCalcControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="FLSPreCalcProvider",
            command_type=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandType,
            command_topic=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandTypeTopic,
            ack_type=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandAckReportType,
            ack_topic=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandAckReportTypeTopic,
            status_type=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandStatusType,
            status_topic=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandStatusTypeTopic,
            source_id=source_id,
        )


class FLSPreCalcControlConsumer(CommandConsumer):
    """FLSPreCalc command consumer (SEM::FLSPreCalcControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="FLSPreCalcConsumer",
            command_type=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandType,
            command_topic=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandTypeTopic,
            ack_type=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandAckReportType,
            ack_topic=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandAckReportTypeTopic,
            status_type=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandStatusType,
            status_topic=UMAA_SEM_FLSPreCalcControl_FLSPreCalcCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.IlluminatorCommandType import (
    UMAA_SEM_IlluminatorControl_IlluminatorCommandType,
    UMAA_SEM_IlluminatorControl_IlluminatorCommandTypeTopic,
)
from rtiumaapy.datamodel.IlluminatorCommandAckReportType import (
    UMAA_SEM_IlluminatorControl_IlluminatorCommandAckReportType,
    UMAA_SEM_IlluminatorControl_IlluminatorCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.IlluminatorCommandStatusType import (
    UMAA_SEM_IlluminatorControl_IlluminatorCommandStatusType,
    UMAA_SEM_IlluminatorControl_IlluminatorCommandStatusTypeTopic,
)


class IlluminatorControlProvider(CommandProvider):
    """Illuminator command provider (SEM::IlluminatorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="IlluminatorProvider",
            command_type=UMAA_SEM_IlluminatorControl_IlluminatorCommandType,
            command_topic=UMAA_SEM_IlluminatorControl_IlluminatorCommandTypeTopic,
            ack_type=UMAA_SEM_IlluminatorControl_IlluminatorCommandAckReportType,
            ack_topic=UMAA_SEM_IlluminatorControl_IlluminatorCommandAckReportTypeTopic,
            status_type=UMAA_SEM_IlluminatorControl_IlluminatorCommandStatusType,
            status_topic=UMAA_SEM_IlluminatorControl_IlluminatorCommandStatusTypeTopic,
            source_id=source_id,
        )


class IlluminatorControlConsumer(CommandConsumer):
    """Illuminator command consumer (SEM::IlluminatorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="IlluminatorConsumer",
            command_type=UMAA_SEM_IlluminatorControl_IlluminatorCommandType,
            command_topic=UMAA_SEM_IlluminatorControl_IlluminatorCommandTypeTopic,
            ack_type=UMAA_SEM_IlluminatorControl_IlluminatorCommandAckReportType,
            ack_topic=UMAA_SEM_IlluminatorControl_IlluminatorCommandAckReportTypeTopic,
            status_type=UMAA_SEM_IlluminatorControl_IlluminatorCommandStatusType,
            status_topic=UMAA_SEM_IlluminatorControl_IlluminatorCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.InertialSensorCommandType import (
    UMAA_SEM_InertialSensorControl_InertialSensorCommandType,
    UMAA_SEM_InertialSensorControl_InertialSensorCommandTypeTopic,
)
from rtiumaapy.datamodel.InertialSensorCommandAckReportType import (
    UMAA_SEM_InertialSensorControl_InertialSensorCommandAckReportType,
    UMAA_SEM_InertialSensorControl_InertialSensorCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.InertialSensorCommandStatusType import (
    UMAA_SEM_InertialSensorControl_InertialSensorCommandStatusType,
    UMAA_SEM_InertialSensorControl_InertialSensorCommandStatusTypeTopic,
)


class InertialSensorControlProvider(CommandProvider):
    """InertialSensor command provider (SEM::InertialSensorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="InertialSensorProvider",
            command_type=UMAA_SEM_InertialSensorControl_InertialSensorCommandType,
            command_topic=UMAA_SEM_InertialSensorControl_InertialSensorCommandTypeTopic,
            ack_type=UMAA_SEM_InertialSensorControl_InertialSensorCommandAckReportType,
            ack_topic=UMAA_SEM_InertialSensorControl_InertialSensorCommandAckReportTypeTopic,
            status_type=UMAA_SEM_InertialSensorControl_InertialSensorCommandStatusType,
            status_topic=UMAA_SEM_InertialSensorControl_InertialSensorCommandStatusTypeTopic,
            source_id=source_id,
        )


class InertialSensorControlConsumer(CommandConsumer):
    """InertialSensor command consumer (SEM::InertialSensorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="InertialSensorConsumer",
            command_type=UMAA_SEM_InertialSensorControl_InertialSensorCommandType,
            command_topic=UMAA_SEM_InertialSensorControl_InertialSensorCommandTypeTopic,
            ack_type=UMAA_SEM_InertialSensorControl_InertialSensorCommandAckReportType,
            ack_topic=UMAA_SEM_InertialSensorControl_InertialSensorCommandAckReportTypeTopic,
            status_type=UMAA_SEM_InertialSensorControl_InertialSensorCommandStatusType,
            status_topic=UMAA_SEM_InertialSensorControl_InertialSensorCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MapSegmentCommandType import (
    UMAA_SEM_MapSegmentControl_MapSegmentCommandType,
    UMAA_SEM_MapSegmentControl_MapSegmentCommandTypeTopic,
)
from rtiumaapy.datamodel.MapSegmentCommandAckReportType import (
    UMAA_SEM_MapSegmentControl_MapSegmentCommandAckReportType,
    UMAA_SEM_MapSegmentControl_MapSegmentCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MapSegmentCommandStatusType import (
    UMAA_SEM_MapSegmentControl_MapSegmentCommandStatusType,
    UMAA_SEM_MapSegmentControl_MapSegmentCommandStatusTypeTopic,
)


class MapSegmentControlProvider(CommandProvider):
    """MapSegment command provider (SEM::MapSegmentControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MapSegmentProvider",
            command_type=UMAA_SEM_MapSegmentControl_MapSegmentCommandType,
            command_topic=UMAA_SEM_MapSegmentControl_MapSegmentCommandTypeTopic,
            ack_type=UMAA_SEM_MapSegmentControl_MapSegmentCommandAckReportType,
            ack_topic=UMAA_SEM_MapSegmentControl_MapSegmentCommandAckReportTypeTopic,
            status_type=UMAA_SEM_MapSegmentControl_MapSegmentCommandStatusType,
            status_topic=UMAA_SEM_MapSegmentControl_MapSegmentCommandStatusTypeTopic,
            source_id=source_id,
        )


class MapSegmentControlConsumer(CommandConsumer):
    """MapSegment command consumer (SEM::MapSegmentControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MapSegmentConsumer",
            command_type=UMAA_SEM_MapSegmentControl_MapSegmentCommandType,
            command_topic=UMAA_SEM_MapSegmentControl_MapSegmentCommandTypeTopic,
            ack_type=UMAA_SEM_MapSegmentControl_MapSegmentCommandAckReportType,
            ack_topic=UMAA_SEM_MapSegmentControl_MapSegmentCommandAckReportTypeTopic,
            status_type=UMAA_SEM_MapSegmentControl_MapSegmentCommandStatusType,
            status_topic=UMAA_SEM_MapSegmentControl_MapSegmentCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.SASCommandType import (
    UMAA_SEM_SASControl_SASCommandType,
    UMAA_SEM_SASControl_SASCommandTypeTopic,
)
from rtiumaapy.datamodel.SASCommandAckReportType import (
    UMAA_SEM_SASControl_SASCommandAckReportType,
    UMAA_SEM_SASControl_SASCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.SASCommandStatusType import (
    UMAA_SEM_SASControl_SASCommandStatusType,
    UMAA_SEM_SASControl_SASCommandStatusTypeTopic,
)


class SASControlProvider(CommandProvider):
    """SAS command provider (SEM::SASControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="SASProvider",
            command_type=UMAA_SEM_SASControl_SASCommandType,
            command_topic=UMAA_SEM_SASControl_SASCommandTypeTopic,
            ack_type=UMAA_SEM_SASControl_SASCommandAckReportType,
            ack_topic=UMAA_SEM_SASControl_SASCommandAckReportTypeTopic,
            status_type=UMAA_SEM_SASControl_SASCommandStatusType,
            status_topic=UMAA_SEM_SASControl_SASCommandStatusTypeTopic,
            source_id=source_id,
        )


class SASControlConsumer(CommandConsumer):
    """SAS command consumer (SEM::SASControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="SASConsumer",
            command_type=UMAA_SEM_SASControl_SASCommandType,
            command_topic=UMAA_SEM_SASControl_SASCommandTypeTopic,
            ack_type=UMAA_SEM_SASControl_SASCommandAckReportType,
            ack_topic=UMAA_SEM_SASControl_SASCommandAckReportTypeTopic,
            status_type=UMAA_SEM_SASControl_SASCommandStatusType,
            status_topic=UMAA_SEM_SASControl_SASCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.SASConfigCommandType import (
    UMAA_SEM_SASConfig_SASConfigCommandType,
    UMAA_SEM_SASConfig_SASConfigCommandTypeTopic,
)
from rtiumaapy.datamodel.SASConfigAckReportType import (
    UMAA_SEM_SASConfig_SASConfigAckReportType,
    UMAA_SEM_SASConfig_SASConfigAckReportTypeTopic,
)
from rtiumaapy.datamodel.SASConfigCommandStatusType import (
    UMAA_SEM_SASConfig_SASConfigCommandStatusType,
    UMAA_SEM_SASConfig_SASConfigCommandStatusTypeTopic,
)


class SASConfigProvider(CommandProvider):
    """SASConfig Config provider (SEM::SASConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="SASConfigProvider",
            command_type=UMAA_SEM_SASConfig_SASConfigCommandType,
            command_topic=UMAA_SEM_SASConfig_SASConfigCommandTypeTopic,
            ack_type=UMAA_SEM_SASConfig_SASConfigAckReportType,
            ack_topic=UMAA_SEM_SASConfig_SASConfigAckReportTypeTopic,
            status_type=UMAA_SEM_SASConfig_SASConfigCommandStatusType,
            status_topic=UMAA_SEM_SASConfig_SASConfigCommandStatusTypeTopic,
            source_id=source_id,
        )


class SASConfigConsumer(CommandConsumer):
    """SASConfig Config consumer (SEM::SASConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="SASConfigConsumer",
            command_type=UMAA_SEM_SASConfig_SASConfigCommandType,
            command_topic=UMAA_SEM_SASConfig_SASConfigCommandTypeTopic,
            ack_type=UMAA_SEM_SASConfig_SASConfigAckReportType,
            ack_topic=UMAA_SEM_SASConfig_SASConfigAckReportTypeTopic,
            status_type=UMAA_SEM_SASConfig_SASConfigCommandStatusType,
            status_topic=UMAA_SEM_SASConfig_SASConfigCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.GPSReportType import (
    UMAA_SEM_GPSStatus_GPSReportType,
    UMAA_SEM_GPSStatus_GPSReportTypeTopic,
)


class GPSReportProvider(ReportProvider):
    """GPS report provider (SEM::GPSStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_GPSStatus_GPSReportType,
            report_topic=UMAA_SEM_GPSStatus_GPSReportTypeTopic,
            key_holder=key_holder,
        )


class GPSReportConsumer(ReportConsumer):
    """GPS report consumer (SEM::GPSStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "GPSReportConsumer"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_GPSStatus_GPSReportType,
            report_topic=UMAA_SEM_GPSStatus_GPSReportTypeTopic,
        )

from rtiumaapy.datamodel.IlluminatorReportType import (
    UMAA_SEM_IlluminatorStatus_IlluminatorReportType,
    UMAA_SEM_IlluminatorStatus_IlluminatorReportTypeTopic,
)


class IlluminatorReportProvider(ReportProvider):
    """Illuminator report provider (SEM::IlluminatorStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_IlluminatorStatus_IlluminatorReportType,
            report_topic=UMAA_SEM_IlluminatorStatus_IlluminatorReportTypeTopic,
            key_holder=key_holder,
        )


class IlluminatorReportConsumer(ReportConsumer):
    """Illuminator report consumer (SEM::IlluminatorStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "IlluminatorReportConsumer"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_IlluminatorStatus_IlluminatorReportType,
            report_topic=UMAA_SEM_IlluminatorStatus_IlluminatorReportTypeTopic,
        )

from rtiumaapy.datamodel.IlluminatorSpecsReportType import (
    UMAA_SEM_IlluminatorSpecs_IlluminatorSpecsReportType,
    UMAA_SEM_IlluminatorSpecs_IlluminatorSpecsReportTypeTopic,
)


class IlluminatorSpecsReportProvider(ReportProvider):
    """IlluminatorSpecs report provider (SEM::IlluminatorSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_IlluminatorSpecs_IlluminatorSpecsReportType,
            report_topic=UMAA_SEM_IlluminatorSpecs_IlluminatorSpecsReportTypeTopic,
            key_holder=key_holder,
        )


class IlluminatorSpecsReportConsumer(ReportConsumer):
    """IlluminatorSpecs report consumer (SEM::IlluminatorSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: str = "IlluminatorSpecsReportConsumer"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_IlluminatorSpecs_IlluminatorSpecsReportType,
            report_topic=UMAA_SEM_IlluminatorSpecs_IlluminatorSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.InertialSensorReportType import (
    UMAA_SEM_InertialSensorStatus_InertialSensorReportType,
    UMAA_SEM_InertialSensorStatus_InertialSensorReportTypeTopic,
)


class InertialSensorReportProvider(ReportProvider):
    """InertialSensor report provider (SEM::InertialSensorStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_InertialSensorStatus_InertialSensorReportType,
            report_topic=UMAA_SEM_InertialSensorStatus_InertialSensorReportTypeTopic,
            key_holder=key_holder,
        )


class InertialSensorReportConsumer(ReportConsumer):
    """InertialSensor report consumer (SEM::InertialSensorStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "InertialSensorReportConsumer"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_InertialSensorStatus_InertialSensorReportType,
            report_topic=UMAA_SEM_InertialSensorStatus_InertialSensorReportTypeTopic,
        )

from rtiumaapy.datamodel.SASConfigReportType import (
    UMAA_SEM_SASConfig_SASConfigReportType,
    UMAA_SEM_SASConfig_SASConfigReportTypeTopic,
)


class SASConfigReportProvider(ReportProvider):
    """SASConfig report provider (SEM::SASConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_SASConfig_SASConfigReportType,
            report_topic=UMAA_SEM_SASConfig_SASConfigReportTypeTopic,
            key_holder=key_holder,
        )


class SASConfigReportConsumer(ReportConsumer):
    """SASConfig report consumer (SEM::SASConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str = "SASConfigReportConsumer"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_SASConfig_SASConfigReportType,
            report_topic=UMAA_SEM_SASConfig_SASConfigReportTypeTopic,
        )

from rtiumaapy.datamodel.SASStatusReportType import (
    UMAA_SEM_SASStatus_SASStatusReportType,
    UMAA_SEM_SASStatus_SASStatusReportTypeTopic,
)


class SASStatusReportProvider(ReportProvider):
    """SASStatus report provider (SEM::SASStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_SASStatus_SASStatusReportType,
            report_topic=UMAA_SEM_SASStatus_SASStatusReportTypeTopic,
            key_holder=key_holder,
        )


class SASStatusReportConsumer(ReportConsumer):
    """SASStatus report consumer (SEM::SASStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "SASStatusReportConsumer"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SEM_SASStatus_SASStatusReportType,
            report_topic=UMAA_SEM_SASStatus_SASStatusReportTypeTopic,
        )
