"""rtiumaapy.services.sa — Situational Awareness service classes.

Auto-generated by tools/generate_services.py. Do not edit manually.
"""

from __future__ import annotations
from typing import Optional

from rtiumaapy.command_provider import CommandProvider
from rtiumaapy.command_consumer import CommandConsumer
from rtiumaapy.report_provider import ReportProvider
from rtiumaapy.report_consumer import ReportConsumer
from rtiumaapy.dds_context import DDSContext

__all__ = [
    "AccelerationReportConsumer",
    "AccelerationReportProvider",
    "CompartmentConfigReportConsumer",
    "CompartmentConfigReportProvider",
    "CompartmentReportConsumer",
    "CompartmentReportProvider",
    "ContactCOLREGSClassificationReportConsumer",
    "ContactCOLREGSClassificationReportProvider",
    "ContactCategoryReportConsumer",
    "ContactCategoryReportProvider",
    "ContactFilterConfigConsumer",
    "ContactFilterConfigProvider",
    "ContactIdentityReportConsumer",
    "ContactIdentityReportProvider",
    "ContactReportConsumer",
    "ContactReportProvider",
    "ContactVisualClassificationReportConsumer",
    "ContactVisualClassificationReportProvider",
    "DateTimeReportConsumer",
    "DateTimeReportProvider",
    "ECEFPoseReportConsumer",
    "ECEFPoseReportProvider",
    "GlobalPoseConfigConsumer",
    "GlobalPoseConfigProvider",
    "GlobalPoseConfigReportConsumer",
    "GlobalPoseConfigReportProvider",
    "GlobalPoseReportConsumer",
    "GlobalPoseReportProvider",
    "LandmarkReportConsumer",
    "LandmarkReportProvider",
    "MagneticVariationReportConsumer",
    "MagneticVariationReportProvider",
    "MagneticVariationSpecsReportConsumer",
    "MagneticVariationSpecsReportProvider",
    "OrientationReportConsumer",
    "OrientationReportProvider",
    "PassiveContactReportConsumer",
    "PassiveContactReportProvider",
    "PathReporterReportConsumer",
    "PathReporterReportProvider",
    "PathReporterSpecsReportConsumer",
    "PathReporterSpecsReportProvider",
    "RelativeContactReportConsumer",
    "RelativeContactReportProvider",
    "SeaStateReportConsumer",
    "SeaStateReportProvider",
    "SoundVelocityProfileReportConsumer",
    "SoundVelocityProfileReportProvider",
    "SpeedReportConsumer",
    "SpeedReportProvider",
    "StillImageReportConsumer",
    "StillImageReportProvider",
    "TerrainReportConsumer",
    "TerrainReportProvider",
    "TranslationalShipMotionReportConsumer",
    "TranslationalShipMotionReportProvider",
    "VelocityReportConsumer",
    "VelocityReportProvider",
    "WaterCharacteristicsReportConsumer",
    "WaterCharacteristicsReportProvider",
    "WaterCurrentReportConsumer",
    "WaterCurrentReportProvider",
    "WeatherReportConsumer",
    "WeatherReportProvider",
    "WindReportConsumer",
    "WindReportProvider",
]

from rtiumaapy.datamodel.ContactFilterConfigCommandType import (
    UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandType,
    UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandTypeTopic,
)
from rtiumaapy.datamodel.ContactFilterConfigAckReportType import (
    UMAA_SA_ContactFilterConfig_ContactFilterConfigAckReportType,
    UMAA_SA_ContactFilterConfig_ContactFilterConfigAckReportTypeTopic,
)
from rtiumaapy.datamodel.ContactFilterConfigCommandStatusType import (
    UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandStatusType,
    UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandStatusTypeTopic,
)


class ContactFilterConfigProvider(CommandProvider):
    """ContactFilterConfig Config provider (SA::ContactFilterConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ContactFilterConfigProvider",
            command_type=UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandType,
            command_topic=UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandTypeTopic,
            ack_type=UMAA_SA_ContactFilterConfig_ContactFilterConfigAckReportType,
            ack_topic=UMAA_SA_ContactFilterConfig_ContactFilterConfigAckReportTypeTopic,
            status_type=UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandStatusType,
            status_topic=UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandStatusTypeTopic,
            source_id=source_id,
        )


class ContactFilterConfigConsumer(CommandConsumer):
    """ContactFilterConfig Config consumer (SA::ContactFilterConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ContactFilterConfigConsumer",
            command_type=UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandType,
            command_topic=UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandTypeTopic,
            ack_type=UMAA_SA_ContactFilterConfig_ContactFilterConfigAckReportType,
            ack_topic=UMAA_SA_ContactFilterConfig_ContactFilterConfigAckReportTypeTopic,
            status_type=UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandStatusType,
            status_topic=UMAA_SA_ContactFilterConfig_ContactFilterConfigCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.GlobalPoseConfigCommandType import (
    UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandType,
    UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandTypeTopic,
)
from rtiumaapy.datamodel.GlobalPoseConfigAckReportType import (
    UMAA_SA_GlobalPoseConfig_GlobalPoseConfigAckReportType,
    UMAA_SA_GlobalPoseConfig_GlobalPoseConfigAckReportTypeTopic,
)
from rtiumaapy.datamodel.GlobalPoseConfigCommandStatusType import (
    UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandStatusType,
    UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandStatusTypeTopic,
)


class GlobalPoseConfigProvider(CommandProvider):
    """GlobalPoseConfig Config provider (SA::GlobalPoseConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="GlobalPoseConfigProvider",
            command_type=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandType,
            command_topic=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandTypeTopic,
            ack_type=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigAckReportType,
            ack_topic=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigAckReportTypeTopic,
            status_type=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandStatusType,
            status_topic=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandStatusTypeTopic,
            source_id=source_id,
        )


class GlobalPoseConfigConsumer(CommandConsumer):
    """GlobalPoseConfig Config consumer (SA::GlobalPoseConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="GlobalPoseConfigConsumer",
            command_type=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandType,
            command_topic=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandTypeTopic,
            ack_type=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigAckReportType,
            ack_topic=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigAckReportTypeTopic,
            status_type=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandStatusType,
            status_topic=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.AccelerationReportType import (
    UMAA_SA_AccelerationStatus_AccelerationReportType,
    UMAA_SA_AccelerationStatus_AccelerationReportTypeTopic,
)


class AccelerationReportProvider(ReportProvider):
    """Acceleration report provider (SA::AccelerationStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_AccelerationStatus_AccelerationReportType,
            report_topic=UMAA_SA_AccelerationStatus_AccelerationReportTypeTopic,
        )


class AccelerationReportConsumer(ReportConsumer):
    """Acceleration report consumer (SA::AccelerationStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_AccelerationStatus_AccelerationReportType,
            report_topic=UMAA_SA_AccelerationStatus_AccelerationReportTypeTopic,
        )

from rtiumaapy.datamodel.CompartmentReportType import (
    UMAA_SA_CompartmentStatus_CompartmentReportType,
    UMAA_SA_CompartmentStatus_CompartmentReportTypeTopic,
)


class CompartmentReportProvider(ReportProvider):
    """Compartment report provider (SA::CompartmentStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_CompartmentStatus_CompartmentReportType,
            report_topic=UMAA_SA_CompartmentStatus_CompartmentReportTypeTopic,
        )


class CompartmentReportConsumer(ReportConsumer):
    """Compartment report consumer (SA::CompartmentStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_CompartmentStatus_CompartmentReportType,
            report_topic=UMAA_SA_CompartmentStatus_CompartmentReportTypeTopic,
        )

from rtiumaapy.datamodel.CompartmentConfigReportType import (
    UMAA_SA_CompartmentConfig_CompartmentConfigReportType,
    UMAA_SA_CompartmentConfig_CompartmentConfigReportTypeTopic,
)


class CompartmentConfigReportProvider(ReportProvider):
    """CompartmentConfig report provider (SA::CompartmentConfig)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_CompartmentConfig_CompartmentConfigReportType,
            report_topic=UMAA_SA_CompartmentConfig_CompartmentConfigReportTypeTopic,
        )


class CompartmentConfigReportConsumer(ReportConsumer):
    """CompartmentConfig report consumer (SA::CompartmentConfig)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_CompartmentConfig_CompartmentConfigReportType,
            report_topic=UMAA_SA_CompartmentConfig_CompartmentConfigReportTypeTopic,
        )

from rtiumaapy.datamodel.ContactReportType import (
    UMAA_SA_ContactReport_ContactReportType,
    UMAA_SA_ContactReport_ContactReportTypeTopic,
)


class ContactReportProvider(ReportProvider):
    """Contact report provider (SA::ContactReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ContactReport_ContactReportType,
            report_topic=UMAA_SA_ContactReport_ContactReportTypeTopic,
        )


class ContactReportConsumer(ReportConsumer):
    """Contact report consumer (SA::ContactReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ContactReport_ContactReportType,
            report_topic=UMAA_SA_ContactReport_ContactReportTypeTopic,
        )

from rtiumaapy.datamodel.ContactCOLREGSClassificationReportType import (
    UMAA_SA_ContactCOLREGSClassificationStatus_ContactCOLREGSClassificationReportType,
    UMAA_SA_ContactCOLREGSClassificationStatus_ContactCOLREGSClassificationReportTypeTopic,
)


class ContactCOLREGSClassificationReportProvider(ReportProvider):
    """ContactCOLREGSClassification report provider (SA::ContactCOLREGSClassificationStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ContactCOLREGSClassificationStatus_ContactCOLREGSClassificationReportType,
            report_topic=UMAA_SA_ContactCOLREGSClassificationStatus_ContactCOLREGSClassificationReportTypeTopic,
        )


class ContactCOLREGSClassificationReportConsumer(ReportConsumer):
    """ContactCOLREGSClassification report consumer (SA::ContactCOLREGSClassificationStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ContactCOLREGSClassificationStatus_ContactCOLREGSClassificationReportType,
            report_topic=UMAA_SA_ContactCOLREGSClassificationStatus_ContactCOLREGSClassificationReportTypeTopic,
        )

from rtiumaapy.datamodel.ContactCategoryReportType import (
    UMAA_SA_ContactCategoryReport_ContactCategoryReportType,
    UMAA_SA_ContactCategoryReport_ContactCategoryReportTypeTopic,
)


class ContactCategoryReportProvider(ReportProvider):
    """ContactCategory report provider (SA::ContactCategoryReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ContactCategoryReport_ContactCategoryReportType,
            report_topic=UMAA_SA_ContactCategoryReport_ContactCategoryReportTypeTopic,
        )


class ContactCategoryReportConsumer(ReportConsumer):
    """ContactCategory report consumer (SA::ContactCategoryReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ContactCategoryReport_ContactCategoryReportType,
            report_topic=UMAA_SA_ContactCategoryReport_ContactCategoryReportTypeTopic,
        )

from rtiumaapy.datamodel.ContactIdentityReportType import (
    UMAA_SA_ContactIdentityReport_ContactIdentityReportType,
    UMAA_SA_ContactIdentityReport_ContactIdentityReportTypeTopic,
)


class ContactIdentityReportProvider(ReportProvider):
    """ContactIdentity report provider (SA::ContactIdentityReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ContactIdentityReport_ContactIdentityReportType,
            report_topic=UMAA_SA_ContactIdentityReport_ContactIdentityReportTypeTopic,
        )


class ContactIdentityReportConsumer(ReportConsumer):
    """ContactIdentity report consumer (SA::ContactIdentityReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ContactIdentityReport_ContactIdentityReportType,
            report_topic=UMAA_SA_ContactIdentityReport_ContactIdentityReportTypeTopic,
        )

from rtiumaapy.datamodel.ContactVisualClassificationReportType import (
    UMAA_SA_ContactVisualClassificationStatus_ContactVisualClassificationReportType,
    UMAA_SA_ContactVisualClassificationStatus_ContactVisualClassificationReportTypeTopic,
)


class ContactVisualClassificationReportProvider(ReportProvider):
    """ContactVisualClassification report provider (SA::ContactVisualClassificationStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ContactVisualClassificationStatus_ContactVisualClassificationReportType,
            report_topic=UMAA_SA_ContactVisualClassificationStatus_ContactVisualClassificationReportTypeTopic,
        )


class ContactVisualClassificationReportConsumer(ReportConsumer):
    """ContactVisualClassification report consumer (SA::ContactVisualClassificationStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ContactVisualClassificationStatus_ContactVisualClassificationReportType,
            report_topic=UMAA_SA_ContactVisualClassificationStatus_ContactVisualClassificationReportTypeTopic,
        )

from rtiumaapy.datamodel.DateTimeReportType import (
    UMAA_SA_DateTimeStatus_DateTimeReportType,
    UMAA_SA_DateTimeStatus_DateTimeReportTypeTopic,
)


class DateTimeReportProvider(ReportProvider):
    """DateTime report provider (SA::DateTimeStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_DateTimeStatus_DateTimeReportType,
            report_topic=UMAA_SA_DateTimeStatus_DateTimeReportTypeTopic,
        )


class DateTimeReportConsumer(ReportConsumer):
    """DateTime report consumer (SA::DateTimeStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_DateTimeStatus_DateTimeReportType,
            report_topic=UMAA_SA_DateTimeStatus_DateTimeReportTypeTopic,
        )

from rtiumaapy.datamodel.ECEFPoseReportType import (
    UMAA_SA_ECEFPoseStatus_ECEFPoseReportType,
    UMAA_SA_ECEFPoseStatus_ECEFPoseReportTypeTopic,
)


class ECEFPoseReportProvider(ReportProvider):
    """ECEFPose report provider (SA::ECEFPoseStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ECEFPoseStatus_ECEFPoseReportType,
            report_topic=UMAA_SA_ECEFPoseStatus_ECEFPoseReportTypeTopic,
        )


class ECEFPoseReportConsumer(ReportConsumer):
    """ECEFPose report consumer (SA::ECEFPoseStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_ECEFPoseStatus_ECEFPoseReportType,
            report_topic=UMAA_SA_ECEFPoseStatus_ECEFPoseReportTypeTopic,
        )

from rtiumaapy.datamodel.GlobalPoseReportType import (
    UMAA_SA_GlobalPoseStatus_GlobalPoseReportType,
    UMAA_SA_GlobalPoseStatus_GlobalPoseReportTypeTopic,
)


class GlobalPoseReportProvider(ReportProvider):
    """GlobalPose report provider (SA::GlobalPoseStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_GlobalPoseStatus_GlobalPoseReportType,
            report_topic=UMAA_SA_GlobalPoseStatus_GlobalPoseReportTypeTopic,
        )


class GlobalPoseReportConsumer(ReportConsumer):
    """GlobalPose report consumer (SA::GlobalPoseStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_GlobalPoseStatus_GlobalPoseReportType,
            report_topic=UMAA_SA_GlobalPoseStatus_GlobalPoseReportTypeTopic,
        )

from rtiumaapy.datamodel.GlobalPoseConfigReportType import (
    UMAA_SA_GlobalPoseConfig_GlobalPoseConfigReportType,
    UMAA_SA_GlobalPoseConfig_GlobalPoseConfigReportTypeTopic,
)


class GlobalPoseConfigReportProvider(ReportProvider):
    """GlobalPoseConfig report provider (SA::GlobalPoseConfig)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigReportType,
            report_topic=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigReportTypeTopic,
        )


class GlobalPoseConfigReportConsumer(ReportConsumer):
    """GlobalPoseConfig report consumer (SA::GlobalPoseConfig)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigReportType,
            report_topic=UMAA_SA_GlobalPoseConfig_GlobalPoseConfigReportTypeTopic,
        )

from rtiumaapy.datamodel.LandmarkReportType import (
    UMAA_SA_LandmarkReport_LandmarkReportType,
    UMAA_SA_LandmarkReport_LandmarkReportTypeTopic,
)


class LandmarkReportProvider(ReportProvider):
    """Landmark report provider (SA::LandmarkReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_LandmarkReport_LandmarkReportType,
            report_topic=UMAA_SA_LandmarkReport_LandmarkReportTypeTopic,
        )


class LandmarkReportConsumer(ReportConsumer):
    """Landmark report consumer (SA::LandmarkReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_LandmarkReport_LandmarkReportType,
            report_topic=UMAA_SA_LandmarkReport_LandmarkReportTypeTopic,
        )

from rtiumaapy.datamodel.MagneticVariationReportType import (
    UMAA_SA_MagneticVariationStatus_MagneticVariationReportType,
    UMAA_SA_MagneticVariationStatus_MagneticVariationReportTypeTopic,
)


class MagneticVariationReportProvider(ReportProvider):
    """MagneticVariation report provider (SA::MagneticVariationStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_MagneticVariationStatus_MagneticVariationReportType,
            report_topic=UMAA_SA_MagneticVariationStatus_MagneticVariationReportTypeTopic,
        )


class MagneticVariationReportConsumer(ReportConsumer):
    """MagneticVariation report consumer (SA::MagneticVariationStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_MagneticVariationStatus_MagneticVariationReportType,
            report_topic=UMAA_SA_MagneticVariationStatus_MagneticVariationReportTypeTopic,
        )

from rtiumaapy.datamodel.MagneticVariationSpecsReportType import (
    UMAA_SA_MagneticVariationSpecs_MagneticVariationSpecsReportType,
    UMAA_SA_MagneticVariationSpecs_MagneticVariationSpecsReportTypeTopic,
)


class MagneticVariationSpecsReportProvider(ReportProvider):
    """MagneticVariationSpecs report provider (SA::MagneticVariationSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_MagneticVariationSpecs_MagneticVariationSpecsReportType,
            report_topic=UMAA_SA_MagneticVariationSpecs_MagneticVariationSpecsReportTypeTopic,
        )


class MagneticVariationSpecsReportConsumer(ReportConsumer):
    """MagneticVariationSpecs report consumer (SA::MagneticVariationSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_MagneticVariationSpecs_MagneticVariationSpecsReportType,
            report_topic=UMAA_SA_MagneticVariationSpecs_MagneticVariationSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.OrientationReportType import (
    UMAA_SA_OrientationStatus_OrientationReportType,
    UMAA_SA_OrientationStatus_OrientationReportTypeTopic,
)


class OrientationReportProvider(ReportProvider):
    """Orientation report provider (SA::OrientationStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_OrientationStatus_OrientationReportType,
            report_topic=UMAA_SA_OrientationStatus_OrientationReportTypeTopic,
        )


class OrientationReportConsumer(ReportConsumer):
    """Orientation report consumer (SA::OrientationStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_OrientationStatus_OrientationReportType,
            report_topic=UMAA_SA_OrientationStatus_OrientationReportTypeTopic,
        )

from rtiumaapy.datamodel.PassiveContactReportType import (
    UMAA_SA_PassiveContactReport_PassiveContactReportType,
    UMAA_SA_PassiveContactReport_PassiveContactReportTypeTopic,
)


class PassiveContactReportProvider(ReportProvider):
    """PassiveContact report provider (SA::PassiveContactReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_PassiveContactReport_PassiveContactReportType,
            report_topic=UMAA_SA_PassiveContactReport_PassiveContactReportTypeTopic,
        )


class PassiveContactReportConsumer(ReportConsumer):
    """PassiveContact report consumer (SA::PassiveContactReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_PassiveContactReport_PassiveContactReportType,
            report_topic=UMAA_SA_PassiveContactReport_PassiveContactReportTypeTopic,
        )

from rtiumaapy.datamodel.PathReporterReportType import (
    UMAA_SA_PathReporterStatus_PathReporterReportType,
    UMAA_SA_PathReporterStatus_PathReporterReportTypeTopic,
)


class PathReporterReportProvider(ReportProvider):
    """PathReporter report provider (SA::PathReporterStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_PathReporterStatus_PathReporterReportType,
            report_topic=UMAA_SA_PathReporterStatus_PathReporterReportTypeTopic,
        )


class PathReporterReportConsumer(ReportConsumer):
    """PathReporter report consumer (SA::PathReporterStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_PathReporterStatus_PathReporterReportType,
            report_topic=UMAA_SA_PathReporterStatus_PathReporterReportTypeTopic,
        )

from rtiumaapy.datamodel.PathReporterSpecsReportType import (
    UMAA_SA_PathReporterSpecs_PathReporterSpecsReportType,
    UMAA_SA_PathReporterSpecs_PathReporterSpecsReportTypeTopic,
)


class PathReporterSpecsReportProvider(ReportProvider):
    """PathReporterSpecs report provider (SA::PathReporterSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_PathReporterSpecs_PathReporterSpecsReportType,
            report_topic=UMAA_SA_PathReporterSpecs_PathReporterSpecsReportTypeTopic,
        )


class PathReporterSpecsReportConsumer(ReportConsumer):
    """PathReporterSpecs report consumer (SA::PathReporterSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_PathReporterSpecs_PathReporterSpecsReportType,
            report_topic=UMAA_SA_PathReporterSpecs_PathReporterSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.RelativeContactReportType import (
    UMAA_SA_RelativeContactReport_RelativeContactReportType,
    UMAA_SA_RelativeContactReport_RelativeContactReportTypeTopic,
)


class RelativeContactReportProvider(ReportProvider):
    """RelativeContact report provider (SA::RelativeContactReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_RelativeContactReport_RelativeContactReportType,
            report_topic=UMAA_SA_RelativeContactReport_RelativeContactReportTypeTopic,
        )


class RelativeContactReportConsumer(ReportConsumer):
    """RelativeContact report consumer (SA::RelativeContactReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_RelativeContactReport_RelativeContactReportType,
            report_topic=UMAA_SA_RelativeContactReport_RelativeContactReportTypeTopic,
        )

from rtiumaapy.datamodel.SeaStateReportType import (
    UMAA_SA_SeaStateReport_SeaStateReportType,
    UMAA_SA_SeaStateReport_SeaStateReportTypeTopic,
)


class SeaStateReportProvider(ReportProvider):
    """SeaState report provider (SA::SeaStateReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_SeaStateReport_SeaStateReportType,
            report_topic=UMAA_SA_SeaStateReport_SeaStateReportTypeTopic,
        )


class SeaStateReportConsumer(ReportConsumer):
    """SeaState report consumer (SA::SeaStateReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_SeaStateReport_SeaStateReportType,
            report_topic=UMAA_SA_SeaStateReport_SeaStateReportTypeTopic,
        )

from rtiumaapy.datamodel.SoundVelocityProfileReportType import (
    UMAA_SA_SoundVelocityProfileReport_SoundVelocityProfileReportType,
    UMAA_SA_SoundVelocityProfileReport_SoundVelocityProfileReportTypeTopic,
)


class SoundVelocityProfileReportProvider(ReportProvider):
    """SoundVelocityProfile report provider (SA::SoundVelocityProfileReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_SoundVelocityProfileReport_SoundVelocityProfileReportType,
            report_topic=UMAA_SA_SoundVelocityProfileReport_SoundVelocityProfileReportTypeTopic,
        )


class SoundVelocityProfileReportConsumer(ReportConsumer):
    """SoundVelocityProfile report consumer (SA::SoundVelocityProfileReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_SoundVelocityProfileReport_SoundVelocityProfileReportType,
            report_topic=UMAA_SA_SoundVelocityProfileReport_SoundVelocityProfileReportTypeTopic,
        )

from rtiumaapy.datamodel.SpeedReportType import (
    UMAA_SA_SpeedStatus_SpeedReportType,
    UMAA_SA_SpeedStatus_SpeedReportTypeTopic,
)


class SpeedReportProvider(ReportProvider):
    """Speed report provider (SA::SpeedStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_SpeedStatus_SpeedReportType,
            report_topic=UMAA_SA_SpeedStatus_SpeedReportTypeTopic,
        )


class SpeedReportConsumer(ReportConsumer):
    """Speed report consumer (SA::SpeedStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_SpeedStatus_SpeedReportType,
            report_topic=UMAA_SA_SpeedStatus_SpeedReportTypeTopic,
        )

from rtiumaapy.datamodel.StillImageReportType import (
    UMAA_SA_StillImageStatus_StillImageReportType,
    UMAA_SA_StillImageStatus_StillImageReportTypeTopic,
)


class StillImageReportProvider(ReportProvider):
    """StillImage report provider (SA::StillImageStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_StillImageStatus_StillImageReportType,
            report_topic=UMAA_SA_StillImageStatus_StillImageReportTypeTopic,
        )


class StillImageReportConsumer(ReportConsumer):
    """StillImage report consumer (SA::StillImageStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_StillImageStatus_StillImageReportType,
            report_topic=UMAA_SA_StillImageStatus_StillImageReportTypeTopic,
        )

from rtiumaapy.datamodel.TerrainReportType import (
    UMAA_SA_TerrainReport_TerrainReportType,
    UMAA_SA_TerrainReport_TerrainReportTypeTopic,
)


class TerrainReportProvider(ReportProvider):
    """Terrain report provider (SA::TerrainReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_TerrainReport_TerrainReportType,
            report_topic=UMAA_SA_TerrainReport_TerrainReportTypeTopic,
        )


class TerrainReportConsumer(ReportConsumer):
    """Terrain report consumer (SA::TerrainReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_TerrainReport_TerrainReportType,
            report_topic=UMAA_SA_TerrainReport_TerrainReportTypeTopic,
        )

from rtiumaapy.datamodel.TranslationalShipMotionReportType import (
    UMAA_SA_TranslationalShipMotionStatus_TranslationalShipMotionReportType,
    UMAA_SA_TranslationalShipMotionStatus_TranslationalShipMotionReportTypeTopic,
)


class TranslationalShipMotionReportProvider(ReportProvider):
    """TranslationalShipMotion report provider (SA::TranslationalShipMotionStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_TranslationalShipMotionStatus_TranslationalShipMotionReportType,
            report_topic=UMAA_SA_TranslationalShipMotionStatus_TranslationalShipMotionReportTypeTopic,
        )


class TranslationalShipMotionReportConsumer(ReportConsumer):
    """TranslationalShipMotion report consumer (SA::TranslationalShipMotionStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_TranslationalShipMotionStatus_TranslationalShipMotionReportType,
            report_topic=UMAA_SA_TranslationalShipMotionStatus_TranslationalShipMotionReportTypeTopic,
        )

from rtiumaapy.datamodel.VelocityReportType import (
    UMAA_SA_VelocityStatus_VelocityReportType,
    UMAA_SA_VelocityStatus_VelocityReportTypeTopic,
)


class VelocityReportProvider(ReportProvider):
    """Velocity report provider (SA::VelocityStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_VelocityStatus_VelocityReportType,
            report_topic=UMAA_SA_VelocityStatus_VelocityReportTypeTopic,
        )


class VelocityReportConsumer(ReportConsumer):
    """Velocity report consumer (SA::VelocityStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_VelocityStatus_VelocityReportType,
            report_topic=UMAA_SA_VelocityStatus_VelocityReportTypeTopic,
        )

from rtiumaapy.datamodel.WaterCharacteristicsReportType import (
    UMAA_SA_WaterCharacteristicsStatus_WaterCharacteristicsReportType,
    UMAA_SA_WaterCharacteristicsStatus_WaterCharacteristicsReportTypeTopic,
)


class WaterCharacteristicsReportProvider(ReportProvider):
    """WaterCharacteristics report provider (SA::WaterCharacteristicsStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_WaterCharacteristicsStatus_WaterCharacteristicsReportType,
            report_topic=UMAA_SA_WaterCharacteristicsStatus_WaterCharacteristicsReportTypeTopic,
        )


class WaterCharacteristicsReportConsumer(ReportConsumer):
    """WaterCharacteristics report consumer (SA::WaterCharacteristicsStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_WaterCharacteristicsStatus_WaterCharacteristicsReportType,
            report_topic=UMAA_SA_WaterCharacteristicsStatus_WaterCharacteristicsReportTypeTopic,
        )

from rtiumaapy.datamodel.WaterCurrentReportType import (
    UMAA_SA_WaterCurrentStatus_WaterCurrentReportType,
    UMAA_SA_WaterCurrentStatus_WaterCurrentReportTypeTopic,
)


class WaterCurrentReportProvider(ReportProvider):
    """WaterCurrent report provider (SA::WaterCurrentStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_WaterCurrentStatus_WaterCurrentReportType,
            report_topic=UMAA_SA_WaterCurrentStatus_WaterCurrentReportTypeTopic,
        )


class WaterCurrentReportConsumer(ReportConsumer):
    """WaterCurrent report consumer (SA::WaterCurrentStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_WaterCurrentStatus_WaterCurrentReportType,
            report_topic=UMAA_SA_WaterCurrentStatus_WaterCurrentReportTypeTopic,
        )

from rtiumaapy.datamodel.WeatherReportType import (
    UMAA_SA_WeatherStatus_WeatherReportType,
    UMAA_SA_WeatherStatus_WeatherReportTypeTopic,
)


class WeatherReportProvider(ReportProvider):
    """Weather report provider (SA::WeatherStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_WeatherStatus_WeatherReportType,
            report_topic=UMAA_SA_WeatherStatus_WeatherReportTypeTopic,
        )


class WeatherReportConsumer(ReportConsumer):
    """Weather report consumer (SA::WeatherStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_WeatherStatus_WeatherReportType,
            report_topic=UMAA_SA_WeatherStatus_WeatherReportTypeTopic,
        )

from rtiumaapy.datamodel.WindReportType import (
    UMAA_SA_WindStatus_WindReportType,
    UMAA_SA_WindStatus_WindReportTypeTopic,
)


class WindReportProvider(ReportProvider):
    """Wind report provider (SA::WindStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_WindStatus_WindReportType,
            report_topic=UMAA_SA_WindStatus_WindReportTypeTopic,
        )


class WindReportConsumer(ReportConsumer):
    """Wind report consumer (SA::WindStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SA_WindStatus_WindReportType,
            report_topic=UMAA_SA_WindStatus_WindReportTypeTopic,
        )
