"""UMAA generated Python types (from rtiddsgen -language Python).

The generated modules use bare ``from <Module> import *`` statements
to resolve cross-type dependencies.  These only work when this package
directory is on ``sys.path``, which we ensure on first import.

This package is auto-generated by the ``gen_python_umaa_types`` CMake
target.  Do not hand-edit the individual type modules.
"""

import os as _os
import sys as _sys

# Generated modules use ``from IdentifierType import *`` etc. — bare
# module-name imports that require this directory on sys.path.
_pkg_dir = _os.path.dirname(_os.path.abspath(__file__))
if _pkg_dir not in _sys.path:
    _sys.path.insert(0, _pkg_dir)
