"""rtiumaapy.services.co — Common Operations service classes.

Auto-generated by tools/generate_services.py. Do not edit manually.
"""

from __future__ import annotations

from rtiumaapy.command_provider import CommandProvider
from rtiumaapy.command_consumer import CommandConsumer
from rtiumaapy.report_provider import ReportProvider
from rtiumaapy.report_consumer import ReportConsumer
from rtiumaapy.dds_context import DDSContext

__all__ = [
    "CommsChannelAddMessageConfigConsumer",
    "CommsChannelAddMessageConfigProvider",
    "CommsChannelClearAllControlConsumer",
    "CommsChannelClearAllControlProvider",
    "CommsChannelClearMessageControlConsumer",
    "CommsChannelClearMessageControlProvider",
    "CommsChannelConfigReportConsumer",
    "CommsChannelConfigReportProvider",
    "CommsChannelDataEncodingReportConsumer",
    "CommsChannelDataEncodingReportProvider",
    "CommsChannelDeleteMessageConfigConsumer",
    "CommsChannelDeleteMessageConfigProvider",
    "CommsChannelEnvironmentReportConsumer",
    "CommsChannelEnvironmentReportProvider",
    "CommsChannelPowerConfigConsumer",
    "CommsChannelPowerConfigProvider",
    "CommsChannelPowerConfigReportConsumer",
    "CommsChannelPowerConfigReportProvider",
    "CommsChannelPowerReportConsumer",
    "CommsChannelPowerReportProvider",
    "CommsChannelReceiverReportConsumer",
    "CommsChannelReceiverReportProvider",
    "CommsChannelReceiverStatisticsReportConsumer",
    "CommsChannelReceiverStatisticsReportProvider",
    "CommsChannelReportConsumer",
    "CommsChannelReportProvider",
    "CommsChannelResetControlConsumer",
    "CommsChannelResetControlProvider",
    "CommsChannelSenderReportConsumer",
    "CommsChannelSenderReportProvider",
    "CommsChannelSenderStatisticsReportConsumer",
    "CommsChannelSenderStatisticsReportProvider",
    "CommsChannelShutdownControlConsumer",
    "CommsChannelShutdownControlProvider",
    "CommsChannelSpecsReportConsumer",
    "CommsChannelSpecsReportProvider",
    "CommsChannelStartupControlConsumer",
    "CommsChannelStartupControlProvider",
    "CommsChannelSystemTimeReportConsumer",
    "CommsChannelSystemTimeReportProvider",
    "MessageFilterConfigConsumer",
    "MessageFilterConfigProvider",
]

from rtiumaapy.datamodel.CommsChannelAddMessageConfigCommandType import (
    UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandType,
    UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelAddMessageConfigAckReportType import (
    UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigAckReportType,
    UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigAckReportTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelAddMessageConfigCommandStatusType import (
    UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandStatusType,
    UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandStatusTypeTopic,
)


class CommsChannelAddMessageConfigProvider(CommandProvider):
    """CommsChannelAddMessageConfig Config provider (CO::CommsChannelConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="CommsChannelAddMessageConfigProvider",
            command_type=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandType,
            command_topic=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigAckReportType,
            ack_topic=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandStatusType,
            status_topic=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandStatusTypeTopic,
            source_id=source_id,
        )


class CommsChannelAddMessageConfigConsumer(CommandConsumer):
    """CommsChannelAddMessageConfig Config consumer (CO::CommsChannelConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="CommsChannelAddMessageConfigConsumer",
            command_type=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandType,
            command_topic=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigAckReportType,
            ack_topic=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandStatusType,
            status_topic=UMAA_CO_CommsChannelConfig_CommsChannelAddMessageConfigCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.CommsChannelClearAllCommandType import (
    UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandType,
    UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelClearAllCommandAckReportType import (
    UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandAckReportType,
    UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelClearAllCommandStatusType import (
    UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandStatusType,
    UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandStatusTypeTopic,
)


class CommsChannelClearAllControlProvider(CommandProvider):
    """CommsChannelClearAll command provider (CO::CommsChannelControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="CommsChannelClearAllProvider",
            command_type=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandType,
            command_topic=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandAckReportType,
            ack_topic=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandStatusType,
            status_topic=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandStatusTypeTopic,
            source_id=source_id,
        )


class CommsChannelClearAllControlConsumer(CommandConsumer):
    """CommsChannelClearAll command consumer (CO::CommsChannelControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="CommsChannelClearAllConsumer",
            command_type=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandType,
            command_topic=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandAckReportType,
            ack_topic=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandStatusType,
            status_topic=UMAA_CO_CommsChannelControl_CommsChannelClearAllCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.CommsChannelClearMessageCommandType import (
    UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandType,
    UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelClearMessageCommandAckReportType import (
    UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandAckReportType,
    UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelClearMessageCommandStatusType import (
    UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandStatusType,
    UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandStatusTypeTopic,
)


class CommsChannelClearMessageControlProvider(CommandProvider):
    """CommsChannelClearMessage command provider (CO::CommsChannelControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="CommsChannelClearMessageProvider",
            command_type=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandType,
            command_topic=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandAckReportType,
            ack_topic=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandStatusType,
            status_topic=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandStatusTypeTopic,
            source_id=source_id,
        )


class CommsChannelClearMessageControlConsumer(CommandConsumer):
    """CommsChannelClearMessage command consumer (CO::CommsChannelControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="CommsChannelClearMessageConsumer",
            command_type=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandType,
            command_topic=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandAckReportType,
            ack_topic=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandStatusType,
            status_topic=UMAA_CO_CommsChannelControl_CommsChannelClearMessageCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.CommsChannelDeleteMessageConfigCommandType import (
    UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandType,
    UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelDeleteMessageConfigAckReportType import (
    UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigAckReportType,
    UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigAckReportTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelDeleteMessageConfigCommandStatusType import (
    UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandStatusType,
    UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandStatusTypeTopic,
)


class CommsChannelDeleteMessageConfigProvider(CommandProvider):
    """CommsChannelDeleteMessageConfig Config provider (CO::CommsChannelConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="CommsChannelDeleteMessageConfigProvider",
            command_type=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandType,
            command_topic=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigAckReportType,
            ack_topic=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandStatusType,
            status_topic=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandStatusTypeTopic,
            source_id=source_id,
        )


class CommsChannelDeleteMessageConfigConsumer(CommandConsumer):
    """CommsChannelDeleteMessageConfig Config consumer (CO::CommsChannelConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="CommsChannelDeleteMessageConfigConsumer",
            command_type=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandType,
            command_topic=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigAckReportType,
            ack_topic=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandStatusType,
            status_topic=UMAA_CO_CommsChannelConfig_CommsChannelDeleteMessageConfigCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.CommsChannelPowerConfigCommandType import (
    UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandType,
    UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelPowerConfigAckReportType import (
    UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigAckReportType,
    UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigAckReportTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelPowerConfigCommandStatusType import (
    UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandStatusType,
    UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandStatusTypeTopic,
)


class CommsChannelPowerConfigProvider(CommandProvider):
    """CommsChannelPowerConfig Config provider (CO::CommsChannelPowerConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="CommsChannelPowerConfigProvider",
            command_type=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandType,
            command_topic=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigAckReportType,
            ack_topic=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandStatusType,
            status_topic=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandStatusTypeTopic,
            source_id=source_id,
        )


class CommsChannelPowerConfigConsumer(CommandConsumer):
    """CommsChannelPowerConfig Config consumer (CO::CommsChannelPowerConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="CommsChannelPowerConfigConsumer",
            command_type=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandType,
            command_topic=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigAckReportType,
            ack_topic=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandStatusType,
            status_topic=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.CommsChannelResetCommandType import (
    UMAA_CO_CommsChannelControl_CommsChannelResetCommandType,
    UMAA_CO_CommsChannelControl_CommsChannelResetCommandTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelResetCommandAckReportType import (
    UMAA_CO_CommsChannelControl_CommsChannelResetCommandAckReportType,
    UMAA_CO_CommsChannelControl_CommsChannelResetCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelResetCommandStatusType import (
    UMAA_CO_CommsChannelControl_CommsChannelResetCommandStatusType,
    UMAA_CO_CommsChannelControl_CommsChannelResetCommandStatusTypeTopic,
)


class CommsChannelResetControlProvider(CommandProvider):
    """CommsChannelReset command provider (CO::CommsChannelControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="CommsChannelResetProvider",
            command_type=UMAA_CO_CommsChannelControl_CommsChannelResetCommandType,
            command_topic=UMAA_CO_CommsChannelControl_CommsChannelResetCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelControl_CommsChannelResetCommandAckReportType,
            ack_topic=UMAA_CO_CommsChannelControl_CommsChannelResetCommandAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelControl_CommsChannelResetCommandStatusType,
            status_topic=UMAA_CO_CommsChannelControl_CommsChannelResetCommandStatusTypeTopic,
            source_id=source_id,
        )


class CommsChannelResetControlConsumer(CommandConsumer):
    """CommsChannelReset command consumer (CO::CommsChannelControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="CommsChannelResetConsumer",
            command_type=UMAA_CO_CommsChannelControl_CommsChannelResetCommandType,
            command_topic=UMAA_CO_CommsChannelControl_CommsChannelResetCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelControl_CommsChannelResetCommandAckReportType,
            ack_topic=UMAA_CO_CommsChannelControl_CommsChannelResetCommandAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelControl_CommsChannelResetCommandStatusType,
            status_topic=UMAA_CO_CommsChannelControl_CommsChannelResetCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.CommsChannelShutdownCommandType import (
    UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandType,
    UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelShutdownCommandAckReportType import (
    UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandAckReportType,
    UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelShutdownCommandStatusType import (
    UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandStatusType,
    UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandStatusTypeTopic,
)


class CommsChannelShutdownControlProvider(CommandProvider):
    """CommsChannelShutdown command provider (CO::CommsChannelControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="CommsChannelShutdownProvider",
            command_type=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandType,
            command_topic=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandAckReportType,
            ack_topic=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandStatusType,
            status_topic=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandStatusTypeTopic,
            source_id=source_id,
        )


class CommsChannelShutdownControlConsumer(CommandConsumer):
    """CommsChannelShutdown command consumer (CO::CommsChannelControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="CommsChannelShutdownConsumer",
            command_type=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandType,
            command_topic=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandAckReportType,
            ack_topic=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandStatusType,
            status_topic=UMAA_CO_CommsChannelControl_CommsChannelShutdownCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.CommsChannelStartupCommandType import (
    UMAA_CO_CommsChannelControl_CommsChannelStartupCommandType,
    UMAA_CO_CommsChannelControl_CommsChannelStartupCommandTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelStartupCommandAckReportType import (
    UMAA_CO_CommsChannelControl_CommsChannelStartupCommandAckReportType,
    UMAA_CO_CommsChannelControl_CommsChannelStartupCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.CommsChannelStartupCommandStatusType import (
    UMAA_CO_CommsChannelControl_CommsChannelStartupCommandStatusType,
    UMAA_CO_CommsChannelControl_CommsChannelStartupCommandStatusTypeTopic,
)


class CommsChannelStartupControlProvider(CommandProvider):
    """CommsChannelStartup command provider (CO::CommsChannelControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="CommsChannelStartupProvider",
            command_type=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandType,
            command_topic=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandAckReportType,
            ack_topic=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandStatusType,
            status_topic=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandStatusTypeTopic,
            source_id=source_id,
        )


class CommsChannelStartupControlConsumer(CommandConsumer):
    """CommsChannelStartup command consumer (CO::CommsChannelControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="CommsChannelStartupConsumer",
            command_type=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandType,
            command_topic=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandTypeTopic,
            ack_type=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandAckReportType,
            ack_topic=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandAckReportTypeTopic,
            status_type=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandStatusType,
            status_topic=UMAA_CO_CommsChannelControl_CommsChannelStartupCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MessageFilterConfigCommandType import (
    UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandType,
    UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandTypeTopic,
)
from rtiumaapy.datamodel.MessageFilterConfigAckReportType import (
    UMAA_CO_MessageFilterConfig_MessageFilterConfigAckReportType,
    UMAA_CO_MessageFilterConfig_MessageFilterConfigAckReportTypeTopic,
)
from rtiumaapy.datamodel.MessageFilterConfigCommandStatusType import (
    UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandStatusType,
    UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandStatusTypeTopic,
)


class MessageFilterConfigProvider(CommandProvider):
    """MessageFilterConfig Config provider (CO::MessageFilterConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MessageFilterConfigProvider",
            command_type=UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandType,
            command_topic=UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandTypeTopic,
            ack_type=UMAA_CO_MessageFilterConfig_MessageFilterConfigAckReportType,
            ack_topic=UMAA_CO_MessageFilterConfig_MessageFilterConfigAckReportTypeTopic,
            status_type=UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandStatusType,
            status_topic=UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandStatusTypeTopic,
            source_id=source_id,
        )


class MessageFilterConfigConsumer(CommandConsumer):
    """MessageFilterConfig Config consumer (CO::MessageFilterConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MessageFilterConfigConsumer",
            command_type=UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandType,
            command_topic=UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandTypeTopic,
            ack_type=UMAA_CO_MessageFilterConfig_MessageFilterConfigAckReportType,
            ack_topic=UMAA_CO_MessageFilterConfig_MessageFilterConfigAckReportTypeTopic,
            status_type=UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandStatusType,
            status_topic=UMAA_CO_MessageFilterConfig_MessageFilterConfigCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.CommsChannelReportType import (
    UMAA_CO_CommsChannelStatus_CommsChannelReportType,
    UMAA_CO_CommsChannelStatus_CommsChannelReportTypeTopic,
)


class CommsChannelReportProvider(ReportProvider):
    """CommsChannel report provider (CO::CommsChannelStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelStatus_CommsChannelReportType,
            report_topic=UMAA_CO_CommsChannelStatus_CommsChannelReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelReportConsumer(ReportConsumer):
    """CommsChannel report consumer (CO::CommsChannelStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelStatus_CommsChannelReportType,
            report_topic=UMAA_CO_CommsChannelStatus_CommsChannelReportTypeTopic,
        )

from rtiumaapy.datamodel.CommsChannelConfigReportType import (
    UMAA_CO_CommsChannelConfig_CommsChannelConfigReportType,
    UMAA_CO_CommsChannelConfig_CommsChannelConfigReportTypeTopic,
)


class CommsChannelConfigReportProvider(ReportProvider):
    """CommsChannelConfig report provider (CO::CommsChannelConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelConfig_CommsChannelConfigReportType,
            report_topic=UMAA_CO_CommsChannelConfig_CommsChannelConfigReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelConfigReportConsumer(ReportConsumer):
    """CommsChannelConfig report consumer (CO::CommsChannelConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelConfigReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelConfig_CommsChannelConfigReportType,
            report_topic=UMAA_CO_CommsChannelConfig_CommsChannelConfigReportTypeTopic,
        )

from rtiumaapy.datamodel.CommsChannelDataEncodingReportType import (
    UMAA_CO_CommsChannelDataEncodingReport_CommsChannelDataEncodingReportType,
    UMAA_CO_CommsChannelDataEncodingReport_CommsChannelDataEncodingReportTypeTopic,
)


class CommsChannelDataEncodingReportProvider(ReportProvider):
    """CommsChannelDataEncoding report provider (CO::CommsChannelDataEncodingReport)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelDataEncodingReport_CommsChannelDataEncodingReportType,
            report_topic=UMAA_CO_CommsChannelDataEncodingReport_CommsChannelDataEncodingReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelDataEncodingReportConsumer(ReportConsumer):
    """CommsChannelDataEncoding report consumer (CO::CommsChannelDataEncodingReport)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelDataEncodingReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelDataEncodingReport_CommsChannelDataEncodingReportType,
            report_topic=UMAA_CO_CommsChannelDataEncodingReport_CommsChannelDataEncodingReportTypeTopic,
        )

from rtiumaapy.datamodel.CommsChannelEnvironmentReportType import (
    UMAA_CO_CommsChannelEnvironmentReport_CommsChannelEnvironmentReportType,
    UMAA_CO_CommsChannelEnvironmentReport_CommsChannelEnvironmentReportTypeTopic,
)


class CommsChannelEnvironmentReportProvider(ReportProvider):
    """CommsChannelEnvironment report provider (CO::CommsChannelEnvironmentReport)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelEnvironmentReport_CommsChannelEnvironmentReportType,
            report_topic=UMAA_CO_CommsChannelEnvironmentReport_CommsChannelEnvironmentReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelEnvironmentReportConsumer(ReportConsumer):
    """CommsChannelEnvironment report consumer (CO::CommsChannelEnvironmentReport)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelEnvironmentReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelEnvironmentReport_CommsChannelEnvironmentReportType,
            report_topic=UMAA_CO_CommsChannelEnvironmentReport_CommsChannelEnvironmentReportTypeTopic,
        )

from rtiumaapy.datamodel.CommsChannelPowerReportType import (
    UMAA_CO_CommsChannelPowerReport_CommsChannelPowerReportType,
    UMAA_CO_CommsChannelPowerReport_CommsChannelPowerReportTypeTopic,
)


class CommsChannelPowerReportProvider(ReportProvider):
    """CommsChannelPower report provider (CO::CommsChannelPowerReport)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelPowerReport_CommsChannelPowerReportType,
            report_topic=UMAA_CO_CommsChannelPowerReport_CommsChannelPowerReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelPowerReportConsumer(ReportConsumer):
    """CommsChannelPower report consumer (CO::CommsChannelPowerReport)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelPowerReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelPowerReport_CommsChannelPowerReportType,
            report_topic=UMAA_CO_CommsChannelPowerReport_CommsChannelPowerReportTypeTopic,
        )

from rtiumaapy.datamodel.CommsChannelPowerConfigReportType import (
    UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigReportType,
    UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigReportTypeTopic,
)


class CommsChannelPowerConfigReportProvider(ReportProvider):
    """CommsChannelPowerConfig report provider (CO::CommsChannelPowerConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigReportType,
            report_topic=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelPowerConfigReportConsumer(ReportConsumer):
    """CommsChannelPowerConfig report consumer (CO::CommsChannelPowerConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelPowerConfigReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigReportType,
            report_topic=UMAA_CO_CommsChannelPowerConfig_CommsChannelPowerConfigReportTypeTopic,
        )

from rtiumaapy.datamodel.CommsChannelReceiverReportType import (
    UMAA_CO_CommsChannelStatus_CommsChannelReceiverReportType,
    UMAA_CO_CommsChannelStatus_CommsChannelReceiverReportTypeTopic,
)


class CommsChannelReceiverReportProvider(ReportProvider):
    """CommsChannelReceiver report provider (CO::CommsChannelStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelStatus_CommsChannelReceiverReportType,
            report_topic=UMAA_CO_CommsChannelStatus_CommsChannelReceiverReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelReceiverReportConsumer(ReportConsumer):
    """CommsChannelReceiver report consumer (CO::CommsChannelStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelReceiverReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelStatus_CommsChannelReceiverReportType,
            report_topic=UMAA_CO_CommsChannelStatus_CommsChannelReceiverReportTypeTopic,
        )

from rtiumaapy.datamodel.CommsChannelReceiverStatisticsReportType import (
    UMAA_CO_CommsChannelStatus_CommsChannelReceiverStatisticsReportType,
    UMAA_CO_CommsChannelStatus_CommsChannelReceiverStatisticsReportTypeTopic,
)


class CommsChannelReceiverStatisticsReportProvider(ReportProvider):
    """CommsChannelReceiverStatistics report provider (CO::CommsChannelStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelStatus_CommsChannelReceiverStatisticsReportType,
            report_topic=UMAA_CO_CommsChannelStatus_CommsChannelReceiverStatisticsReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelReceiverStatisticsReportConsumer(ReportConsumer):
    """CommsChannelReceiverStatistics report consumer (CO::CommsChannelStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelReceiverStatisticsReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelStatus_CommsChannelReceiverStatisticsReportType,
            report_topic=UMAA_CO_CommsChannelStatus_CommsChannelReceiverStatisticsReportTypeTopic,
        )

from rtiumaapy.datamodel.CommsChannelSenderReportType import (
    UMAA_CO_CommsChannelStatus_CommsChannelSenderReportType,
    UMAA_CO_CommsChannelStatus_CommsChannelSenderReportTypeTopic,
)


class CommsChannelSenderReportProvider(ReportProvider):
    """CommsChannelSender report provider (CO::CommsChannelStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelStatus_CommsChannelSenderReportType,
            report_topic=UMAA_CO_CommsChannelStatus_CommsChannelSenderReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelSenderReportConsumer(ReportConsumer):
    """CommsChannelSender report consumer (CO::CommsChannelStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelSenderReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelStatus_CommsChannelSenderReportType,
            report_topic=UMAA_CO_CommsChannelStatus_CommsChannelSenderReportTypeTopic,
        )

from rtiumaapy.datamodel.CommsChannelSenderStatisticsReportType import (
    UMAA_CO_CommsChannelStatus_CommsChannelSenderStatisticsReportType,
    UMAA_CO_CommsChannelStatus_CommsChannelSenderStatisticsReportTypeTopic,
)


class CommsChannelSenderStatisticsReportProvider(ReportProvider):
    """CommsChannelSenderStatistics report provider (CO::CommsChannelStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelStatus_CommsChannelSenderStatisticsReportType,
            report_topic=UMAA_CO_CommsChannelStatus_CommsChannelSenderStatisticsReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelSenderStatisticsReportConsumer(ReportConsumer):
    """CommsChannelSenderStatistics report consumer (CO::CommsChannelStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelSenderStatisticsReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelStatus_CommsChannelSenderStatisticsReportType,
            report_topic=UMAA_CO_CommsChannelStatus_CommsChannelSenderStatisticsReportTypeTopic,
        )

from rtiumaapy.datamodel.CommsChannelSpecsReportType import (
    UMAA_CO_CommsChannelSpecs_CommsChannelSpecsReportType,
    UMAA_CO_CommsChannelSpecs_CommsChannelSpecsReportTypeTopic,
)


class CommsChannelSpecsReportProvider(ReportProvider):
    """CommsChannelSpecs report provider (CO::CommsChannelSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelSpecs_CommsChannelSpecsReportType,
            report_topic=UMAA_CO_CommsChannelSpecs_CommsChannelSpecsReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelSpecsReportConsumer(ReportConsumer):
    """CommsChannelSpecs report consumer (CO::CommsChannelSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelSpecsReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelSpecs_CommsChannelSpecsReportType,
            report_topic=UMAA_CO_CommsChannelSpecs_CommsChannelSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.CommsChannelSystemTimeReportType import (
    UMAA_CO_CommsChannelSystemTimeReport_CommsChannelSystemTimeReportType,
    UMAA_CO_CommsChannelSystemTimeReport_CommsChannelSystemTimeReportTypeTopic,
)


class CommsChannelSystemTimeReportProvider(ReportProvider):
    """CommsChannelSystemTime report provider (CO::CommsChannelSystemTimeReport)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelSystemTimeReport_CommsChannelSystemTimeReportType,
            report_topic=UMAA_CO_CommsChannelSystemTimeReport_CommsChannelSystemTimeReportTypeTopic,
            key_holder=key_holder,
        )


class CommsChannelSystemTimeReportConsumer(ReportConsumer):
    """CommsChannelSystemTime report consumer (CO::CommsChannelSystemTimeReport)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CommsChannelSystemTimeReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_CO_CommsChannelSystemTimeReport_CommsChannelSystemTimeReportType,
            report_topic=UMAA_CO_CommsChannelSystemTimeReport_CommsChannelSystemTimeReportTypeTopic,
        )
