

/*
WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.

This file was generated from GlobalRegularPolygonStateType.idl
using RTI Code Generator (rtiddsgen) version 4.2.0.
The rtiddsgen tool is part of the RTI Connext DDS distribution.
For more information, type 'rtiddsgen -help' at a command shell
or consult the Code Generator User's Manual.
*/

#ifndef GlobalRegularPolygonStateType_335007902_h
#define GlobalRegularPolygonStateType_335007902_h

#ifndef NDDS_STANDALONE_TYPE
#ifndef ndds_cpp_h
#include "ndds/ndds_cpp.h"
#endif
#include "rti/xcdr/Interpreter.hpp"
#else
#include "ndds_standalone_type.h"
#endif

#include "UMAA/MO/GlobalRegularPolygonState/GlobalRegularPolygonPatternType.h"
#include "UMAA/MO/GlobalRegularPolygonState/GlobalRegularPolygonTransitType.h"

typedef enum UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors
{
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_GLOBALREGULARPOLYGONTRANSITTYPE_SELECT , 
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_GLOBALREGULARPOLYGONPATTERNTYPE_SELECT 
} UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors;
#if (defined(RTI_WIN32) || defined (RTI_WINCE) || defined(RTI_INTIME)) && defined(NDDS_USER_DLL_EXPORT)
/* If the code is building on Windows, start exporting symbols.
*/
#undef NDDSUSERDllExport
#define NDDSUSERDllExport __declspec(dllexport)
#endif

#ifndef NDDS_STANDALONE_TYPE
NDDSUSERDllExport DDS_TypeCode * UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_get_typecode(void); /* Type code */
NDDSUSERDllExport RTIXCdrTypePlugin *UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_get_type_plugin_info(void);
NDDSUSERDllExport RTIXCdrSampleAccessInfo *UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_get_sample_access_info(void);
NDDSUSERDllExport RTIXCdrSampleAccessInfo *UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_get_sample_seq_access_info(void);
#endif
DDS_SEQUENCE(UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_SelectorsSeq, UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors);

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_initialize(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors* self);

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_initialize_ex(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors* self,RTIBool allocatePointers,RTIBool allocateMemory);

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_initialize_w_params(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors* self,
    const struct DDS_TypeAllocationParams_t * allocParams);  

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_finalize_w_return(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors* self);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_finalize(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors* self);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_finalize_ex(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors* self,RTIBool deletePointers);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_finalize_w_params(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors* self,
    const struct DDS_TypeDeallocationParams_t * deallocParams);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_finalize_optional_members(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors* self, RTIBool deletePointers);  

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors_copy(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors* dst,
    const UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors* src);

#if (defined(RTI_WIN32) || defined (RTI_WINCE) || defined(RTI_INTIME)) && defined(NDDS_USER_DLL_EXPORT)
/* If the code is building on Windows, stop exporting symbols.
*/
#undef NDDSUSERDllExport
#define NDDSUSERDllExport
#endif

extern "C" {

    extern const char *UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_UnionTYPENAME;

}

struct UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_UnionSeq;
#ifndef NDDS_STANDALONE_TYPE
class UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_UnionTypeSupport;
class UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_UnionDataWriter;
class UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_UnionDataReader;
#endif

typedef struct UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union
{
    typedef struct UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_UnionSeq Seq;
    #ifndef NDDS_STANDALONE_TYPE
    typedef UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_UnionTypeSupport TypeSupport;
    typedef UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_UnionDataWriter DataWriter;
    typedef UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_UnionDataReader DataReader;
    #endif

    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Selectors _d;
    struct UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_u 
    {

        UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonTransitType   GlobalRegularPolygonTransitType_data ;
        UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonPatternType   GlobalRegularPolygonPatternType_data ;
    }_u;

} UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union ;
#if (defined(RTI_WIN32) || defined (RTI_WINCE) || defined(RTI_INTIME)) && defined(NDDS_USER_DLL_EXPORT)
/* If the code is building on Windows, start exporting symbols.
*/
#undef NDDSUSERDllExport
#define NDDSUSERDllExport __declspec(dllexport)
#endif

#ifndef NDDS_STANDALONE_TYPE
NDDSUSERDllExport DDS_TypeCode * UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_get_typecode(void); /* Type code */
NDDSUSERDllExport RTIXCdrTypePlugin *UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_get_type_plugin_info(void);
NDDSUSERDllExport RTIXCdrSampleAccessInfo *UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_get_sample_access_info(void);
NDDSUSERDllExport RTIXCdrSampleAccessInfo *UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_get_sample_seq_access_info(void);
#endif
DDS_SEQUENCE(UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_UnionSeq, UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union);

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_initialize(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union* self);

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_initialize_ex(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union* self,RTIBool allocatePointers,RTIBool allocateMemory);

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_initialize_w_params(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union* self,
    const struct DDS_TypeAllocationParams_t * allocParams);  

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_finalize_w_return(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union* self);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_finalize(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union* self);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_finalize_ex(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union* self,RTIBool deletePointers);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_finalize_w_params(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union* self,
    const struct DDS_TypeDeallocationParams_t * deallocParams);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_finalize_optional_members(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union* self, RTIBool deletePointers);  

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_copy(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union* dst,
    const UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union* src);

NDDSUSERDllExport
DDS_LongLong UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union_getDefaultDiscriminator(void);

#if (defined(RTI_WIN32) || defined (RTI_WINCE) || defined(RTI_INTIME)) && defined(NDDS_USER_DLL_EXPORT)
/* If the code is building on Windows, stop exporting symbols.
*/
#undef NDDSUSERDllExport
#define NDDSUSERDllExport
#endif

extern "C" {

    extern const char *UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateTypeTYPENAME;

}

struct UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateTypeSeq;
#ifndef NDDS_STANDALONE_TYPE
class UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateTypeTypeSupport;
class UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateTypeDataWriter;
class UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateTypeDataReader;
#endif
class UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType 
{
  public:
    typedef struct UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateTypeSeq Seq;
    #ifndef NDDS_STANDALONE_TYPE
    typedef UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateTypeTypeSupport TypeSupport;
    typedef UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateTypeDataWriter DataWriter;
    typedef UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateTypeDataReader DataReader;
    #endif

    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union   GlobalRegularPolygonStateType_subtypes ;

};
#if (defined(RTI_WIN32) || defined (RTI_WINCE) || defined(RTI_INTIME)) && defined(NDDS_USER_DLL_EXPORT)
/* If the code is building on Windows, start exporting symbols.
*/
#undef NDDSUSERDllExport
#define NDDSUSERDllExport __declspec(dllexport)
#endif

#ifndef NDDS_STANDALONE_TYPE
NDDSUSERDllExport DDS_TypeCode * UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_get_typecode(void); /* Type code */
NDDSUSERDllExport RTIXCdrTypePlugin *UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_get_type_plugin_info(void);
NDDSUSERDllExport RTIXCdrSampleAccessInfo *UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_get_sample_access_info(void);
NDDSUSERDllExport RTIXCdrSampleAccessInfo *UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_get_sample_seq_access_info(void);
#endif
DDS_SEQUENCE(UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateTypeSeq, UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType);

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_initialize(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType* self);

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_initialize_ex(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType* self,RTIBool allocatePointers,RTIBool allocateMemory);

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_initialize_w_params(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType* self,
    const struct DDS_TypeAllocationParams_t * allocParams);  

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_finalize_w_return(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType* self);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_finalize(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType* self);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_finalize_ex(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType* self,RTIBool deletePointers);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_finalize_w_params(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType* self,
    const struct DDS_TypeDeallocationParams_t * deallocParams);

NDDSUSERDllExport
void UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_finalize_optional_members(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType* self, RTIBool deletePointers);  

NDDSUSERDllExport
RTIBool UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_copy(
    UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType* dst,
    const UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType* src);

#if (defined(RTI_WIN32) || defined (RTI_WINCE) || defined(RTI_INTIME)) && defined(NDDS_USER_DLL_EXPORT)
/* If the code is building on Windows, stop exporting symbols.
*/
#undef NDDSUSERDllExport
#define NDDSUSERDllExport
#endif

#ifndef NDDS_STANDALONE_TYPE
namespace rti { 
    namespace xcdr {
        template <>
        struct type_code< UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType_Specializations_GlobalRegularPolygonStateType_Union> {
            static const RTIXCdrTypeCode * get();
        };

        template <>
        struct type_code< UMAA_MO_GlobalRegularPolygonState_GlobalRegularPolygonStateType> {
            static const RTIXCdrTypeCode * get();
        };

    } 
}

#endif

#endif /* GlobalRegularPolygonStateType */

