"""rtiumaapy.services.so — System Operations service classes.

Auto-generated by tools/generate_services.py. Do not edit manually.
"""

from __future__ import annotations

from rtiumaapy.command_provider import CommandProvider
from rtiumaapy.command_consumer import CommandConsumer
from rtiumaapy.report_provider import ReportProvider
from rtiumaapy.report_consumer import ReportConsumer
from rtiumaapy.dds_context import DDSContext

__all__ = [
    "BITConfigConsumer",
    "BITConfigProvider",
    "BITConfigReportConsumer",
    "BITConfigReportProvider",
    "BITControlConsumer",
    "BITControlProvider",
    "BITReportConsumer",
    "BITReportProvider",
    "BITSpecsReportConsumer",
    "BITSpecsReportProvider",
    "ClearDataControlConsumer",
    "ClearDataControlProvider",
    "ClientIDReportConsumer",
    "ClientIDReportProvider",
    "ControlSystemIDControlConsumer",
    "ControlSystemIDControlProvider",
    "ControlSystemIDReportConsumer",
    "ControlSystemIDReportProvider",
    "EmitterControlConsumer",
    "EmitterControlProvider",
    "EmitterPresetConfigConsumer",
    "EmitterPresetConfigProvider",
    "EmitterPresetConfigReportConsumer",
    "EmitterPresetConfigReportProvider",
    "EmitterPresetControlConsumer",
    "EmitterPresetControlProvider",
    "EmitterPresetReportConsumer",
    "EmitterPresetReportProvider",
    "EmitterReportConsumer",
    "EmitterReportProvider",
    "EmitterSpecsReportConsumer",
    "EmitterSpecsReportProvider",
    "FileSystemReportConsumer",
    "FileSystemReportProvider",
    "HealthReportConsumer",
    "HealthReportProvider",
    "HeartbeatPulseReportConsumer",
    "HeartbeatPulseReportProvider",
    "LogReportConsumer",
    "LogReportProvider",
    "MemoryReportConsumer",
    "MemoryReportProvider",
    "ProcessingUnitReportConsumer",
    "ProcessingUnitReportProvider",
    "RecordingSpecsReportConsumer",
    "RecordingSpecsReportProvider",
    "RecordingStatusReportConsumer",
    "RecordingStatusReportProvider",
    "ResourceAllocationConfigReportConsumer",
    "ResourceAllocationConfigReportProvider",
    "ResourceAllocationControlConsumer",
    "ResourceAllocationControlProvider",
    "ResourceAllocationPriorityControlConsumer",
    "ResourceAllocationPriorityControlProvider",
    "ResourceAllocationPriorityReportConsumer",
    "ResourceAllocationPriorityReportProvider",
    "ResourceAllocationReportConsumer",
    "ResourceAllocationReportProvider",
    "ResourceAuthorizationReportConsumer",
    "ResourceAuthorizationReportProvider",
    "SubsystemIDReportConsumer",
    "SubsystemIDReportProvider",
    "SyncDataControlConsumer",
    "SyncDataControlProvider",
    "TamperDetectionControlConsumer",
    "TamperDetectionControlProvider",
    "TamperDetectionReportConsumer",
    "TamperDetectionReportProvider",
    "VehicleIDReportConsumer",
    "VehicleIDReportProvider",
]

from rtiumaapy.datamodel.BITCommandType import (
    UMAA_SO_BITControl_BITCommandType,
    UMAA_SO_BITControl_BITCommandTypeTopic,
)
from rtiumaapy.datamodel.BITCommandAckReportType import (
    UMAA_SO_BITControl_BITCommandAckReportType,
    UMAA_SO_BITControl_BITCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.BITCommandStatusType import (
    UMAA_SO_BITControl_BITCommandStatusType,
    UMAA_SO_BITControl_BITCommandStatusTypeTopic,
)
from rtiumaapy.datamodel.BITExecutionStatusReportType import (
    UMAA_SO_BITControl_BITExecutionStatusReportType,
    UMAA_SO_BITControl_BITExecutionStatusReportTypeTopic,
)


class BITControlProvider(CommandProvider):
    """BIT command provider (SO::BITControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="BIT",
            command_type=UMAA_SO_BITControl_BITCommandType,
            command_topic=UMAA_SO_BITControl_BITCommandTypeTopic,
            ack_type=UMAA_SO_BITControl_BITCommandAckReportType,
            ack_topic=UMAA_SO_BITControl_BITCommandAckReportTypeTopic,
            status_type=UMAA_SO_BITControl_BITCommandStatusType,
            status_topic=UMAA_SO_BITControl_BITCommandStatusTypeTopic,
            exec_status_type=UMAA_SO_BITControl_BITExecutionStatusReportType,
            exec_status_topic=UMAA_SO_BITControl_BITExecutionStatusReportTypeTopic,
            source_id=source_id,
        )


class BITControlConsumer(CommandConsumer):
    """BIT command consumer (SO::BITControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="BIT",
            command_type=UMAA_SO_BITControl_BITCommandType,
            command_topic=UMAA_SO_BITControl_BITCommandTypeTopic,
            ack_type=UMAA_SO_BITControl_BITCommandAckReportType,
            ack_topic=UMAA_SO_BITControl_BITCommandAckReportTypeTopic,
            status_type=UMAA_SO_BITControl_BITCommandStatusType,
            status_topic=UMAA_SO_BITControl_BITCommandStatusTypeTopic,
            exec_status_type=UMAA_SO_BITControl_BITExecutionStatusReportType,
            exec_status_topic=UMAA_SO_BITControl_BITExecutionStatusReportTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.BITConfigCommandType import (
    UMAA_SO_BITConfig_BITConfigCommandType,
    UMAA_SO_BITConfig_BITConfigCommandTypeTopic,
)
from rtiumaapy.datamodel.BITConfigAckReportType import (
    UMAA_SO_BITConfig_BITConfigAckReportType,
    UMAA_SO_BITConfig_BITConfigAckReportTypeTopic,
)
from rtiumaapy.datamodel.BITConfigCommandStatusType import (
    UMAA_SO_BITConfig_BITConfigCommandStatusType,
    UMAA_SO_BITConfig_BITConfigCommandStatusTypeTopic,
)


class BITConfigProvider(CommandProvider):
    """BITConfig Config provider (SO::BITConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="BITConfig",
            command_type=UMAA_SO_BITConfig_BITConfigCommandType,
            command_topic=UMAA_SO_BITConfig_BITConfigCommandTypeTopic,
            ack_type=UMAA_SO_BITConfig_BITConfigAckReportType,
            ack_topic=UMAA_SO_BITConfig_BITConfigAckReportTypeTopic,
            status_type=UMAA_SO_BITConfig_BITConfigCommandStatusType,
            status_topic=UMAA_SO_BITConfig_BITConfigCommandStatusTypeTopic,
            source_id=source_id,
        )


class BITConfigConsumer(CommandConsumer):
    """BITConfig Config consumer (SO::BITConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="BITConfig",
            command_type=UMAA_SO_BITConfig_BITConfigCommandType,
            command_topic=UMAA_SO_BITConfig_BITConfigCommandTypeTopic,
            ack_type=UMAA_SO_BITConfig_BITConfigAckReportType,
            ack_topic=UMAA_SO_BITConfig_BITConfigAckReportTypeTopic,
            status_type=UMAA_SO_BITConfig_BITConfigCommandStatusType,
            status_topic=UMAA_SO_BITConfig_BITConfigCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ClearDataCommandType import (
    UMAA_SO_ClearDataControl_ClearDataCommandType,
    UMAA_SO_ClearDataControl_ClearDataCommandTypeTopic,
)
from rtiumaapy.datamodel.ClearDataCommandAckReportType import (
    UMAA_SO_ClearDataControl_ClearDataCommandAckReportType,
    UMAA_SO_ClearDataControl_ClearDataCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.ClearDataCommandStatusType import (
    UMAA_SO_ClearDataControl_ClearDataCommandStatusType,
    UMAA_SO_ClearDataControl_ClearDataCommandStatusTypeTopic,
)


class ClearDataControlProvider(CommandProvider):
    """ClearData command provider (SO::ClearDataControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ClearData",
            command_type=UMAA_SO_ClearDataControl_ClearDataCommandType,
            command_topic=UMAA_SO_ClearDataControl_ClearDataCommandTypeTopic,
            ack_type=UMAA_SO_ClearDataControl_ClearDataCommandAckReportType,
            ack_topic=UMAA_SO_ClearDataControl_ClearDataCommandAckReportTypeTopic,
            status_type=UMAA_SO_ClearDataControl_ClearDataCommandStatusType,
            status_topic=UMAA_SO_ClearDataControl_ClearDataCommandStatusTypeTopic,
            source_id=source_id,
        )


class ClearDataControlConsumer(CommandConsumer):
    """ClearData command consumer (SO::ClearDataControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ClearData",
            command_type=UMAA_SO_ClearDataControl_ClearDataCommandType,
            command_topic=UMAA_SO_ClearDataControl_ClearDataCommandTypeTopic,
            ack_type=UMAA_SO_ClearDataControl_ClearDataCommandAckReportType,
            ack_topic=UMAA_SO_ClearDataControl_ClearDataCommandAckReportTypeTopic,
            status_type=UMAA_SO_ClearDataControl_ClearDataCommandStatusType,
            status_topic=UMAA_SO_ClearDataControl_ClearDataCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ControlSystemIDCommandType import (
    UMAA_SO_ControlSystemID_ControlSystemIDCommandType,
    UMAA_SO_ControlSystemID_ControlSystemIDCommandTypeTopic,
)
from rtiumaapy.datamodel.ControlSystemIDCommandAckReportType import (
    UMAA_SO_ControlSystemID_ControlSystemIDCommandAckReportType,
    UMAA_SO_ControlSystemID_ControlSystemIDCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.ControlSystemIDCommandStatusType import (
    UMAA_SO_ControlSystemID_ControlSystemIDCommandStatusType,
    UMAA_SO_ControlSystemID_ControlSystemIDCommandStatusTypeTopic,
)


class ControlSystemIDControlProvider(CommandProvider):
    """ControlSystemID command provider (SO::ControlSystemID)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ControlSystemID",
            command_type=UMAA_SO_ControlSystemID_ControlSystemIDCommandType,
            command_topic=UMAA_SO_ControlSystemID_ControlSystemIDCommandTypeTopic,
            ack_type=UMAA_SO_ControlSystemID_ControlSystemIDCommandAckReportType,
            ack_topic=UMAA_SO_ControlSystemID_ControlSystemIDCommandAckReportTypeTopic,
            status_type=UMAA_SO_ControlSystemID_ControlSystemIDCommandStatusType,
            status_topic=UMAA_SO_ControlSystemID_ControlSystemIDCommandStatusTypeTopic,
            source_id=source_id,
        )


class ControlSystemIDControlConsumer(CommandConsumer):
    """ControlSystemID command consumer (SO::ControlSystemID)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ControlSystemID",
            command_type=UMAA_SO_ControlSystemID_ControlSystemIDCommandType,
            command_topic=UMAA_SO_ControlSystemID_ControlSystemIDCommandTypeTopic,
            ack_type=UMAA_SO_ControlSystemID_ControlSystemIDCommandAckReportType,
            ack_topic=UMAA_SO_ControlSystemID_ControlSystemIDCommandAckReportTypeTopic,
            status_type=UMAA_SO_ControlSystemID_ControlSystemIDCommandStatusType,
            status_topic=UMAA_SO_ControlSystemID_ControlSystemIDCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.EmitterCommandType import (
    UMAA_SO_EmitterControl_EmitterCommandType,
    UMAA_SO_EmitterControl_EmitterCommandTypeTopic,
)
from rtiumaapy.datamodel.EmitterCommandAckReportType import (
    UMAA_SO_EmitterControl_EmitterCommandAckReportType,
    UMAA_SO_EmitterControl_EmitterCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.EmitterCommandStatusType import (
    UMAA_SO_EmitterControl_EmitterCommandStatusType,
    UMAA_SO_EmitterControl_EmitterCommandStatusTypeTopic,
)


class EmitterControlProvider(CommandProvider):
    """Emitter command provider (SO::EmitterControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="Emitter",
            command_type=UMAA_SO_EmitterControl_EmitterCommandType,
            command_topic=UMAA_SO_EmitterControl_EmitterCommandTypeTopic,
            ack_type=UMAA_SO_EmitterControl_EmitterCommandAckReportType,
            ack_topic=UMAA_SO_EmitterControl_EmitterCommandAckReportTypeTopic,
            status_type=UMAA_SO_EmitterControl_EmitterCommandStatusType,
            status_topic=UMAA_SO_EmitterControl_EmitterCommandStatusTypeTopic,
            source_id=source_id,
        )


class EmitterControlConsumer(CommandConsumer):
    """Emitter command consumer (SO::EmitterControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="Emitter",
            command_type=UMAA_SO_EmitterControl_EmitterCommandType,
            command_topic=UMAA_SO_EmitterControl_EmitterCommandTypeTopic,
            ack_type=UMAA_SO_EmitterControl_EmitterCommandAckReportType,
            ack_topic=UMAA_SO_EmitterControl_EmitterCommandAckReportTypeTopic,
            status_type=UMAA_SO_EmitterControl_EmitterCommandStatusType,
            status_topic=UMAA_SO_EmitterControl_EmitterCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.EmitterPresetCommandType import (
    UMAA_SO_EmitterPresetControl_EmitterPresetCommandType,
    UMAA_SO_EmitterPresetControl_EmitterPresetCommandTypeTopic,
)
from rtiumaapy.datamodel.EmitterPresetCommandAckReportType import (
    UMAA_SO_EmitterPresetControl_EmitterPresetCommandAckReportType,
    UMAA_SO_EmitterPresetControl_EmitterPresetCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.EmitterPresetCommandStatusType import (
    UMAA_SO_EmitterPresetControl_EmitterPresetCommandStatusType,
    UMAA_SO_EmitterPresetControl_EmitterPresetCommandStatusTypeTopic,
)


class EmitterPresetControlProvider(CommandProvider):
    """EmitterPreset command provider (SO::EmitterPresetControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="EmitterPreset",
            command_type=UMAA_SO_EmitterPresetControl_EmitterPresetCommandType,
            command_topic=UMAA_SO_EmitterPresetControl_EmitterPresetCommandTypeTopic,
            ack_type=UMAA_SO_EmitterPresetControl_EmitterPresetCommandAckReportType,
            ack_topic=UMAA_SO_EmitterPresetControl_EmitterPresetCommandAckReportTypeTopic,
            status_type=UMAA_SO_EmitterPresetControl_EmitterPresetCommandStatusType,
            status_topic=UMAA_SO_EmitterPresetControl_EmitterPresetCommandStatusTypeTopic,
            source_id=source_id,
        )


class EmitterPresetControlConsumer(CommandConsumer):
    """EmitterPreset command consumer (SO::EmitterPresetControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="EmitterPreset",
            command_type=UMAA_SO_EmitterPresetControl_EmitterPresetCommandType,
            command_topic=UMAA_SO_EmitterPresetControl_EmitterPresetCommandTypeTopic,
            ack_type=UMAA_SO_EmitterPresetControl_EmitterPresetCommandAckReportType,
            ack_topic=UMAA_SO_EmitterPresetControl_EmitterPresetCommandAckReportTypeTopic,
            status_type=UMAA_SO_EmitterPresetControl_EmitterPresetCommandStatusType,
            status_topic=UMAA_SO_EmitterPresetControl_EmitterPresetCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.EmitterPresetConfigCommandType import (
    UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandType,
    UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandTypeTopic,
)
from rtiumaapy.datamodel.EmitterPresetConfigAckReportType import (
    UMAA_SO_EmitterPresetConfig_EmitterPresetConfigAckReportType,
    UMAA_SO_EmitterPresetConfig_EmitterPresetConfigAckReportTypeTopic,
)
from rtiumaapy.datamodel.EmitterPresetConfigCommandStatusType import (
    UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandStatusType,
    UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandStatusTypeTopic,
)


class EmitterPresetConfigProvider(CommandProvider):
    """EmitterPresetConfig Config provider (SO::EmitterPresetConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="EmitterPresetConfig",
            command_type=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandType,
            command_topic=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandTypeTopic,
            ack_type=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigAckReportType,
            ack_topic=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigAckReportTypeTopic,
            status_type=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandStatusType,
            status_topic=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandStatusTypeTopic,
            source_id=source_id,
        )


class EmitterPresetConfigConsumer(CommandConsumer):
    """EmitterPresetConfig Config consumer (SO::EmitterPresetConfig)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="EmitterPresetConfig",
            command_type=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandType,
            command_topic=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandTypeTopic,
            ack_type=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigAckReportType,
            ack_topic=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigAckReportTypeTopic,
            status_type=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandStatusType,
            status_topic=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ResourceAllocationCommandType import (
    UMAA_SO_ResourceAllocation_ResourceAllocationCommandType,
    UMAA_SO_ResourceAllocation_ResourceAllocationCommandTypeTopic,
)
from rtiumaapy.datamodel.ResourceAllocationCommandAckReportType import (
    UMAA_SO_ResourceAllocation_ResourceAllocationCommandAckReportType,
    UMAA_SO_ResourceAllocation_ResourceAllocationCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.ResourceAllocationCommandStatusType import (
    UMAA_SO_ResourceAllocation_ResourceAllocationCommandStatusType,
    UMAA_SO_ResourceAllocation_ResourceAllocationCommandStatusTypeTopic,
)


class ResourceAllocationControlProvider(CommandProvider):
    """ResourceAllocation command provider (SO::ResourceAllocation)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ResourceAllocation",
            command_type=UMAA_SO_ResourceAllocation_ResourceAllocationCommandType,
            command_topic=UMAA_SO_ResourceAllocation_ResourceAllocationCommandTypeTopic,
            ack_type=UMAA_SO_ResourceAllocation_ResourceAllocationCommandAckReportType,
            ack_topic=UMAA_SO_ResourceAllocation_ResourceAllocationCommandAckReportTypeTopic,
            status_type=UMAA_SO_ResourceAllocation_ResourceAllocationCommandStatusType,
            status_topic=UMAA_SO_ResourceAllocation_ResourceAllocationCommandStatusTypeTopic,
            source_id=source_id,
        )


class ResourceAllocationControlConsumer(CommandConsumer):
    """ResourceAllocation command consumer (SO::ResourceAllocation)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ResourceAllocation",
            command_type=UMAA_SO_ResourceAllocation_ResourceAllocationCommandType,
            command_topic=UMAA_SO_ResourceAllocation_ResourceAllocationCommandTypeTopic,
            ack_type=UMAA_SO_ResourceAllocation_ResourceAllocationCommandAckReportType,
            ack_topic=UMAA_SO_ResourceAllocation_ResourceAllocationCommandAckReportTypeTopic,
            status_type=UMAA_SO_ResourceAllocation_ResourceAllocationCommandStatusType,
            status_topic=UMAA_SO_ResourceAllocation_ResourceAllocationCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ResourceAllocationPriorityCommandType import (
    UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandType,
    UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandTypeTopic,
)
from rtiumaapy.datamodel.ResourceAllocationPriorityCommandAckReportType import (
    UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandAckReportType,
    UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.ResourceAllocationPriorityCommandStatusType import (
    UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandStatusType,
    UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandStatusTypeTopic,
)


class ResourceAllocationPriorityControlProvider(CommandProvider):
    """ResourceAllocationPriority command provider (SO::ResourceAllocation)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ResourceAllocationPriority",
            command_type=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandType,
            command_topic=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandTypeTopic,
            ack_type=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandAckReportType,
            ack_topic=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandAckReportTypeTopic,
            status_type=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandStatusType,
            status_topic=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandStatusTypeTopic,
            source_id=source_id,
        )


class ResourceAllocationPriorityControlConsumer(CommandConsumer):
    """ResourceAllocationPriority command consumer (SO::ResourceAllocation)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ResourceAllocationPriority",
            command_type=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandType,
            command_topic=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandTypeTopic,
            ack_type=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandAckReportType,
            ack_topic=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandAckReportTypeTopic,
            status_type=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandStatusType,
            status_topic=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.SyncDataCommandType import (
    UMAA_SO_SyncDataControl_SyncDataCommandType,
    UMAA_SO_SyncDataControl_SyncDataCommandTypeTopic,
)
from rtiumaapy.datamodel.SyncDataCommandAckReportType import (
    UMAA_SO_SyncDataControl_SyncDataCommandAckReportType,
    UMAA_SO_SyncDataControl_SyncDataCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.SyncDataCommandStatusType import (
    UMAA_SO_SyncDataControl_SyncDataCommandStatusType,
    UMAA_SO_SyncDataControl_SyncDataCommandStatusTypeTopic,
)


class SyncDataControlProvider(CommandProvider):
    """SyncData command provider (SO::SyncDataControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="SyncData",
            command_type=UMAA_SO_SyncDataControl_SyncDataCommandType,
            command_topic=UMAA_SO_SyncDataControl_SyncDataCommandTypeTopic,
            ack_type=UMAA_SO_SyncDataControl_SyncDataCommandAckReportType,
            ack_topic=UMAA_SO_SyncDataControl_SyncDataCommandAckReportTypeTopic,
            status_type=UMAA_SO_SyncDataControl_SyncDataCommandStatusType,
            status_topic=UMAA_SO_SyncDataControl_SyncDataCommandStatusTypeTopic,
            source_id=source_id,
        )


class SyncDataControlConsumer(CommandConsumer):
    """SyncData command consumer (SO::SyncDataControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="SyncData",
            command_type=UMAA_SO_SyncDataControl_SyncDataCommandType,
            command_topic=UMAA_SO_SyncDataControl_SyncDataCommandTypeTopic,
            ack_type=UMAA_SO_SyncDataControl_SyncDataCommandAckReportType,
            ack_topic=UMAA_SO_SyncDataControl_SyncDataCommandAckReportTypeTopic,
            status_type=UMAA_SO_SyncDataControl_SyncDataCommandStatusType,
            status_topic=UMAA_SO_SyncDataControl_SyncDataCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.TamperDetectionCommandType import (
    UMAA_SO_TamperDetectionControl_TamperDetectionCommandType,
    UMAA_SO_TamperDetectionControl_TamperDetectionCommandTypeTopic,
)
from rtiumaapy.datamodel.TamperDetectionCommandAckReportType import (
    UMAA_SO_TamperDetectionControl_TamperDetectionCommandAckReportType,
    UMAA_SO_TamperDetectionControl_TamperDetectionCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.TamperDetectionCommandStatusType import (
    UMAA_SO_TamperDetectionControl_TamperDetectionCommandStatusType,
    UMAA_SO_TamperDetectionControl_TamperDetectionCommandStatusTypeTopic,
)


class TamperDetectionControlProvider(CommandProvider):
    """TamperDetection command provider (SO::TamperDetectionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="TamperDetection",
            command_type=UMAA_SO_TamperDetectionControl_TamperDetectionCommandType,
            command_topic=UMAA_SO_TamperDetectionControl_TamperDetectionCommandTypeTopic,
            ack_type=UMAA_SO_TamperDetectionControl_TamperDetectionCommandAckReportType,
            ack_topic=UMAA_SO_TamperDetectionControl_TamperDetectionCommandAckReportTypeTopic,
            status_type=UMAA_SO_TamperDetectionControl_TamperDetectionCommandStatusType,
            status_topic=UMAA_SO_TamperDetectionControl_TamperDetectionCommandStatusTypeTopic,
            source_id=source_id,
        )


class TamperDetectionControlConsumer(CommandConsumer):
    """TamperDetection command consumer (SO::TamperDetectionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="TamperDetection",
            command_type=UMAA_SO_TamperDetectionControl_TamperDetectionCommandType,
            command_topic=UMAA_SO_TamperDetectionControl_TamperDetectionCommandTypeTopic,
            ack_type=UMAA_SO_TamperDetectionControl_TamperDetectionCommandAckReportType,
            ack_topic=UMAA_SO_TamperDetectionControl_TamperDetectionCommandAckReportTypeTopic,
            status_type=UMAA_SO_TamperDetectionControl_TamperDetectionCommandStatusType,
            status_topic=UMAA_SO_TamperDetectionControl_TamperDetectionCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.BITReportType import (
    UMAA_SO_BITReport_BITReportType,
    UMAA_SO_BITReport_BITReportTypeTopic,
)


class BITReportProvider(ReportProvider):
    """BIT report provider (SO::BITReport)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_BITReport_BITReportType,
            report_topic=UMAA_SO_BITReport_BITReportTypeTopic,
            key_holder=key_holder,
        )


class BITReportConsumer(ReportConsumer):
    """BIT report consumer (SO::BITReport)."""

    def __init__(self, ctx: DDSContext, service_name: str = "BITReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_BITReport_BITReportType,
            report_topic=UMAA_SO_BITReport_BITReportTypeTopic,
        )

from rtiumaapy.datamodel.BITConfigReportType import (
    UMAA_SO_BITConfig_BITConfigReportType,
    UMAA_SO_BITConfig_BITConfigReportTypeTopic,
)


class BITConfigReportProvider(ReportProvider):
    """BITConfig report provider (SO::BITConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_BITConfig_BITConfigReportType,
            report_topic=UMAA_SO_BITConfig_BITConfigReportTypeTopic,
            key_holder=key_holder,
        )


class BITConfigReportConsumer(ReportConsumer):
    """BITConfig report consumer (SO::BITConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str = "BITConfigReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_BITConfig_BITConfigReportType,
            report_topic=UMAA_SO_BITConfig_BITConfigReportTypeTopic,
        )

from rtiumaapy.datamodel.BITSpecsReportType import (
    UMAA_SO_BITSpecs_BITSpecsReportType,
    UMAA_SO_BITSpecs_BITSpecsReportTypeTopic,
)


class BITSpecsReportProvider(ReportProvider):
    """BITSpecs report provider (SO::BITSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_BITSpecs_BITSpecsReportType,
            report_topic=UMAA_SO_BITSpecs_BITSpecsReportTypeTopic,
            key_holder=key_holder,
        )


class BITSpecsReportConsumer(ReportConsumer):
    """BITSpecs report consumer (SO::BITSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: str = "BITSpecsReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_BITSpecs_BITSpecsReportType,
            report_topic=UMAA_SO_BITSpecs_BITSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.ClientIDReportType import (
    UMAA_SO_ControlSystemID_ClientIDReportType,
    UMAA_SO_ControlSystemID_ClientIDReportTypeTopic,
)


class ClientIDReportProvider(ReportProvider):
    """ClientID report provider (SO::ControlSystemID)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ControlSystemID_ClientIDReportType,
            report_topic=UMAA_SO_ControlSystemID_ClientIDReportTypeTopic,
            key_holder=key_holder,
        )


class ClientIDReportConsumer(ReportConsumer):
    """ClientID report consumer (SO::ControlSystemID)."""

    def __init__(self, ctx: DDSContext, service_name: str = "ClientIDReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ControlSystemID_ClientIDReportType,
            report_topic=UMAA_SO_ControlSystemID_ClientIDReportTypeTopic,
        )

from rtiumaapy.datamodel.ControlSystemIDReportType import (
    UMAA_SO_ControlSystemID_ControlSystemIDReportType,
    UMAA_SO_ControlSystemID_ControlSystemIDReportTypeTopic,
)


class ControlSystemIDReportProvider(ReportProvider):
    """ControlSystemID report provider (SO::ControlSystemID)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ControlSystemID_ControlSystemIDReportType,
            report_topic=UMAA_SO_ControlSystemID_ControlSystemIDReportTypeTopic,
            key_holder=key_holder,
        )


class ControlSystemIDReportConsumer(ReportConsumer):
    """ControlSystemID report consumer (SO::ControlSystemID)."""

    def __init__(self, ctx: DDSContext, service_name: str = "ControlSystemIDReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ControlSystemID_ControlSystemIDReportType,
            report_topic=UMAA_SO_ControlSystemID_ControlSystemIDReportTypeTopic,
        )

from rtiumaapy.datamodel.EmitterReportType import (
    UMAA_SO_EmitterReport_EmitterReportType,
    UMAA_SO_EmitterReport_EmitterReportTypeTopic,
)


class EmitterReportProvider(ReportProvider):
    """Emitter report provider (SO::EmitterReport)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_EmitterReport_EmitterReportType,
            report_topic=UMAA_SO_EmitterReport_EmitterReportTypeTopic,
            key_holder=key_holder,
        )


class EmitterReportConsumer(ReportConsumer):
    """Emitter report consumer (SO::EmitterReport)."""

    def __init__(self, ctx: DDSContext, service_name: str = "EmitterReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_EmitterReport_EmitterReportType,
            report_topic=UMAA_SO_EmitterReport_EmitterReportTypeTopic,
        )

from rtiumaapy.datamodel.EmitterPresetReportType import (
    UMAA_SO_EmitterPresetReport_EmitterPresetReportType,
    UMAA_SO_EmitterPresetReport_EmitterPresetReportTypeTopic,
)


class EmitterPresetReportProvider(ReportProvider):
    """EmitterPreset report provider (SO::EmitterPresetReport)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_EmitterPresetReport_EmitterPresetReportType,
            report_topic=UMAA_SO_EmitterPresetReport_EmitterPresetReportTypeTopic,
            key_holder=key_holder,
        )


class EmitterPresetReportConsumer(ReportConsumer):
    """EmitterPreset report consumer (SO::EmitterPresetReport)."""

    def __init__(self, ctx: DDSContext, service_name: str = "EmitterPresetReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_EmitterPresetReport_EmitterPresetReportType,
            report_topic=UMAA_SO_EmitterPresetReport_EmitterPresetReportTypeTopic,
        )

from rtiumaapy.datamodel.EmitterPresetConfigReportType import (
    UMAA_SO_EmitterPresetConfig_EmitterPresetConfigReportType,
    UMAA_SO_EmitterPresetConfig_EmitterPresetConfigReportTypeTopic,
)


class EmitterPresetConfigReportProvider(ReportProvider):
    """EmitterPresetConfig report provider (SO::EmitterPresetConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigReportType,
            report_topic=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigReportTypeTopic,
            key_holder=key_holder,
        )


class EmitterPresetConfigReportConsumer(ReportConsumer):
    """EmitterPresetConfig report consumer (SO::EmitterPresetConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str = "EmitterPresetConfigReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigReportType,
            report_topic=UMAA_SO_EmitterPresetConfig_EmitterPresetConfigReportTypeTopic,
        )

from rtiumaapy.datamodel.EmitterSpecsReportType import (
    UMAA_SO_EmitterSpecs_EmitterSpecsReportType,
    UMAA_SO_EmitterSpecs_EmitterSpecsReportTypeTopic,
)


class EmitterSpecsReportProvider(ReportProvider):
    """EmitterSpecs report provider (SO::EmitterSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_EmitterSpecs_EmitterSpecsReportType,
            report_topic=UMAA_SO_EmitterSpecs_EmitterSpecsReportTypeTopic,
            key_holder=key_holder,
        )


class EmitterSpecsReportConsumer(ReportConsumer):
    """EmitterSpecs report consumer (SO::EmitterSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: str = "EmitterSpecsReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_EmitterSpecs_EmitterSpecsReportType,
            report_topic=UMAA_SO_EmitterSpecs_EmitterSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.FileSystemReportType import (
    UMAA_SO_FileSystemStatus_FileSystemReportType,
    UMAA_SO_FileSystemStatus_FileSystemReportTypeTopic,
)


class FileSystemReportProvider(ReportProvider):
    """FileSystem report provider (SO::FileSystemStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_FileSystemStatus_FileSystemReportType,
            report_topic=UMAA_SO_FileSystemStatus_FileSystemReportTypeTopic,
            key_holder=key_holder,
        )


class FileSystemReportConsumer(ReportConsumer):
    """FileSystem report consumer (SO::FileSystemStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "FileSystemReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_FileSystemStatus_FileSystemReportType,
            report_topic=UMAA_SO_FileSystemStatus_FileSystemReportTypeTopic,
        )

from rtiumaapy.datamodel.HealthReportType import (
    UMAA_SO_HealthReport_HealthReportType,
    UMAA_SO_HealthReport_HealthReportTypeTopic,
)


class HealthReportProvider(ReportProvider):
    """Health report provider (SO::HealthReport)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_HealthReport_HealthReportType,
            report_topic=UMAA_SO_HealthReport_HealthReportTypeTopic,
            key_holder=key_holder,
        )


class HealthReportConsumer(ReportConsumer):
    """Health report consumer (SO::HealthReport)."""

    def __init__(self, ctx: DDSContext, service_name: str = "HealthReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_HealthReport_HealthReportType,
            report_topic=UMAA_SO_HealthReport_HealthReportTypeTopic,
        )

from rtiumaapy.datamodel.HeartbeatPulseReportType import (
    UMAA_SO_HeartbeatPulseStatus_HeartbeatPulseReportType,
    UMAA_SO_HeartbeatPulseStatus_HeartbeatPulseReportTypeTopic,
)


class HeartbeatPulseReportProvider(ReportProvider):
    """HeartbeatPulse report provider (SO::HeartbeatPulseStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_HeartbeatPulseStatus_HeartbeatPulseReportType,
            report_topic=UMAA_SO_HeartbeatPulseStatus_HeartbeatPulseReportTypeTopic,
            key_holder=key_holder,
        )


class HeartbeatPulseReportConsumer(ReportConsumer):
    """HeartbeatPulse report consumer (SO::HeartbeatPulseStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "HeartbeatPulseReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_HeartbeatPulseStatus_HeartbeatPulseReportType,
            report_topic=UMAA_SO_HeartbeatPulseStatus_HeartbeatPulseReportTypeTopic,
        )

from rtiumaapy.datamodel.LogReportType import (
    UMAA_SO_LogReport_LogReportType,
    UMAA_SO_LogReport_LogReportTypeTopic,
)


class LogReportProvider(ReportProvider):
    """Log report provider (SO::LogReport)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_LogReport_LogReportType,
            report_topic=UMAA_SO_LogReport_LogReportTypeTopic,
            key_holder=key_holder,
        )


class LogReportConsumer(ReportConsumer):
    """Log report consumer (SO::LogReport)."""

    def __init__(self, ctx: DDSContext, service_name: str = "LogReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_LogReport_LogReportType,
            report_topic=UMAA_SO_LogReport_LogReportTypeTopic,
        )

from rtiumaapy.datamodel.MemoryReportType import (
    UMAA_SO_MemoryStatus_MemoryReportType,
    UMAA_SO_MemoryStatus_MemoryReportTypeTopic,
)


class MemoryReportProvider(ReportProvider):
    """Memory report provider (SO::MemoryStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_MemoryStatus_MemoryReportType,
            report_topic=UMAA_SO_MemoryStatus_MemoryReportTypeTopic,
            key_holder=key_holder,
        )


class MemoryReportConsumer(ReportConsumer):
    """Memory report consumer (SO::MemoryStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "MemoryReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_MemoryStatus_MemoryReportType,
            report_topic=UMAA_SO_MemoryStatus_MemoryReportTypeTopic,
        )

from rtiumaapy.datamodel.ProcessingUnitReportType import (
    UMAA_SO_ProcessingUnitStatus_ProcessingUnitReportType,
    UMAA_SO_ProcessingUnitStatus_ProcessingUnitReportTypeTopic,
)


class ProcessingUnitReportProvider(ReportProvider):
    """ProcessingUnit report provider (SO::ProcessingUnitStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ProcessingUnitStatus_ProcessingUnitReportType,
            report_topic=UMAA_SO_ProcessingUnitStatus_ProcessingUnitReportTypeTopic,
            key_holder=key_holder,
        )


class ProcessingUnitReportConsumer(ReportConsumer):
    """ProcessingUnit report consumer (SO::ProcessingUnitStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "ProcessingUnitReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ProcessingUnitStatus_ProcessingUnitReportType,
            report_topic=UMAA_SO_ProcessingUnitStatus_ProcessingUnitReportTypeTopic,
        )

from rtiumaapy.datamodel.RecordingSpecsReportType import (
    UMAA_SO_RecordingSpecs_RecordingSpecsReportType,
    UMAA_SO_RecordingSpecs_RecordingSpecsReportTypeTopic,
)


class RecordingSpecsReportProvider(ReportProvider):
    """RecordingSpecs report provider (SO::RecordingSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_RecordingSpecs_RecordingSpecsReportType,
            report_topic=UMAA_SO_RecordingSpecs_RecordingSpecsReportTypeTopic,
            key_holder=key_holder,
        )


class RecordingSpecsReportConsumer(ReportConsumer):
    """RecordingSpecs report consumer (SO::RecordingSpecs)."""

    def __init__(self, ctx: DDSContext, service_name: str = "RecordingSpecsReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_RecordingSpecs_RecordingSpecsReportType,
            report_topic=UMAA_SO_RecordingSpecs_RecordingSpecsReportTypeTopic,
        )

from rtiumaapy.datamodel.RecordingStatusReportType import (
    UMAA_SO_RecordingStatus_RecordingStatusReportType,
    UMAA_SO_RecordingStatus_RecordingStatusReportTypeTopic,
)


class RecordingStatusReportProvider(ReportProvider):
    """RecordingStatus report provider (SO::RecordingStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_RecordingStatus_RecordingStatusReportType,
            report_topic=UMAA_SO_RecordingStatus_RecordingStatusReportTypeTopic,
            key_holder=key_holder,
        )


class RecordingStatusReportConsumer(ReportConsumer):
    """RecordingStatus report consumer (SO::RecordingStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "RecordingStatusReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_RecordingStatus_RecordingStatusReportType,
            report_topic=UMAA_SO_RecordingStatus_RecordingStatusReportTypeTopic,
        )

from rtiumaapy.datamodel.ResourceAllocationReportType import (
    UMAA_SO_ResourceAllocation_ResourceAllocationReportType,
    UMAA_SO_ResourceAllocation_ResourceAllocationReportTypeTopic,
)


class ResourceAllocationReportProvider(ReportProvider):
    """ResourceAllocation report provider (SO::ResourceAllocation)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceAllocation_ResourceAllocationReportType,
            report_topic=UMAA_SO_ResourceAllocation_ResourceAllocationReportTypeTopic,
            key_holder=key_holder,
        )


class ResourceAllocationReportConsumer(ReportConsumer):
    """ResourceAllocation report consumer (SO::ResourceAllocation)."""

    def __init__(self, ctx: DDSContext, service_name: str = "ResourceAllocationReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceAllocation_ResourceAllocationReportType,
            report_topic=UMAA_SO_ResourceAllocation_ResourceAllocationReportTypeTopic,
        )

from rtiumaapy.datamodel.ResourceAllocationConfigReportType import (
    UMAA_SO_ResourceAllocation_ResourceAllocationConfigReportType,
    UMAA_SO_ResourceAllocation_ResourceAllocationConfigReportTypeTopic,
)


class ResourceAllocationConfigReportProvider(ReportProvider):
    """ResourceAllocationConfig report provider (SO::ResourceAllocation)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceAllocation_ResourceAllocationConfigReportType,
            report_topic=UMAA_SO_ResourceAllocation_ResourceAllocationConfigReportTypeTopic,
            key_holder=key_holder,
        )


class ResourceAllocationConfigReportConsumer(ReportConsumer):
    """ResourceAllocationConfig report consumer (SO::ResourceAllocation)."""

    def __init__(self, ctx: DDSContext, service_name: str = "ResourceAllocationConfigReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceAllocation_ResourceAllocationConfigReportType,
            report_topic=UMAA_SO_ResourceAllocation_ResourceAllocationConfigReportTypeTopic,
        )

from rtiumaapy.datamodel.ResourceAllocationPriorityReportType import (
    UMAA_SO_ResourceAllocation_ResourceAllocationPriorityReportType,
    UMAA_SO_ResourceAllocation_ResourceAllocationPriorityReportTypeTopic,
)


class ResourceAllocationPriorityReportProvider(ReportProvider):
    """ResourceAllocationPriority report provider (SO::ResourceAllocation)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityReportType,
            report_topic=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityReportTypeTopic,
            key_holder=key_holder,
        )


class ResourceAllocationPriorityReportConsumer(ReportConsumer):
    """ResourceAllocationPriority report consumer (SO::ResourceAllocation)."""

    def __init__(self, ctx: DDSContext, service_name: str = "ResourceAllocationPriorityReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityReportType,
            report_topic=UMAA_SO_ResourceAllocation_ResourceAllocationPriorityReportTypeTopic,
        )

from rtiumaapy.datamodel.ResourceAuthorizationReportType import (
    UMAA_SO_ResourceIdentification_ResourceAuthorizationReportType,
    UMAA_SO_ResourceIdentification_ResourceAuthorizationReportTypeTopic,
)


class ResourceAuthorizationReportProvider(ReportProvider):
    """ResourceAuthorization report provider (SO::ResourceIdentification)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceIdentification_ResourceAuthorizationReportType,
            report_topic=UMAA_SO_ResourceIdentification_ResourceAuthorizationReportTypeTopic,
            key_holder=key_holder,
        )


class ResourceAuthorizationReportConsumer(ReportConsumer):
    """ResourceAuthorization report consumer (SO::ResourceIdentification)."""

    def __init__(self, ctx: DDSContext, service_name: str = "ResourceAuthorizationReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceIdentification_ResourceAuthorizationReportType,
            report_topic=UMAA_SO_ResourceIdentification_ResourceAuthorizationReportTypeTopic,
        )

from rtiumaapy.datamodel.SubsystemIDReportType import (
    UMAA_SO_ResourceIdentification_SubsystemIDReportType,
    UMAA_SO_ResourceIdentification_SubsystemIDReportTypeTopic,
)


class SubsystemIDReportProvider(ReportProvider):
    """SubsystemID report provider (SO::ResourceIdentification)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceIdentification_SubsystemIDReportType,
            report_topic=UMAA_SO_ResourceIdentification_SubsystemIDReportTypeTopic,
            key_holder=key_holder,
        )


class SubsystemIDReportConsumer(ReportConsumer):
    """SubsystemID report consumer (SO::ResourceIdentification)."""

    def __init__(self, ctx: DDSContext, service_name: str = "SubsystemIDReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceIdentification_SubsystemIDReportType,
            report_topic=UMAA_SO_ResourceIdentification_SubsystemIDReportTypeTopic,
        )

from rtiumaapy.datamodel.TamperDetectionReportType import (
    UMAA_SO_TamperDetectionStatus_TamperDetectionReportType,
    UMAA_SO_TamperDetectionStatus_TamperDetectionReportTypeTopic,
)


class TamperDetectionReportProvider(ReportProvider):
    """TamperDetection report provider (SO::TamperDetectionStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_TamperDetectionStatus_TamperDetectionReportType,
            report_topic=UMAA_SO_TamperDetectionStatus_TamperDetectionReportTypeTopic,
            key_holder=key_holder,
        )


class TamperDetectionReportConsumer(ReportConsumer):
    """TamperDetection report consumer (SO::TamperDetectionStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "TamperDetectionReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_TamperDetectionStatus_TamperDetectionReportType,
            report_topic=UMAA_SO_TamperDetectionStatus_TamperDetectionReportTypeTopic,
        )

from rtiumaapy.datamodel.VehicleIDReportType import (
    UMAA_SO_ResourceIdentification_VehicleIDReportType,
    UMAA_SO_ResourceIdentification_VehicleIDReportTypeTopic,
)


class VehicleIDReportProvider(ReportProvider):
    """VehicleID report provider (SO::ResourceIdentification)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceIdentification_VehicleIDReportType,
            report_topic=UMAA_SO_ResourceIdentification_VehicleIDReportTypeTopic,
            key_holder=key_holder,
        )


class VehicleIDReportConsumer(ReportConsumer):
    """VehicleID report consumer (SO::ResourceIdentification)."""

    def __init__(self, ctx: DDSContext, service_name: str = "VehicleIDReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_SO_ResourceIdentification_VehicleIDReportType,
            report_topic=UMAA_SO_ResourceIdentification_VehicleIDReportTypeTopic,
        )
