"""rtiumaapy.services.mo — Maneuver/Operations service classes.

Auto-generated by tools/generate_services.py. Do not edit manually.
"""

from __future__ import annotations

from rtiumaapy.command_provider import CommandProvider
from rtiumaapy.command_consumer import CommandConsumer
from rtiumaapy.report_provider import ReportProvider
from rtiumaapy.report_consumer import ReportConsumer
from rtiumaapy.dds_context import DDSContext

__all__ = [
    "ContactManeuverInfluenceReportConsumer",
    "ContactManeuverInfluenceReportProvider",
    "CoordinationSituationalSignalReportConsumer",
    "CoordinationSituationalSignalReportProvider",
    "FreeFloatControlConsumer",
    "FreeFloatControlProvider",
    "GlobalDriftControlConsumer",
    "GlobalDriftControlProvider",
    "GlobalHoverControlConsumer",
    "GlobalHoverControlProvider",
    "GlobalVectorControlConsumer",
    "GlobalVectorControlProvider",
    "GlobalWaypointControlConsumer",
    "GlobalWaypointControlProvider",
    "HazardAvoidanceConfigReportConsumer",
    "HazardAvoidanceConfigReportProvider",
    "PrimitiveDriverControlConsumer",
    "PrimitiveDriverControlProvider",
]

from rtiumaapy.datamodel.FreeFloatCommandType import (
    UMAA_MO_FreeFloatControl_FreeFloatCommandType,
    UMAA_MO_FreeFloatControl_FreeFloatCommandTypeTopic,
)
from rtiumaapy.datamodel.FreeFloatCommandAckReportType import (
    UMAA_MO_FreeFloatControl_FreeFloatCommandAckReportType,
    UMAA_MO_FreeFloatControl_FreeFloatCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.FreeFloatCommandStatusType import (
    UMAA_MO_FreeFloatControl_FreeFloatCommandStatusType,
    UMAA_MO_FreeFloatControl_FreeFloatCommandStatusTypeTopic,
)
from rtiumaapy.datamodel.FreeFloatExecutionStatusReportType import (
    UMAA_MO_FreeFloatControl_FreeFloatExecutionStatusReportType,
    UMAA_MO_FreeFloatControl_FreeFloatExecutionStatusReportTypeTopic,
)


class FreeFloatControlProvider(CommandProvider):
    """FreeFloat command provider (MO::FreeFloatControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="FreeFloat",
            command_type=UMAA_MO_FreeFloatControl_FreeFloatCommandType,
            command_topic=UMAA_MO_FreeFloatControl_FreeFloatCommandTypeTopic,
            ack_type=UMAA_MO_FreeFloatControl_FreeFloatCommandAckReportType,
            ack_topic=UMAA_MO_FreeFloatControl_FreeFloatCommandAckReportTypeTopic,
            status_type=UMAA_MO_FreeFloatControl_FreeFloatCommandStatusType,
            status_topic=UMAA_MO_FreeFloatControl_FreeFloatCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_FreeFloatControl_FreeFloatExecutionStatusReportType,
            exec_status_topic=UMAA_MO_FreeFloatControl_FreeFloatExecutionStatusReportTypeTopic,
            source_id=source_id,
        )


class FreeFloatControlConsumer(CommandConsumer):
    """FreeFloat command consumer (MO::FreeFloatControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="FreeFloat",
            command_type=UMAA_MO_FreeFloatControl_FreeFloatCommandType,
            command_topic=UMAA_MO_FreeFloatControl_FreeFloatCommandTypeTopic,
            ack_type=UMAA_MO_FreeFloatControl_FreeFloatCommandAckReportType,
            ack_topic=UMAA_MO_FreeFloatControl_FreeFloatCommandAckReportTypeTopic,
            status_type=UMAA_MO_FreeFloatControl_FreeFloatCommandStatusType,
            status_topic=UMAA_MO_FreeFloatControl_FreeFloatCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_FreeFloatControl_FreeFloatExecutionStatusReportType,
            exec_status_topic=UMAA_MO_FreeFloatControl_FreeFloatExecutionStatusReportTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.GlobalDriftCommandType import (
    UMAA_MO_GlobalDriftControl_GlobalDriftCommandType,
    UMAA_MO_GlobalDriftControl_GlobalDriftCommandTypeTopic,
)
from rtiumaapy.datamodel.GlobalDriftCommandAckReportType import (
    UMAA_MO_GlobalDriftControl_GlobalDriftCommandAckReportType,
    UMAA_MO_GlobalDriftControl_GlobalDriftCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.GlobalDriftCommandStatusType import (
    UMAA_MO_GlobalDriftControl_GlobalDriftCommandStatusType,
    UMAA_MO_GlobalDriftControl_GlobalDriftCommandStatusTypeTopic,
)
from rtiumaapy.datamodel.GlobalDriftExecutionStatusReportType import (
    UMAA_MO_GlobalDriftControl_GlobalDriftExecutionStatusReportType,
    UMAA_MO_GlobalDriftControl_GlobalDriftExecutionStatusReportTypeTopic,
)


class GlobalDriftControlProvider(CommandProvider):
    """GlobalDrift command provider (MO::GlobalDriftControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="GlobalDrift",
            command_type=UMAA_MO_GlobalDriftControl_GlobalDriftCommandType,
            command_topic=UMAA_MO_GlobalDriftControl_GlobalDriftCommandTypeTopic,
            ack_type=UMAA_MO_GlobalDriftControl_GlobalDriftCommandAckReportType,
            ack_topic=UMAA_MO_GlobalDriftControl_GlobalDriftCommandAckReportTypeTopic,
            status_type=UMAA_MO_GlobalDriftControl_GlobalDriftCommandStatusType,
            status_topic=UMAA_MO_GlobalDriftControl_GlobalDriftCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_GlobalDriftControl_GlobalDriftExecutionStatusReportType,
            exec_status_topic=UMAA_MO_GlobalDriftControl_GlobalDriftExecutionStatusReportTypeTopic,
            source_id=source_id,
        )


class GlobalDriftControlConsumer(CommandConsumer):
    """GlobalDrift command consumer (MO::GlobalDriftControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="GlobalDrift",
            command_type=UMAA_MO_GlobalDriftControl_GlobalDriftCommandType,
            command_topic=UMAA_MO_GlobalDriftControl_GlobalDriftCommandTypeTopic,
            ack_type=UMAA_MO_GlobalDriftControl_GlobalDriftCommandAckReportType,
            ack_topic=UMAA_MO_GlobalDriftControl_GlobalDriftCommandAckReportTypeTopic,
            status_type=UMAA_MO_GlobalDriftControl_GlobalDriftCommandStatusType,
            status_topic=UMAA_MO_GlobalDriftControl_GlobalDriftCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_GlobalDriftControl_GlobalDriftExecutionStatusReportType,
            exec_status_topic=UMAA_MO_GlobalDriftControl_GlobalDriftExecutionStatusReportTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.GlobalHoverCommandType import (
    UMAA_MO_GlobalHoverControl_GlobalHoverCommandType,
    UMAA_MO_GlobalHoverControl_GlobalHoverCommandTypeTopic,
)
from rtiumaapy.datamodel.GlobalHoverCommandAckReportType import (
    UMAA_MO_GlobalHoverControl_GlobalHoverCommandAckReportType,
    UMAA_MO_GlobalHoverControl_GlobalHoverCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.GlobalHoverCommandStatusType import (
    UMAA_MO_GlobalHoverControl_GlobalHoverCommandStatusType,
    UMAA_MO_GlobalHoverControl_GlobalHoverCommandStatusTypeTopic,
)
from rtiumaapy.datamodel.GlobalHoverExecutionStatusReportType import (
    UMAA_MO_GlobalHoverControl_GlobalHoverExecutionStatusReportType,
    UMAA_MO_GlobalHoverControl_GlobalHoverExecutionStatusReportTypeTopic,
)


class GlobalHoverControlProvider(CommandProvider):
    """GlobalHover command provider (MO::GlobalHoverControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="GlobalHover",
            command_type=UMAA_MO_GlobalHoverControl_GlobalHoverCommandType,
            command_topic=UMAA_MO_GlobalHoverControl_GlobalHoverCommandTypeTopic,
            ack_type=UMAA_MO_GlobalHoverControl_GlobalHoverCommandAckReportType,
            ack_topic=UMAA_MO_GlobalHoverControl_GlobalHoverCommandAckReportTypeTopic,
            status_type=UMAA_MO_GlobalHoverControl_GlobalHoverCommandStatusType,
            status_topic=UMAA_MO_GlobalHoverControl_GlobalHoverCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_GlobalHoverControl_GlobalHoverExecutionStatusReportType,
            exec_status_topic=UMAA_MO_GlobalHoverControl_GlobalHoverExecutionStatusReportTypeTopic,
            source_id=source_id,
        )


class GlobalHoverControlConsumer(CommandConsumer):
    """GlobalHover command consumer (MO::GlobalHoverControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="GlobalHover",
            command_type=UMAA_MO_GlobalHoverControl_GlobalHoverCommandType,
            command_topic=UMAA_MO_GlobalHoverControl_GlobalHoverCommandTypeTopic,
            ack_type=UMAA_MO_GlobalHoverControl_GlobalHoverCommandAckReportType,
            ack_topic=UMAA_MO_GlobalHoverControl_GlobalHoverCommandAckReportTypeTopic,
            status_type=UMAA_MO_GlobalHoverControl_GlobalHoverCommandStatusType,
            status_topic=UMAA_MO_GlobalHoverControl_GlobalHoverCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_GlobalHoverControl_GlobalHoverExecutionStatusReportType,
            exec_status_topic=UMAA_MO_GlobalHoverControl_GlobalHoverExecutionStatusReportTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.GlobalVectorCommandType import (
    UMAA_MO_GlobalVectorControl_GlobalVectorCommandType,
    UMAA_MO_GlobalVectorControl_GlobalVectorCommandTypeTopic,
)
from rtiumaapy.datamodel.GlobalVectorCommandAckReportType import (
    UMAA_MO_GlobalVectorControl_GlobalVectorCommandAckReportType,
    UMAA_MO_GlobalVectorControl_GlobalVectorCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.GlobalVectorCommandStatusType import (
    UMAA_MO_GlobalVectorControl_GlobalVectorCommandStatusType,
    UMAA_MO_GlobalVectorControl_GlobalVectorCommandStatusTypeTopic,
)
from rtiumaapy.datamodel.GlobalVectorExecutionStatusReportType import (
    UMAA_MO_GlobalVectorControl_GlobalVectorExecutionStatusReportType,
    UMAA_MO_GlobalVectorControl_GlobalVectorExecutionStatusReportTypeTopic,
)


class GlobalVectorControlProvider(CommandProvider):
    """GlobalVector command provider (MO::GlobalVectorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="GlobalVector",
            command_type=UMAA_MO_GlobalVectorControl_GlobalVectorCommandType,
            command_topic=UMAA_MO_GlobalVectorControl_GlobalVectorCommandTypeTopic,
            ack_type=UMAA_MO_GlobalVectorControl_GlobalVectorCommandAckReportType,
            ack_topic=UMAA_MO_GlobalVectorControl_GlobalVectorCommandAckReportTypeTopic,
            status_type=UMAA_MO_GlobalVectorControl_GlobalVectorCommandStatusType,
            status_topic=UMAA_MO_GlobalVectorControl_GlobalVectorCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_GlobalVectorControl_GlobalVectorExecutionStatusReportType,
            exec_status_topic=UMAA_MO_GlobalVectorControl_GlobalVectorExecutionStatusReportTypeTopic,
            source_id=source_id,
        )


class GlobalVectorControlConsumer(CommandConsumer):
    """GlobalVector command consumer (MO::GlobalVectorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="GlobalVector",
            command_type=UMAA_MO_GlobalVectorControl_GlobalVectorCommandType,
            command_topic=UMAA_MO_GlobalVectorControl_GlobalVectorCommandTypeTopic,
            ack_type=UMAA_MO_GlobalVectorControl_GlobalVectorCommandAckReportType,
            ack_topic=UMAA_MO_GlobalVectorControl_GlobalVectorCommandAckReportTypeTopic,
            status_type=UMAA_MO_GlobalVectorControl_GlobalVectorCommandStatusType,
            status_topic=UMAA_MO_GlobalVectorControl_GlobalVectorCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_GlobalVectorControl_GlobalVectorExecutionStatusReportType,
            exec_status_topic=UMAA_MO_GlobalVectorControl_GlobalVectorExecutionStatusReportTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.GlobalWaypointCommandType import (
    UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandType,
    UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandTypeTopic,
)
from rtiumaapy.datamodel.GlobalWaypointCommandAckReportType import (
    UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandAckReportType,
    UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.GlobalWaypointCommandStatusType import (
    UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandStatusType,
    UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandStatusTypeTopic,
)
from rtiumaapy.datamodel.GlobalWaypointExecutionStatusReportType import (
    UMAA_MO_GlobalWaypointControl_GlobalWaypointExecutionStatusReportType,
    UMAA_MO_GlobalWaypointControl_GlobalWaypointExecutionStatusReportTypeTopic,
)


class GlobalWaypointControlProvider(CommandProvider):
    """GlobalWaypoint command provider (MO::GlobalWaypointControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="GlobalWaypoint",
            command_type=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandType,
            command_topic=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandTypeTopic,
            ack_type=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandAckReportType,
            ack_topic=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandAckReportTypeTopic,
            status_type=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandStatusType,
            status_topic=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_GlobalWaypointControl_GlobalWaypointExecutionStatusReportType,
            exec_status_topic=UMAA_MO_GlobalWaypointControl_GlobalWaypointExecutionStatusReportTypeTopic,
            source_id=source_id,
        )


class GlobalWaypointControlConsumer(CommandConsumer):
    """GlobalWaypoint command consumer (MO::GlobalWaypointControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="GlobalWaypoint",
            command_type=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandType,
            command_topic=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandTypeTopic,
            ack_type=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandAckReportType,
            ack_topic=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandAckReportTypeTopic,
            status_type=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandStatusType,
            status_topic=UMAA_MO_GlobalWaypointControl_GlobalWaypointCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_GlobalWaypointControl_GlobalWaypointExecutionStatusReportType,
            exec_status_topic=UMAA_MO_GlobalWaypointControl_GlobalWaypointExecutionStatusReportTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.PrimitiveDriverCommandType import (
    UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandType,
    UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandTypeTopic,
)
from rtiumaapy.datamodel.PrimitiveDriverCommandAckReportType import (
    UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandAckReportType,
    UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.PrimitiveDriverCommandStatusType import (
    UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandStatusType,
    UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandStatusTypeTopic,
)
from rtiumaapy.datamodel.PrimitiveDriverExecutionStatusReportType import (
    UMAA_MO_PrimitiveDriverControl_PrimitiveDriverExecutionStatusReportType,
    UMAA_MO_PrimitiveDriverControl_PrimitiveDriverExecutionStatusReportTypeTopic,
)


class PrimitiveDriverControlProvider(CommandProvider):
    """PrimitiveDriver command provider (MO::PrimitiveDriverControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="PrimitiveDriver",
            command_type=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandType,
            command_topic=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandTypeTopic,
            ack_type=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandAckReportType,
            ack_topic=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandAckReportTypeTopic,
            status_type=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandStatusType,
            status_topic=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverExecutionStatusReportType,
            exec_status_topic=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverExecutionStatusReportTypeTopic,
            source_id=source_id,
        )


class PrimitiveDriverControlConsumer(CommandConsumer):
    """PrimitiveDriver command consumer (MO::PrimitiveDriverControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="PrimitiveDriver",
            command_type=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandType,
            command_topic=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandTypeTopic,
            ack_type=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandAckReportType,
            ack_topic=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandAckReportTypeTopic,
            status_type=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandStatusType,
            status_topic=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverCommandStatusTypeTopic,
            exec_status_type=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverExecutionStatusReportType,
            exec_status_topic=UMAA_MO_PrimitiveDriverControl_PrimitiveDriverExecutionStatusReportTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ContactManeuverInfluenceReportType import (
    UMAA_MO_ContactManeuverInfluenceStatus_ContactManeuverInfluenceReportType,
    UMAA_MO_ContactManeuverInfluenceStatus_ContactManeuverInfluenceReportTypeTopic,
)


class ContactManeuverInfluenceReportProvider(ReportProvider):
    """ContactManeuverInfluence report provider (MO::ContactManeuverInfluenceStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MO_ContactManeuverInfluenceStatus_ContactManeuverInfluenceReportType,
            report_topic=UMAA_MO_ContactManeuverInfluenceStatus_ContactManeuverInfluenceReportTypeTopic,
            key_holder=key_holder,
        )


class ContactManeuverInfluenceReportConsumer(ReportConsumer):
    """ContactManeuverInfluence report consumer (MO::ContactManeuverInfluenceStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "ContactManeuverInfluenceReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MO_ContactManeuverInfluenceStatus_ContactManeuverInfluenceReportType,
            report_topic=UMAA_MO_ContactManeuverInfluenceStatus_ContactManeuverInfluenceReportTypeTopic,
        )

from rtiumaapy.datamodel.CoordinationSituationalSignalReportType import (
    UMAA_MO_CoordinationSituationalSignalStatus_CoordinationSituationalSignalReportType,
    UMAA_MO_CoordinationSituationalSignalStatus_CoordinationSituationalSignalReportTypeTopic,
)


class CoordinationSituationalSignalReportProvider(ReportProvider):
    """CoordinationSituationalSignal report provider (MO::CoordinationSituationalSignalStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MO_CoordinationSituationalSignalStatus_CoordinationSituationalSignalReportType,
            report_topic=UMAA_MO_CoordinationSituationalSignalStatus_CoordinationSituationalSignalReportTypeTopic,
            key_holder=key_holder,
        )


class CoordinationSituationalSignalReportConsumer(ReportConsumer):
    """CoordinationSituationalSignal report consumer (MO::CoordinationSituationalSignalStatus)."""

    def __init__(self, ctx: DDSContext, service_name: str = "CoordinationSituationalSignalReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MO_CoordinationSituationalSignalStatus_CoordinationSituationalSignalReportType,
            report_topic=UMAA_MO_CoordinationSituationalSignalStatus_CoordinationSituationalSignalReportTypeTopic,
        )

from rtiumaapy.datamodel.HazardAvoidanceConfigReportType import (
    UMAA_MO_HazardAvoidanceConfig_HazardAvoidanceConfigReportType,
    UMAA_MO_HazardAvoidanceConfig_HazardAvoidanceConfigReportTypeTopic,
)


class HazardAvoidanceConfigReportProvider(ReportProvider):
    """HazardAvoidanceConfig report provider (MO::HazardAvoidanceConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str, key_holder):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MO_HazardAvoidanceConfig_HazardAvoidanceConfigReportType,
            report_topic=UMAA_MO_HazardAvoidanceConfig_HazardAvoidanceConfigReportTypeTopic,
            key_holder=key_holder,
        )


class HazardAvoidanceConfigReportConsumer(ReportConsumer):
    """HazardAvoidanceConfig report consumer (MO::HazardAvoidanceConfig)."""

    def __init__(self, ctx: DDSContext, service_name: str = "HazardAvoidanceConfigReport"):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MO_HazardAvoidanceConfig_HazardAvoidanceConfigReportType,
            report_topic=UMAA_MO_HazardAvoidanceConfig_HazardAvoidanceConfigReportTypeTopic,
        )
