"""rtiumaapy.services.mm — Mission Management service classes.

Auto-generated by tools/generate_services.py. Do not edit manually.
"""

from __future__ import annotations
from typing import Optional

from rtiumaapy.command_provider import CommandProvider
from rtiumaapy.command_consumer import CommandConsumer
from rtiumaapy.report_provider import ReportProvider
from rtiumaapy.report_consumer import ReportConsumer
from rtiumaapy.dds_context import DDSContext

__all__ = [
    "ActiveConstraintsControlConsumer",
    "ActiveConstraintsControlProvider",
    "ClientControlReportConsumer",
    "ClientControlReportProvider",
    "ClientControlTransferReportConsumer",
    "ClientControlTransferReportProvider",
    "ConditionalAddControlConsumer",
    "ConditionalAddControlProvider",
    "ConditionalDeleteControlConsumer",
    "ConditionalDeleteControlProvider",
    "ConditionalReportConsumer",
    "ConditionalReportProvider",
    "ConditionalStateReportConsumer",
    "ConditionalStateReportProvider",
    "ControlSystemControlReportConsumer",
    "ControlSystemControlReportProvider",
    "ControlSystemTransferReportConsumer",
    "ControlSystemTransferReportProvider",
    "MissionPlanAssignmentControlConsumer",
    "MissionPlanAssignmentControlProvider",
    "MissionPlanAssignmentReportConsumer",
    "MissionPlanAssignmentReportProvider",
    "MissionPlanConstraintAddControlConsumer",
    "MissionPlanConstraintAddControlProvider",
    "MissionPlanConstraintDeleteControlConsumer",
    "MissionPlanConstraintDeleteControlProvider",
    "MissionPlanExecutionControlConsumer",
    "MissionPlanExecutionControlProvider",
    "MissionPlanExecutionReportConsumer",
    "MissionPlanExecutionReportProvider",
    "MissionPlanMissionAddControlConsumer",
    "MissionPlanMissionAddControlProvider",
    "MissionPlanMissionClearControlConsumer",
    "MissionPlanMissionClearControlProvider",
    "MissionPlanMissionDeleteControlConsumer",
    "MissionPlanMissionDeleteControlProvider",
    "MissionPlanObjectiveAddControlConsumer",
    "MissionPlanObjectiveAddControlProvider",
    "MissionPlanObjectiveDeleteControlConsumer",
    "MissionPlanObjectiveDeleteControlProvider",
    "MissionPlanReportConsumer",
    "MissionPlanReportProvider",
    "MissionPlanTaskAddControlConsumer",
    "MissionPlanTaskAddControlProvider",
    "MissionPlanTaskDeleteControlConsumer",
    "MissionPlanTaskDeleteControlProvider",
    "ObjectiveAssignmentControlConsumer",
    "ObjectiveAssignmentControlProvider",
    "ObjectiveAssignmentReportConsumer",
    "ObjectiveAssignmentReportProvider",
    "ObjectiveExecutionControlConsumer",
    "ObjectiveExecutionControlProvider",
    "ObjectiveExecutionReportConsumer",
    "ObjectiveExecutionReportProvider",
    "ObjectiveExecutorControlConsumer",
    "ObjectiveExecutorControlProvider",
    "ObjectiveExecutorStateControlConsumer",
    "ObjectiveExecutorStateControlProvider",
    "OperationalModeControlConsumer",
    "OperationalModeControlProvider",
    "OperationalModeReportConsumer",
    "OperationalModeReportProvider",
    "TaskPlanAssignmentControlConsumer",
    "TaskPlanAssignmentControlProvider",
    "TaskPlanAssignmentReportConsumer",
    "TaskPlanAssignmentReportProvider",
    "TaskPlanExecutionControlConsumer",
    "TaskPlanExecutionControlProvider",
    "TaskPlanExecutionReportConsumer",
    "TaskPlanExecutionReportProvider",
]

from rtiumaapy.datamodel.ActiveConstraintsCommandType import (
    UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandType,
    UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandTypeTopic,
)
from rtiumaapy.datamodel.ActiveConstraintsCommandAckReportType import (
    UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandAckReportType,
    UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.ActiveConstraintsCommandStatusType import (
    UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandStatusType,
    UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandStatusTypeTopic,
)


class ActiveConstraintsControlProvider(CommandProvider):
    """ActiveConstraints command provider (MM::ActiveConstraintsControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ActiveConstraintsProvider",
            command_type=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandType,
            command_topic=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandTypeTopic,
            ack_type=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandAckReportType,
            ack_topic=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandAckReportTypeTopic,
            status_type=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandStatusType,
            status_topic=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandStatusTypeTopic,
            source_id=source_id,
        )


class ActiveConstraintsControlConsumer(CommandConsumer):
    """ActiveConstraints command consumer (MM::ActiveConstraintsControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ActiveConstraintsConsumer",
            command_type=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandType,
            command_topic=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandTypeTopic,
            ack_type=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandAckReportType,
            ack_topic=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandAckReportTypeTopic,
            status_type=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandStatusType,
            status_topic=UMAA_MM_ActiveConstraintsControl_ActiveConstraintsCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ConditionalAddCommandType import (
    UMAA_MM_ConditionalControl_ConditionalAddCommandType,
    UMAA_MM_ConditionalControl_ConditionalAddCommandTypeTopic,
)
from rtiumaapy.datamodel.ConditionalAddCommandAckReportType import (
    UMAA_MM_ConditionalControl_ConditionalAddCommandAckReportType,
    UMAA_MM_ConditionalControl_ConditionalAddCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.ConditionalAddCommandStatusType import (
    UMAA_MM_ConditionalControl_ConditionalAddCommandStatusType,
    UMAA_MM_ConditionalControl_ConditionalAddCommandStatusTypeTopic,
)


class ConditionalAddControlProvider(CommandProvider):
    """ConditionalAdd command provider (MM::ConditionalControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ConditionalAddProvider",
            command_type=UMAA_MM_ConditionalControl_ConditionalAddCommandType,
            command_topic=UMAA_MM_ConditionalControl_ConditionalAddCommandTypeTopic,
            ack_type=UMAA_MM_ConditionalControl_ConditionalAddCommandAckReportType,
            ack_topic=UMAA_MM_ConditionalControl_ConditionalAddCommandAckReportTypeTopic,
            status_type=UMAA_MM_ConditionalControl_ConditionalAddCommandStatusType,
            status_topic=UMAA_MM_ConditionalControl_ConditionalAddCommandStatusTypeTopic,
            source_id=source_id,
        )


class ConditionalAddControlConsumer(CommandConsumer):
    """ConditionalAdd command consumer (MM::ConditionalControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ConditionalAddConsumer",
            command_type=UMAA_MM_ConditionalControl_ConditionalAddCommandType,
            command_topic=UMAA_MM_ConditionalControl_ConditionalAddCommandTypeTopic,
            ack_type=UMAA_MM_ConditionalControl_ConditionalAddCommandAckReportType,
            ack_topic=UMAA_MM_ConditionalControl_ConditionalAddCommandAckReportTypeTopic,
            status_type=UMAA_MM_ConditionalControl_ConditionalAddCommandStatusType,
            status_topic=UMAA_MM_ConditionalControl_ConditionalAddCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ConditionalDeleteCommandType import (
    UMAA_MM_ConditionalControl_ConditionalDeleteCommandType,
    UMAA_MM_ConditionalControl_ConditionalDeleteCommandTypeTopic,
)
from rtiumaapy.datamodel.ConditionalDeleteCommandAckReportType import (
    UMAA_MM_ConditionalControl_ConditionalDeleteCommandAckReportType,
    UMAA_MM_ConditionalControl_ConditionalDeleteCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.ConditionalDeleteCommandStatusType import (
    UMAA_MM_ConditionalControl_ConditionalDeleteCommandStatusType,
    UMAA_MM_ConditionalControl_ConditionalDeleteCommandStatusTypeTopic,
)


class ConditionalDeleteControlProvider(CommandProvider):
    """ConditionalDelete command provider (MM::ConditionalControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ConditionalDeleteProvider",
            command_type=UMAA_MM_ConditionalControl_ConditionalDeleteCommandType,
            command_topic=UMAA_MM_ConditionalControl_ConditionalDeleteCommandTypeTopic,
            ack_type=UMAA_MM_ConditionalControl_ConditionalDeleteCommandAckReportType,
            ack_topic=UMAA_MM_ConditionalControl_ConditionalDeleteCommandAckReportTypeTopic,
            status_type=UMAA_MM_ConditionalControl_ConditionalDeleteCommandStatusType,
            status_topic=UMAA_MM_ConditionalControl_ConditionalDeleteCommandStatusTypeTopic,
            source_id=source_id,
        )


class ConditionalDeleteControlConsumer(CommandConsumer):
    """ConditionalDelete command consumer (MM::ConditionalControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ConditionalDeleteConsumer",
            command_type=UMAA_MM_ConditionalControl_ConditionalDeleteCommandType,
            command_topic=UMAA_MM_ConditionalControl_ConditionalDeleteCommandTypeTopic,
            ack_type=UMAA_MM_ConditionalControl_ConditionalDeleteCommandAckReportType,
            ack_topic=UMAA_MM_ConditionalControl_ConditionalDeleteCommandAckReportTypeTopic,
            status_type=UMAA_MM_ConditionalControl_ConditionalDeleteCommandStatusType,
            status_topic=UMAA_MM_ConditionalControl_ConditionalDeleteCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MissionPlanAssignmentCommandType import (
    UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandType,
    UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanAssignmentCommandAckReportType import (
    UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandAckReportType,
    UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanAssignmentCommandStatusType import (
    UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandStatusType,
    UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandStatusTypeTopic,
)


class MissionPlanAssignmentControlProvider(CommandProvider):
    """MissionPlanAssignment command provider (MM::MissionPlanAssignmentControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MissionPlanAssignmentProvider",
            command_type=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandType,
            command_topic=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandStatusType,
            status_topic=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandStatusTypeTopic,
            source_id=source_id,
        )


class MissionPlanAssignmentControlConsumer(CommandConsumer):
    """MissionPlanAssignment command consumer (MM::MissionPlanAssignmentControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MissionPlanAssignmentConsumer",
            command_type=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandType,
            command_topic=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandStatusType,
            status_topic=UMAA_MM_MissionPlanAssignmentControl_MissionPlanAssignmentCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MissionPlanConstraintAddCommandType import (
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandType,
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanConstraintAddCommandAckReportType import (
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandAckReportType,
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanConstraintAddCommandStatusType import (
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandStatusType,
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandStatusTypeTopic,
)


class MissionPlanConstraintAddControlProvider(CommandProvider):
    """MissionPlanConstraintAdd command provider (MM::MissionPlanConstraintControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MissionPlanConstraintAddProvider",
            command_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandType,
            command_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandStatusType,
            status_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandStatusTypeTopic,
            source_id=source_id,
        )


class MissionPlanConstraintAddControlConsumer(CommandConsumer):
    """MissionPlanConstraintAdd command consumer (MM::MissionPlanConstraintControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MissionPlanConstraintAddConsumer",
            command_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandType,
            command_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandStatusType,
            status_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintAddCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MissionPlanConstraintDeleteCommandType import (
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandType,
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanConstraintDeleteCommandAckReportType import (
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandAckReportType,
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanConstraintDeleteCommandStatusType import (
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandStatusType,
    UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandStatusTypeTopic,
)


class MissionPlanConstraintDeleteControlProvider(CommandProvider):
    """MissionPlanConstraintDelete command provider (MM::MissionPlanConstraintControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MissionPlanConstraintDeleteProvider",
            command_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandType,
            command_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandStatusType,
            status_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandStatusTypeTopic,
            source_id=source_id,
        )


class MissionPlanConstraintDeleteControlConsumer(CommandConsumer):
    """MissionPlanConstraintDelete command consumer (MM::MissionPlanConstraintControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MissionPlanConstraintDeleteConsumer",
            command_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandType,
            command_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandStatusType,
            status_topic=UMAA_MM_MissionPlanConstraintControl_MissionPlanConstraintDeleteCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MissionPlanExecutionCommandType import (
    UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandType,
    UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanExecutionCommandAckReportType import (
    UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandAckReportType,
    UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanExecutionCommandStatusType import (
    UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandStatusType,
    UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandStatusTypeTopic,
)


class MissionPlanExecutionControlProvider(CommandProvider):
    """MissionPlanExecution command provider (MM::MissionPlanExecutionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MissionPlanExecutionProvider",
            command_type=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandType,
            command_topic=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandStatusType,
            status_topic=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandStatusTypeTopic,
            source_id=source_id,
        )


class MissionPlanExecutionControlConsumer(CommandConsumer):
    """MissionPlanExecution command consumer (MM::MissionPlanExecutionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MissionPlanExecutionConsumer",
            command_type=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandType,
            command_topic=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandStatusType,
            status_topic=UMAA_MM_MissionPlanExecutionControl_MissionPlanExecutionCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MissionPlanMissionAddCommandType import (
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandType,
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanMissionAddCommandAckReportType import (
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandAckReportType,
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanMissionAddCommandStatusType import (
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandStatusType,
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandStatusTypeTopic,
)


class MissionPlanMissionAddControlProvider(CommandProvider):
    """MissionPlanMissionAdd command provider (MM::MissionPlanMissionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MissionPlanMissionAddProvider",
            command_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandType,
            command_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandStatusType,
            status_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandStatusTypeTopic,
            source_id=source_id,
        )


class MissionPlanMissionAddControlConsumer(CommandConsumer):
    """MissionPlanMissionAdd command consumer (MM::MissionPlanMissionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MissionPlanMissionAddConsumer",
            command_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandType,
            command_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandStatusType,
            status_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionAddCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MissionPlanMissionClearCommandType import (
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandType,
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanMissionClearCommandAckReportType import (
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandAckReportType,
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanMissionClearCommandStatusType import (
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandStatusType,
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandStatusTypeTopic,
)


class MissionPlanMissionClearControlProvider(CommandProvider):
    """MissionPlanMissionClear command provider (MM::MissionPlanMissionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MissionPlanMissionClearProvider",
            command_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandType,
            command_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandStatusType,
            status_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandStatusTypeTopic,
            source_id=source_id,
        )


class MissionPlanMissionClearControlConsumer(CommandConsumer):
    """MissionPlanMissionClear command consumer (MM::MissionPlanMissionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MissionPlanMissionClearConsumer",
            command_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandType,
            command_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandStatusType,
            status_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionClearCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MissionPlanMissionDeleteCommandType import (
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandType,
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanMissionDeleteCommandAckReportType import (
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandAckReportType,
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanMissionDeleteCommandStatusType import (
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandStatusType,
    UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandStatusTypeTopic,
)


class MissionPlanMissionDeleteControlProvider(CommandProvider):
    """MissionPlanMissionDelete command provider (MM::MissionPlanMissionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MissionPlanMissionDeleteProvider",
            command_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandType,
            command_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandStatusType,
            status_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandStatusTypeTopic,
            source_id=source_id,
        )


class MissionPlanMissionDeleteControlConsumer(CommandConsumer):
    """MissionPlanMissionDelete command consumer (MM::MissionPlanMissionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MissionPlanMissionDeleteConsumer",
            command_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandType,
            command_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandStatusType,
            status_topic=UMAA_MM_MissionPlanMissionControl_MissionPlanMissionDeleteCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MissionPlanObjectiveAddCommandType import (
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandType,
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanObjectiveAddCommandAckReportType import (
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandAckReportType,
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanObjectiveAddCommandStatusType import (
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandStatusType,
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandStatusTypeTopic,
)


class MissionPlanObjectiveAddControlProvider(CommandProvider):
    """MissionPlanObjectiveAdd command provider (MM::MissionPlanObjectiveControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MissionPlanObjectiveAddProvider",
            command_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandType,
            command_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandStatusType,
            status_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandStatusTypeTopic,
            source_id=source_id,
        )


class MissionPlanObjectiveAddControlConsumer(CommandConsumer):
    """MissionPlanObjectiveAdd command consumer (MM::MissionPlanObjectiveControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MissionPlanObjectiveAddConsumer",
            command_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandType,
            command_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandStatusType,
            status_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveAddCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MissionPlanObjectiveDeleteCommandType import (
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandType,
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanObjectiveDeleteCommandAckReportType import (
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandAckReportType,
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanObjectiveDeleteCommandStatusType import (
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandStatusType,
    UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandStatusTypeTopic,
)


class MissionPlanObjectiveDeleteControlProvider(CommandProvider):
    """MissionPlanObjectiveDelete command provider (MM::MissionPlanObjectiveControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MissionPlanObjectiveDeleteProvider",
            command_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandType,
            command_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandStatusType,
            status_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandStatusTypeTopic,
            source_id=source_id,
        )


class MissionPlanObjectiveDeleteControlConsumer(CommandConsumer):
    """MissionPlanObjectiveDelete command consumer (MM::MissionPlanObjectiveControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MissionPlanObjectiveDeleteConsumer",
            command_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandType,
            command_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandStatusType,
            status_topic=UMAA_MM_MissionPlanObjectiveControl_MissionPlanObjectiveDeleteCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MissionPlanTaskAddCommandType import (
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandType,
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanTaskAddCommandAckReportType import (
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandAckReportType,
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanTaskAddCommandStatusType import (
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandStatusType,
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandStatusTypeTopic,
)


class MissionPlanTaskAddControlProvider(CommandProvider):
    """MissionPlanTaskAdd command provider (MM::MissionPlanTaskControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MissionPlanTaskAddProvider",
            command_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandType,
            command_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandStatusType,
            status_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandStatusTypeTopic,
            source_id=source_id,
        )


class MissionPlanTaskAddControlConsumer(CommandConsumer):
    """MissionPlanTaskAdd command consumer (MM::MissionPlanTaskControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MissionPlanTaskAddConsumer",
            command_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandType,
            command_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandStatusType,
            status_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskAddCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.MissionPlanTaskDeleteCommandType import (
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandType,
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanTaskDeleteCommandAckReportType import (
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandAckReportType,
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.MissionPlanTaskDeleteCommandStatusType import (
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandStatusType,
    UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandStatusTypeTopic,
)


class MissionPlanTaskDeleteControlProvider(CommandProvider):
    """MissionPlanTaskDelete command provider (MM::MissionPlanTaskControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="MissionPlanTaskDeleteProvider",
            command_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandType,
            command_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandStatusType,
            status_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandStatusTypeTopic,
            source_id=source_id,
        )


class MissionPlanTaskDeleteControlConsumer(CommandConsumer):
    """MissionPlanTaskDelete command consumer (MM::MissionPlanTaskControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="MissionPlanTaskDeleteConsumer",
            command_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandType,
            command_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandTypeTopic,
            ack_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandAckReportType,
            ack_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandAckReportTypeTopic,
            status_type=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandStatusType,
            status_topic=UMAA_MM_MissionPlanTaskControl_MissionPlanTaskDeleteCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ObjectiveAssignmentCommandType import (
    UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandType,
    UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandTypeTopic,
)
from rtiumaapy.datamodel.ObjectiveAssignmentCommandAckReportType import (
    UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandAckReportType,
    UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.ObjectiveAssignmentCommandStatusType import (
    UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandStatusType,
    UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandStatusTypeTopic,
)


class ObjectiveAssignmentControlProvider(CommandProvider):
    """ObjectiveAssignment command provider (MM::ObjectiveAssignmentControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ObjectiveAssignmentProvider",
            command_type=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandType,
            command_topic=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandTypeTopic,
            ack_type=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandAckReportType,
            ack_topic=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandAckReportTypeTopic,
            status_type=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandStatusType,
            status_topic=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandStatusTypeTopic,
            source_id=source_id,
        )


class ObjectiveAssignmentControlConsumer(CommandConsumer):
    """ObjectiveAssignment command consumer (MM::ObjectiveAssignmentControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ObjectiveAssignmentConsumer",
            command_type=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandType,
            command_topic=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandTypeTopic,
            ack_type=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandAckReportType,
            ack_topic=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandAckReportTypeTopic,
            status_type=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandStatusType,
            status_topic=UMAA_MM_ObjectiveAssignmentControl_ObjectiveAssignmentCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ObjectiveExecutionCommandType import (
    UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandType,
    UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandTypeTopic,
)
from rtiumaapy.datamodel.ObjectiveExecutionCommandAckReportType import (
    UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandAckReportType,
    UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.ObjectiveExecutionCommandStatusType import (
    UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandStatusType,
    UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandStatusTypeTopic,
)


class ObjectiveExecutionControlProvider(CommandProvider):
    """ObjectiveExecution command provider (MM::ObjectiveExecutionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ObjectiveExecutionProvider",
            command_type=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandType,
            command_topic=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandTypeTopic,
            ack_type=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandAckReportType,
            ack_topic=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandAckReportTypeTopic,
            status_type=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandStatusType,
            status_topic=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandStatusTypeTopic,
            source_id=source_id,
        )


class ObjectiveExecutionControlConsumer(CommandConsumer):
    """ObjectiveExecution command consumer (MM::ObjectiveExecutionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ObjectiveExecutionConsumer",
            command_type=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandType,
            command_topic=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandTypeTopic,
            ack_type=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandAckReportType,
            ack_topic=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandAckReportTypeTopic,
            status_type=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandStatusType,
            status_topic=UMAA_MM_ObjectiveExecutionControl_ObjectiveExecutionCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ObjectiveExecutorCommandType import (
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandType,
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandTypeTopic,
)
from rtiumaapy.datamodel.ObjectiveExecutorCommandAckReportType import (
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandAckReportType,
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.ObjectiveExecutorCommandStatusType import (
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandStatusType,
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandStatusTypeTopic,
)
from rtiumaapy.datamodel.ObjectiveExecutorExecutionStatusReportType import (
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorExecutionStatusReportType,
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorExecutionStatusReportTypeTopic,
)


class ObjectiveExecutorControlProvider(CommandProvider):
    """ObjectiveExecutor command provider (MM::ObjectiveExecutorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ObjectiveExecutorProvider",
            command_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandType,
            command_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandTypeTopic,
            ack_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandAckReportType,
            ack_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandAckReportTypeTopic,
            status_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandStatusType,
            status_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandStatusTypeTopic,
            exec_status_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorExecutionStatusReportType,
            exec_status_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorExecutionStatusReportTypeTopic,
            source_id=source_id,
        )


class ObjectiveExecutorControlConsumer(CommandConsumer):
    """ObjectiveExecutor command consumer (MM::ObjectiveExecutorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ObjectiveExecutorConsumer",
            command_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandType,
            command_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandTypeTopic,
            ack_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandAckReportType,
            ack_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandAckReportTypeTopic,
            status_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandStatusType,
            status_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorCommandStatusTypeTopic,
            exec_status_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorExecutionStatusReportType,
            exec_status_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorExecutionStatusReportTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ObjectiveExecutorStateCommandType import (
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandType,
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandTypeTopic,
)
from rtiumaapy.datamodel.ObjectiveExecutorStateCommandAckReportType import (
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandAckReportType,
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.ObjectiveExecutorStateCommandStatusType import (
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandStatusType,
    UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandStatusTypeTopic,
)


class ObjectiveExecutorStateControlProvider(CommandProvider):
    """ObjectiveExecutorState command provider (MM::ObjectiveExecutorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="ObjectiveExecutorStateProvider",
            command_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandType,
            command_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandTypeTopic,
            ack_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandAckReportType,
            ack_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandAckReportTypeTopic,
            status_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandStatusType,
            status_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandStatusTypeTopic,
            source_id=source_id,
        )


class ObjectiveExecutorStateControlConsumer(CommandConsumer):
    """ObjectiveExecutorState command consumer (MM::ObjectiveExecutorControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="ObjectiveExecutorStateConsumer",
            command_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandType,
            command_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandTypeTopic,
            ack_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandAckReportType,
            ack_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandAckReportTypeTopic,
            status_type=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandStatusType,
            status_topic=UMAA_MM_ObjectiveExecutorControl_ObjectiveExecutorStateCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.OperationalModeCommandType import (
    UMAA_MM_OperationalModeControl_OperationalModeCommandType,
    UMAA_MM_OperationalModeControl_OperationalModeCommandTypeTopic,
)
from rtiumaapy.datamodel.OperationalModeCommandAckReportType import (
    UMAA_MM_OperationalModeControl_OperationalModeCommandAckReportType,
    UMAA_MM_OperationalModeControl_OperationalModeCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.OperationalModeCommandStatusType import (
    UMAA_MM_OperationalModeControl_OperationalModeCommandStatusType,
    UMAA_MM_OperationalModeControl_OperationalModeCommandStatusTypeTopic,
)


class OperationalModeControlProvider(CommandProvider):
    """OperationalMode command provider (MM::OperationalModeControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="OperationalModeProvider",
            command_type=UMAA_MM_OperationalModeControl_OperationalModeCommandType,
            command_topic=UMAA_MM_OperationalModeControl_OperationalModeCommandTypeTopic,
            ack_type=UMAA_MM_OperationalModeControl_OperationalModeCommandAckReportType,
            ack_topic=UMAA_MM_OperationalModeControl_OperationalModeCommandAckReportTypeTopic,
            status_type=UMAA_MM_OperationalModeControl_OperationalModeCommandStatusType,
            status_topic=UMAA_MM_OperationalModeControl_OperationalModeCommandStatusTypeTopic,
            source_id=source_id,
        )


class OperationalModeControlConsumer(CommandConsumer):
    """OperationalMode command consumer (MM::OperationalModeControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="OperationalModeConsumer",
            command_type=UMAA_MM_OperationalModeControl_OperationalModeCommandType,
            command_topic=UMAA_MM_OperationalModeControl_OperationalModeCommandTypeTopic,
            ack_type=UMAA_MM_OperationalModeControl_OperationalModeCommandAckReportType,
            ack_topic=UMAA_MM_OperationalModeControl_OperationalModeCommandAckReportTypeTopic,
            status_type=UMAA_MM_OperationalModeControl_OperationalModeCommandStatusType,
            status_topic=UMAA_MM_OperationalModeControl_OperationalModeCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.TaskPlanAssignmentCommandType import (
    UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandType,
    UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandTypeTopic,
)
from rtiumaapy.datamodel.TaskPlanAssignmentCommandAckReportType import (
    UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandAckReportType,
    UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.TaskPlanAssignmentCommandStatusType import (
    UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandStatusType,
    UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandStatusTypeTopic,
)


class TaskPlanAssignmentControlProvider(CommandProvider):
    """TaskPlanAssignment command provider (MM::TaskPlanAssignmentControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="TaskPlanAssignmentProvider",
            command_type=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandType,
            command_topic=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandTypeTopic,
            ack_type=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandAckReportType,
            ack_topic=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandAckReportTypeTopic,
            status_type=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandStatusType,
            status_topic=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandStatusTypeTopic,
            source_id=source_id,
        )


class TaskPlanAssignmentControlConsumer(CommandConsumer):
    """TaskPlanAssignment command consumer (MM::TaskPlanAssignmentControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="TaskPlanAssignmentConsumer",
            command_type=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandType,
            command_topic=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandTypeTopic,
            ack_type=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandAckReportType,
            ack_topic=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandAckReportTypeTopic,
            status_type=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandStatusType,
            status_topic=UMAA_MM_TaskPlanAssignmentControl_TaskPlanAssignmentCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.TaskPlanExecutionCommandType import (
    UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandType,
    UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandTypeTopic,
)
from rtiumaapy.datamodel.TaskPlanExecutionCommandAckReportType import (
    UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandAckReportType,
    UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandAckReportTypeTopic,
)
from rtiumaapy.datamodel.TaskPlanExecutionCommandStatusType import (
    UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandStatusType,
    UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandStatusTypeTopic,
)


class TaskPlanExecutionControlProvider(CommandProvider):
    """TaskPlanExecution command provider (MM::TaskPlanExecutionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id):
        super().__init__(
            ctx,
            service_name="TaskPlanExecutionProvider",
            command_type=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandType,
            command_topic=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandTypeTopic,
            ack_type=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandAckReportType,
            ack_topic=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandAckReportTypeTopic,
            status_type=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandStatusType,
            status_topic=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandStatusTypeTopic,
            source_id=source_id,
        )


class TaskPlanExecutionControlConsumer(CommandConsumer):
    """TaskPlanExecution command consumer (MM::TaskPlanExecutionControl)."""

    def __init__(self, ctx: DDSContext, *, source_id=None, destination_id=None):
        super().__init__(
            ctx,
            service_name="TaskPlanExecutionConsumer",
            command_type=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandType,
            command_topic=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandTypeTopic,
            ack_type=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandAckReportType,
            ack_topic=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandAckReportTypeTopic,
            status_type=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandStatusType,
            status_topic=UMAA_MM_TaskPlanExecutionControl_TaskPlanExecutionCommandStatusTypeTopic,
            source_id=source_id,
            destination_id=destination_id,
        )

from rtiumaapy.datamodel.ClientControlReportType import (
    UMAA_MM_ControlTransfer_ClientControlReportType,
    UMAA_MM_ControlTransfer_ClientControlReportTypeTopic,
)


class ClientControlReportProvider(ReportProvider):
    """ClientControl report provider (MM::ControlTransfer)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ControlTransfer_ClientControlReportType,
            report_topic=UMAA_MM_ControlTransfer_ClientControlReportTypeTopic,
        )


class ClientControlReportConsumer(ReportConsumer):
    """ClientControl report consumer (MM::ControlTransfer)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ControlTransfer_ClientControlReportType,
            report_topic=UMAA_MM_ControlTransfer_ClientControlReportTypeTopic,
        )

from rtiumaapy.datamodel.ClientControlTransferReportType import (
    UMAA_MM_ControlTransfer_ClientControlTransferReportType,
    UMAA_MM_ControlTransfer_ClientControlTransferReportTypeTopic,
)


class ClientControlTransferReportProvider(ReportProvider):
    """ClientControlTransfer report provider (MM::ControlTransfer)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ControlTransfer_ClientControlTransferReportType,
            report_topic=UMAA_MM_ControlTransfer_ClientControlTransferReportTypeTopic,
        )


class ClientControlTransferReportConsumer(ReportConsumer):
    """ClientControlTransfer report consumer (MM::ControlTransfer)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ControlTransfer_ClientControlTransferReportType,
            report_topic=UMAA_MM_ControlTransfer_ClientControlTransferReportTypeTopic,
        )

from rtiumaapy.datamodel.ConditionalReportType import (
    UMAA_MM_ConditionalReport_ConditionalReportType,
    UMAA_MM_ConditionalReport_ConditionalReportTypeTopic,
)


class ConditionalReportProvider(ReportProvider):
    """Conditional report provider (MM::ConditionalReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ConditionalReport_ConditionalReportType,
            report_topic=UMAA_MM_ConditionalReport_ConditionalReportTypeTopic,
        )


class ConditionalReportConsumer(ReportConsumer):
    """Conditional report consumer (MM::ConditionalReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ConditionalReport_ConditionalReportType,
            report_topic=UMAA_MM_ConditionalReport_ConditionalReportTypeTopic,
        )

from rtiumaapy.datamodel.ConditionalStateReportType import (
    UMAA_MM_ConditionalStateReport_ConditionalStateReportType,
    UMAA_MM_ConditionalStateReport_ConditionalStateReportTypeTopic,
)


class ConditionalStateReportProvider(ReportProvider):
    """ConditionalState report provider (MM::ConditionalStateReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ConditionalStateReport_ConditionalStateReportType,
            report_topic=UMAA_MM_ConditionalStateReport_ConditionalStateReportTypeTopic,
        )


class ConditionalStateReportConsumer(ReportConsumer):
    """ConditionalState report consumer (MM::ConditionalStateReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ConditionalStateReport_ConditionalStateReportType,
            report_topic=UMAA_MM_ConditionalStateReport_ConditionalStateReportTypeTopic,
        )

from rtiumaapy.datamodel.ControlSystemControlReportType import (
    UMAA_MM_ControlTransfer_ControlSystemControlReportType,
    UMAA_MM_ControlTransfer_ControlSystemControlReportTypeTopic,
)


class ControlSystemControlReportProvider(ReportProvider):
    """ControlSystemControl report provider (MM::ControlTransfer)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ControlTransfer_ControlSystemControlReportType,
            report_topic=UMAA_MM_ControlTransfer_ControlSystemControlReportTypeTopic,
        )


class ControlSystemControlReportConsumer(ReportConsumer):
    """ControlSystemControl report consumer (MM::ControlTransfer)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ControlTransfer_ControlSystemControlReportType,
            report_topic=UMAA_MM_ControlTransfer_ControlSystemControlReportTypeTopic,
        )

from rtiumaapy.datamodel.ControlSystemTransferReportType import (
    UMAA_MM_ControlTransfer_ControlSystemTransferReportType,
    UMAA_MM_ControlTransfer_ControlSystemTransferReportTypeTopic,
)


class ControlSystemTransferReportProvider(ReportProvider):
    """ControlSystemTransfer report provider (MM::ControlTransfer)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ControlTransfer_ControlSystemTransferReportType,
            report_topic=UMAA_MM_ControlTransfer_ControlSystemTransferReportTypeTopic,
        )


class ControlSystemTransferReportConsumer(ReportConsumer):
    """ControlSystemTransfer report consumer (MM::ControlTransfer)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ControlTransfer_ControlSystemTransferReportType,
            report_topic=UMAA_MM_ControlTransfer_ControlSystemTransferReportTypeTopic,
        )

from rtiumaapy.datamodel.MissionPlanReportType import (
    UMAA_MM_MissionPlanReport_MissionPlanReportType,
    UMAA_MM_MissionPlanReport_MissionPlanReportTypeTopic,
)


class MissionPlanReportProvider(ReportProvider):
    """MissionPlan report provider (MM::MissionPlanReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_MissionPlanReport_MissionPlanReportType,
            report_topic=UMAA_MM_MissionPlanReport_MissionPlanReportTypeTopic,
        )


class MissionPlanReportConsumer(ReportConsumer):
    """MissionPlan report consumer (MM::MissionPlanReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_MissionPlanReport_MissionPlanReportType,
            report_topic=UMAA_MM_MissionPlanReport_MissionPlanReportTypeTopic,
        )

from rtiumaapy.datamodel.MissionPlanAssignmentReportType import (
    UMAA_MM_MissionPlanAssignmentReport_MissionPlanAssignmentReportType,
    UMAA_MM_MissionPlanAssignmentReport_MissionPlanAssignmentReportTypeTopic,
)


class MissionPlanAssignmentReportProvider(ReportProvider):
    """MissionPlanAssignment report provider (MM::MissionPlanAssignmentReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_MissionPlanAssignmentReport_MissionPlanAssignmentReportType,
            report_topic=UMAA_MM_MissionPlanAssignmentReport_MissionPlanAssignmentReportTypeTopic,
        )


class MissionPlanAssignmentReportConsumer(ReportConsumer):
    """MissionPlanAssignment report consumer (MM::MissionPlanAssignmentReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_MissionPlanAssignmentReport_MissionPlanAssignmentReportType,
            report_topic=UMAA_MM_MissionPlanAssignmentReport_MissionPlanAssignmentReportTypeTopic,
        )

from rtiumaapy.datamodel.MissionPlanExecutionReportType import (
    UMAA_MM_MissionPlanExecutionStatus_MissionPlanExecutionReportType,
    UMAA_MM_MissionPlanExecutionStatus_MissionPlanExecutionReportTypeTopic,
)


class MissionPlanExecutionReportProvider(ReportProvider):
    """MissionPlanExecution report provider (MM::MissionPlanExecutionStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_MissionPlanExecutionStatus_MissionPlanExecutionReportType,
            report_topic=UMAA_MM_MissionPlanExecutionStatus_MissionPlanExecutionReportTypeTopic,
        )


class MissionPlanExecutionReportConsumer(ReportConsumer):
    """MissionPlanExecution report consumer (MM::MissionPlanExecutionStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_MissionPlanExecutionStatus_MissionPlanExecutionReportType,
            report_topic=UMAA_MM_MissionPlanExecutionStatus_MissionPlanExecutionReportTypeTopic,
        )

from rtiumaapy.datamodel.ObjectiveAssignmentReportType import (
    UMAA_MM_ObjectiveAssignmentReport_ObjectiveAssignmentReportType,
    UMAA_MM_ObjectiveAssignmentReport_ObjectiveAssignmentReportTypeTopic,
)


class ObjectiveAssignmentReportProvider(ReportProvider):
    """ObjectiveAssignment report provider (MM::ObjectiveAssignmentReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ObjectiveAssignmentReport_ObjectiveAssignmentReportType,
            report_topic=UMAA_MM_ObjectiveAssignmentReport_ObjectiveAssignmentReportTypeTopic,
        )


class ObjectiveAssignmentReportConsumer(ReportConsumer):
    """ObjectiveAssignment report consumer (MM::ObjectiveAssignmentReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ObjectiveAssignmentReport_ObjectiveAssignmentReportType,
            report_topic=UMAA_MM_ObjectiveAssignmentReport_ObjectiveAssignmentReportTypeTopic,
        )

from rtiumaapy.datamodel.ObjectiveExecutionReportType import (
    UMAA_MM_ObjectiveExecutionStatus_ObjectiveExecutionReportType,
    UMAA_MM_ObjectiveExecutionStatus_ObjectiveExecutionReportTypeTopic,
)


class ObjectiveExecutionReportProvider(ReportProvider):
    """ObjectiveExecution report provider (MM::ObjectiveExecutionStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ObjectiveExecutionStatus_ObjectiveExecutionReportType,
            report_topic=UMAA_MM_ObjectiveExecutionStatus_ObjectiveExecutionReportTypeTopic,
        )


class ObjectiveExecutionReportConsumer(ReportConsumer):
    """ObjectiveExecution report consumer (MM::ObjectiveExecutionStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_ObjectiveExecutionStatus_ObjectiveExecutionReportType,
            report_topic=UMAA_MM_ObjectiveExecutionStatus_ObjectiveExecutionReportTypeTopic,
        )

from rtiumaapy.datamodel.OperationalModeReportType import (
    UMAA_MM_OperationalModeStatus_OperationalModeReportType,
    UMAA_MM_OperationalModeStatus_OperationalModeReportTypeTopic,
)


class OperationalModeReportProvider(ReportProvider):
    """OperationalMode report provider (MM::OperationalModeStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_OperationalModeStatus_OperationalModeReportType,
            report_topic=UMAA_MM_OperationalModeStatus_OperationalModeReportTypeTopic,
        )


class OperationalModeReportConsumer(ReportConsumer):
    """OperationalMode report consumer (MM::OperationalModeStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_OperationalModeStatus_OperationalModeReportType,
            report_topic=UMAA_MM_OperationalModeStatus_OperationalModeReportTypeTopic,
        )

from rtiumaapy.datamodel.TaskPlanAssignmentReportType import (
    UMAA_MM_TaskPlanAssignmentReport_TaskPlanAssignmentReportType,
    UMAA_MM_TaskPlanAssignmentReport_TaskPlanAssignmentReportTypeTopic,
)


class TaskPlanAssignmentReportProvider(ReportProvider):
    """TaskPlanAssignment report provider (MM::TaskPlanAssignmentReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_TaskPlanAssignmentReport_TaskPlanAssignmentReportType,
            report_topic=UMAA_MM_TaskPlanAssignmentReport_TaskPlanAssignmentReportTypeTopic,
        )


class TaskPlanAssignmentReportConsumer(ReportConsumer):
    """TaskPlanAssignment report consumer (MM::TaskPlanAssignmentReport)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_TaskPlanAssignmentReport_TaskPlanAssignmentReportType,
            report_topic=UMAA_MM_TaskPlanAssignmentReport_TaskPlanAssignmentReportTypeTopic,
        )

from rtiumaapy.datamodel.TaskPlanExecutionReportType import (
    UMAA_MM_TaskPlanExecutionStatus_TaskPlanExecutionReportType,
    UMAA_MM_TaskPlanExecutionStatus_TaskPlanExecutionReportTypeTopic,
)


class TaskPlanExecutionReportProvider(ReportProvider):
    """TaskPlanExecution report provider (MM::TaskPlanExecutionStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_TaskPlanExecutionStatus_TaskPlanExecutionReportType,
            report_topic=UMAA_MM_TaskPlanExecutionStatus_TaskPlanExecutionReportTypeTopic,
        )


class TaskPlanExecutionReportConsumer(ReportConsumer):
    """TaskPlanExecution report consumer (MM::TaskPlanExecutionStatus)."""

    def __init__(self, ctx: DDSContext, service_name: Optional[str] = None):
        super().__init__(
            ctx,
            service_name=service_name,
            report_type=UMAA_MM_TaskPlanExecutionStatus_TaskPlanExecutionReportType,
            report_topic=UMAA_MM_TaskPlanExecutionStatus_TaskPlanExecutionReportTypeTopic,
        )
